kinesis-lambda-efo/README.md

Perm fix might be rename this dir (`kinesis-lambda-efo`) to (`kinesis-lambda-enhanced-fan-out`).  Not sure if this is generated via automation

fix broken link

---

lambda-sfn/template.yaml

Removed `AWS::IAM::Role` resource and made use of the `Policies` array on both the `AWS::Serverless::Function` and `AWS::Serverless::StateMachine`

fix: removing unnecessary roles

---

apigw-http-api-lambda/src/app.js
apigw-http-api-lambda/template.yml

Function resource is using default Lambda execution role. Removed reference to function execution role in template.

Removed reference to function execution role and updated error message

---

apigw-http-api-lambda/README.md

Fixing the missing link the README file for the API Gateway HTTP API to Lambda pattern. 

fix link in README

---

lambda-s3-sfn/src/functions/processFile/app.js

Update key name to match the key name in saveAndStartStateMachine function so that S3 keys would look like this after processing
- `<key>/initialPayload/<key>.json`
- `<key>/processedPayload/<key>.json`
Should be helpful when debugging step function workflows.

Update key name.

---

s3-sqs-lambda/README.md
s3-sqs-lambda/src/app.js
s3-sqs-lambda/src/package.json
s3-sqs-lambda/template.yaml

[https://github.com/aws-samples/serverless-patterns/issues/29](https://github.com/aws-samples/serverless-patterns/issues/29)
S3 to SQS to Lambda
Create an S3 bucket that sends notifications for created objects to an SQS queue that triggers a lambda function that resizes the image and uploads it to another S3 bucket
This is an update to the [s3-lambda pattern](https://serverlessland.com/patterns/s3-lambda), for busy applications with high throughput to s3 buckets. Using SQS between S3 and Lambda enables scale by retaining the events in the SQS queue and throttling it for downstream services.

Add s3-sqs-lambda pattern

---

s3-sqs/template.yaml

I updated the SQS Queue Policy to match internal AWS security requirements (StringEquals: 'aws:SourceAccount': !Ref 'AWS::AccountId').  Now this pattern can be deployed without generating a Sev 2 ticket.  I also removed the DependsOn attributes that were not needed.

Updated Queue Policy, removed uneccessary DependsOn

---

apigw-vpclink-pvt-alb/README.md
apigw-vpclink-pvt-alb/template.yml

This pattern allows integration of public API gateway endpoint to a private Application Load Balancer with an ECS Fargate cluster behind it.
It allows to build a secure pattern without exposing the private subnet resources and can be accessed only via a VPC Link.
The SAM template in this pattern deploys the following resources. It requires a VPC id and private subnet ids as inputs. It is assumed that the VPC and subnets are already configured with the required network routes.
* Requried Security Groups
* ECS Fargate cluster with service and task definitions
* Private Application Load Balancer with appropriate listener and target group
* VPC Link
* API gateway integration between the API endpoint and the private ALB via the VPC Link
By …

New serverless pattern - apigw-vpclink-pvt-alb

---

apigw-http-api-eventbridge-cdk/README.md
apigw-http-api-eventbridge-cdk/cdk/.gitignore
apigw-http-api-eventbridge-cdk/cdk/.npmignore
apigw-http-api-eventbridge-cdk/cdk/bin/api-eventbridge.ts
apigw-http-api-eventbridge-cdk/cdk/cdk.json
apigw-http-api-eventbridge-cdk/cdk/lib/api-eventbridge-stack.ts
apigw-http-api-eventbridge-cdk/cdk/package.json
apigw-http-api-eventbridge-cdk/cdk/tsconfig.json
apigw-http-api-eventbridge-cdk/pattern-apigateway-http-eventbridge-cdk.json

Similar to the existing HTTP API to Eventbridge, but with CDK instead of SAM.
I also added an Eventbridge Rule targeting Cloudwatch Logs instead of a Lambda. 

HTTP API to Eventbridge using CDK

---

apigw-sfn/template.yaml

There's a small typo in the template.yaml file that causes the error:
```
"Error: Unable to upload artifact statemachine/StateMachine.asl.json referenced by DefinitionUri parameter
of StateMachineExpressSync resource. Parameter DefinitionUri of resource StateMachineExpressSync refers to a
file or folder that does not exist
serverless-patterns/apigw-sfn/statemachine/StateMachine.asl.json"
```
This change fix that.

Fix typo for APIGW-SFN template

---

sfn-apigw/template.yaml

- Typo in the reference to the state machine file.
- State Machine missing log permissions. That would cause the following error:
[StateMachinetoAPIGW]. Rollback requested by user.
ResourceStatus| ResourceType | LogicalResourceId | ResourceStatusReason
-----------------|-------------------------------------|-----------------------|-------------------------------------
CREATE_FAILED | AWS::StepFunctions::StateMachine  | StateMachinetoAPIGW | Resource handler returned message: "The state machine IAM Role is not authorized to access the Log Destination (Service: AWSStepFunctions; Status Code: 400; Error Code: AccessDeniedException; Request ID: 2264351c-57e7-408b-91d9-f0f5984eb7b3; Proxy: null)" (RequestToken: ccf5ac0c-3790-7cf8-17bc-743ee3d73f2c,  HandlerErrorCode: AccessDenied)
- Changes …

Fix log group permission and typo.

---

apigw-rest-api-eventbridge-sam/README.md
apigw-rest-api-eventbridge-sam/template.yaml

https://github.com/aws-samples/serverless-patterns/issues/94
This template creates an API Gateway REST API that puts an event to Amazon EventBridge. This pattern addresses some nuances with defining the VTL template mapping when integrating with EventBridge. An IAM permission for putting events to EventBridge is created for API Gateway.

New pattern - Rest API to EventBridge

---

apigw-to-private-apig-cdk/README.md
apigw-to-private-apig-cdk/src/api/config.json
apigw-to-private-apig-cdk/src/api/dist/index.js
apigw-to-private-apig-cdk/src/api/dist/index.js.map
apigw-to-private-apig-cdk/src/api/index.ts
apigw-to-private-apig-cdk/src/api/lambda/api-handler.ts
apigw-to-private-apig-cdk/src/api/lambda/index.ts
apigw-to-private-apig-cdk/src/index.ts
apigw-to-private-apig-cdk/src/package.json
apigw-to-private-apig-cdk/src/tsconfig.json
apigw-to-private-apig-cdk/src/vpc/index.ts

This pattern in CDK offers an example to create  
a. Amazon API Gateway with a GET / api which invokes private API gateway backed by lambda 
b. Private API endpoint with a greedy proxy ("{proxy+}") and "ANY" method from the specified path, meaning it will accept by default any method and any path. The VPC Lambda function provided in JavaScript only returns the path
c. To make the connection possible following resources are also created
i. VPC Endpoint for execute-api in your VPC
ii. ELB target group using the private IPs created for each AZ as part of the VPC endpoint creation for TCP 443
iii. Private NLB listening on TCP 443 configured to use the target group
iv. VPC link in API Gateway linking NLB created above
By submitting this pull …

Serverless Pattern, API Gateway to Private (VPC) API Gateway

---

sfn-sfn/README.md
sfn-sfn/statemachine/childStateMachine.asl.json
sfn-sfn/statemachine/parentStateMachine.asl.json
sfn-sfn/template.yml

*Issue #, if available:* #114
Initial commit.  
Demonstrates how to use an AWS Step Functions state machine to launch another state machine execution. The SAM template deploys 2 State Machines, where invoking the "Parent" State Machine executes a "Child" State Machine. The AWS SAM template deploys the resources and the IAM permissions required to run the application. 

step function to step function

---

lambda-dynamodb-cdk/README.md
lambda-dynamodb-cdk/cdk/.gitignore
lambda-dynamodb-cdk/cdk/.npmignore
lambda-dynamodb-cdk/cdk/README.md
lambda-dynamodb-cdk/cdk/bin/cdk.ts
lambda-dynamodb-cdk/cdk/cdk.json
lambda-dynamodb-cdk/cdk/jest.config.js
lambda-dynamodb-cdk/cdk/lib/cdk-stack.ts
lambda-dynamodb-cdk/cdk/package.json
lambda-dynamodb-cdk/cdk/src/app.ts
lambda-dynamodb-cdk/cdk/test/cdk.test.ts
lambda-dynamodb-cdk/cdk/tsconfig.json

*Issue #, if available:* 
#120
CDK code describes the Lambda function and DynamoDB table with permissions granted for Lambda to write to DynamoDB using the in-built grantWriteData property. This is the CDK implementation of the lambda-dynamodb example. The function code and the tests remain the same from the SAM version.

lambda to dynamodb cdk

---

apigw-mutualtls-lambda/README.md
apigw-mutualtls-lambda/src/app.js
apigw-mutualtls-lambda/template.yaml

https://github.com/aws-samples/serverless-patterns/issues/179
This pattern deploys an Amazon API Gateway HTTP API with a default route and basic CORS configuration. The default route is integrated with an AWS Lambda function written in Node.js and API is authenticated by certificate based mutual TLS. The function logs the incoming API event and context object to an Amazon CloudWatch Logs log group and returns basic information about the event to the caller.

New serverless pattern - HTTP Api Gateway mutual TLS pattern changes

---

iot-mqttoverhttp-customauth/README.md
iot-mqttoverhttp-customauth/iot-rule-sqs-customauth-pattern.json
iot-mqttoverhttp-customauth/src/app.js
iot-mqttoverhttp-customauth/template.yaml

Issue#: [206](https://github.com/aws-samples/serverless-patterns/issues/206)
Adding a new serverless pattern for IoT that uses rule to forward events received through data endpoint to a SQS queue to be processed by lambda function in batch. Along with this, this app also deploys a custom authorizer for IoT data endpoint to allow users to bring their own authentication as is.

New serverless pattern - IoT to SQS with custom authorizer

---

sfn-glue-sync-cdk/.gitignore
sfn-glue-sync-cdk/README.md
sfn-glue-sync-cdk/app.py
sfn-glue-sync-cdk/cdk.json
sfn-glue-sync-cdk/requirements.txt
sfn-glue-sync-cdk/resources/glue-scripts/hello.py

https://github.com/aws-samples/serverless-patterns/issues/215
This CDK application deploys a Step Functions workflow, that takes in a payload and trigger a AWS Glue job synchronously. In this pattern, the state machine does wait for Glue job to finish. The application contains the minimum IAM resources required to run the workflow and Glue job.

New serverless pattern - sfn-glue-sync-cdk

---

apigw-rest-api-batch-sam/template.yaml

REST API to AWS Batch: Updating the IAM permissions to batch:SubmitJob

REST API to AWS Batch: locking the IAM permissions to batch:SubmitJob

---

parallel-e2e-pipeline-cdk/README.md
parallel-e2e-pipeline-cdk/src/mock-e2e-tests/mock-e2e-1.ts
parallel-e2e-pipeline-cdk/src/mock-e2e-tests/mock-e2e-2.ts
parallel-e2e-pipeline-cdk/src/pipeline/.gitignore
parallel-e2e-pipeline-cdk/src/pipeline/app/constructs/end-to-end-tests.ts
parallel-e2e-pipeline-cdk/src/pipeline/app/constructs/roles/e2e-code-build-role.ts
parallel-e2e-pipeline-cdk/src/pipeline/app/constructs/roles/index.ts
parallel-e2e-pipeline-cdk/src/pipeline/app/constructs/roles/pipeline-role.ts
parallel-e2e-pipeline-cdk/src/pipeline/app/pipeline-stack.ts
parallel-e2e-pipeline-cdk/src/pipeline/cdk.json
parallel-e2e-pipeline-cdk/src/pipeline/main.ts
parallel-e2e-pipeline-cdk/src/pipeline/package.json
parallel-e2e-pipeline-cdk/src/pipeline/tsconfig.json

#219 
Added a new serverless pattern (parallel-e2e-pipeline-cdk) that provides scaffolding for a CI/CD pipeline with a stage, which can be used to run End-to-End-Tests in parallel.

New serverless pattern - parallel-e2e-pipeline-cdk

---

sfn-eventbridge/template.yaml

It seems the log group arn has a trailing :* which deploys fine without errors but did not work and the event never reached the eventbus. Maybe there is a better workaround but constructing the arn without the * seems to resolve it. 
Related to the extra star in console clicking from the rule through to the target shows error message in the cloudwatch console "An error occurred while describing log groups.
1 validation error detected: Value '/aws/events/sfn-eventbridge:*' at 'logGroupNamePrefix' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+"

Fix broken rule

---

sqs-lambda-dynamodb-cdk/README.md

Link to serverlessland for sqs-lambda-dynamodb-cdk pattern page is broken.
Fix a link that points to serverlessland.

fix broken link to serverlessland from sqs-lambda-dynamodb-cdk pattern

---

PUBLISHING.md

Existing command doesn't work and gives error of `cp: _pattern-model is a directory (not copied).`. To remove this error correct command is added by using recursive copy.
- Updated command to modify the command used to copy folder `_pattern-model`.
- Existing command gives below error: 
```javascript
cp: _pattern-model is a directory (not copied).
```

Bug: Updated the command while doing the change path

---

codecommit-s3/README.md
codecommit-s3/template.yaml

Adds a new serverless pattern to backup CodeCommit repositories to S3 buckets, using Lambda, EventBridge, and CodeBuild.

New serverless pattern - codecommit-s3

---

fargate-aurora-serverless-cdk/README.md

Simply typo fix from `aurara` to `aurora`

docs: fix aurora spelling typo

---

eventbridge-api-destinations/4-mongodb/mongoDB.yaml
eventbridge-api-destinations/4-mongodb/testEvent.json
eventbridge-api-destinations/README.md

Added MongoDB API Destination pattern. To run, just enable API Key authentication on MongoDB and run the Cloudformation template and test event 

New API Destination pattern - eventbridge-api-destination-MongoDB

---

eventbridge-api-destinations/7-datadog/DataDogApiDestination.yml
eventbridge-api-destinations/7-datadog/testEvent.json

Added Datadog API Destination pattern. To run, just enable API Key authentication on Datadog and run the Cloudformation template and test event.

New serverless pattern - datadog-event-bridge-api-destination

---

sqs-lambda-rust/Makefile
sqs-lambda-rust/README.md
sqs-lambda-rust/template.yaml

Because the Makefile was already using the cross build I think is best to use arm64 architecture as default.
To be able to use arm64 architecture, we must install [CROSS](https://github.com/rust-embedded/cross)

sqs-lambda-rust: change to arm64 architecture

---

lambda-sqs-rust/Makefile
lambda-sqs-rust/README.md
lambda-sqs-rust/template.yaml

Because the Makefile was already using the cross build I think is best to use arm64 architecture as default.
To be able to use arm64 architecture, we must install [CROSS](https://github.com/rust-embedded/cross) 

lambda-sqs-rust: change to arm64 architecture

---

apigw-http-api-lambda-rust/Cargo.toml
apigw-http-api-lambda-rust/Makefile
apigw-http-api-lambda-rust/README.md
apigw-http-api-lambda-rust/src/bin/handler.rs
apigw-http-api-lambda-rust/template.yml

Create an Amazon API Gateway HTTP API that invokes an AWS Lambda function

New Pattern: apigw-http-api-lambda in rust

---

apigw-http-api-lambda-rust/Makefile
apigw-http-api-lambda-rust/README.md
lambda-s3-rust/Makefile
lambda-s3-rust/README.md
lambda-sfn-rust/Makefile
lambda-sfn-rust/README.md
lambda-sqs-rust/Makefile
lambda-sqs-rust/README.md
s3-eventbridge-direct-rust/Cargo.toml
s3-eventbridge-direct-rust/Makefile
s3-eventbridge-direct-rust/README.md
sqs-lambda-rust/Makefile
sqs-lambda-rust/README.md

I have aligned with one MR all the rust examples already approved instead of doing one fix for each (I hope you do not mind).
I have updated:
- readme instruction (requirements section)
- MakeFile to use zigbuild for cross compilation
I have followed the AWS SA Nicolas Moutschen from a twitter discussion [here](https://twitter.com/NMoutschen/status/1494595443300483072?s=20&t=J2iJiOWY0mW7mjcSIH7lFw)
And you can see the official [recomendation](https://github.com/aws-samples/serverless-rust-demo/pull/41) 

Rust: align all rust examples to use zigbuild for cross compilation

---

eventbridge-api-destinations/8-pagerduty/template.yaml
eventbridge-api-destinations/8-pagerduty/testEvent.json

Added an example of EventBridge API Destination integration with PagerDuty.  Requires an API Key and Integration key from a PagerDuty environment.

PagerDuty EventBridge API Destination 

---

apigw-canary-deployment-cdk/app.py
apigw-canary-deployment-cdk/cdk.json
apigw-canary-deployment-cdk/requirements.txt

#411 
-  updating feature flags in ```cdk.json```
- dependency updates in ```requirements.txt```
- updating imports to use the new ```constructs``` module and consolidated ```aws-cdk-lib``` package

migrated to AWS CDK v2 (python)

---

dynamodb-streams-lambda-terraform/README.md
dynamodb-streams-lambda-terraform/main.tf
dynamodb-streams-lambda-terraform/src/app.js

Deploy DynamoDB table with stream enabled, Lambda function that process the stream records, via Terraform

feature: add dynamodb streams to lambda function pattern via terraform

---

msk-lambda-cdk/bin/msk-lambda-cdk.ts
msk-lambda-cdk/cdk.json
msk-lambda-cdk/lib/msk-lambda-cdk-stack.ts
msk-lambda-cdk/package.json

*Issue #, if available:* closes #503
* updating feature flags in cdk.json
* dependency updates in package.json
* updating imports to use the new constructs and consolidated aws-cdk-lib libraries

migrated to AWS CDK v2 (typescript)

---

appsync-eventbridge/.npmignore
appsync-eventbridge/cdk/.gitignore
appsync-eventbridge/cdk/.npmignore
appsync-eventbridge/cdk/bin/appsync-eventbridge.ts
appsync-eventbridge/cdk/cdk.json
appsync-eventbridge/cdk/lib/appsync-eventbridge-stack.ts
appsync-eventbridge/cdk/package.json

*Issue #, if available:* closes #480
* updating feature flags in cdk.json
* dependency updates in package.json
* updating imports to use the new constructs and consolidated aws-cdk-lib libraries

Schaeedw fix appsync eventbrito cdk2

---

cloudfront-apigw-http-api-lambda-rust/README.md
cloudfront-failover-apigw-http-api-lambda-rust/Cargo.toml
cloudfront-failover-apigw-http-api-lambda-rust/Makefile
cloudfront-failover-apigw-http-api-lambda-rust/README.md
cloudfront-failover-apigw-http-api-lambda-rust/api.yml
cloudfront-failover-apigw-http-api-lambda-rust/cloudfront.yml
cloudfront-failover-apigw-http-api-lambda-rust/src/bin/handler.rs

This pattern follows [Optimizing high availability with CloudFront origin failover](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/high_availability_origin_failover.html)
It will deploy 2 APIGW and 2 Lambda in two different regions, and it will setup a CloudFront distribution on the front with two origins.

New Pattern: CloudFront failover with two apigw http api lambda rust in different regions

---

.gitignore
apigw-http-api-eventbridge-lambda-sls/README.md
apigw-http-api-eventbridge-lambda-sls/api.json
apigw-http-api-eventbridge-lambda-sls/example-pattern.json
apigw-http-api-eventbridge-lambda-sls/package.json
apigw-http-api-eventbridge-lambda-sls/serverless.yml
apigw-http-api-eventbridge-lambda-sls/src/handler.ts
apigw-http-api-eventbridge-lambda-sls/tsconfig.json

#566 
- Add support for APIGW (HTTP API) - EventBridge - Lambda pattern, implemented with Serverless Framework
- replace `.serverless%` with `/*/.serverless/` in .gitignore
- add `/*/.build/` to .gitignore, so that temp folders, created by the `serverless-plugin-typescript` plugin, are not committed to the shared Git repo.

APIGW EventBridge Lambda - Serverless Framework

---

apigw-http-api-eventbridge-java/README.md
apigw-http-api-eventbridge-java/TriggeredLambda/pom.xml
apigw-http-api-eventbridge-java/TriggeredLambda/src/main/java/com/example/App.java
apigw-http-api-eventbridge-java/api.yaml
apigw-http-api-eventbridge-java/example-pattern.json
apigw-http-api-eventbridge-java/template.yaml

A Java port of the pattern showing APIGW HTTP API publishing body to Event Bridge, with a Lambda function triggered from the event. This original pattern is https://serverlessland.com/patterns/apigateway-http-eventbridge. 

Java port of APIGW HTTP to Event Bridge to Lambda Pattern

---

systems-manager-automation-to-lambda/README.md

Regarding the `systems-manager-automation-to-lambda` example, `sam deploy` fails with the error:
```
Error: Failed to create changeset for the stack: sam-app, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Requires capabilities : [CAPABILITY_NAMED_IAM]
```
Add  missing `--capabilities CAPABILITY_NAMED_IAM` to `sam deploy` in the README.md

add missing --capabilities CAPABILITY_NAMED_IAM to sam deploy

---

cloudfront-lambda-url-java/LambdaFunction/pom.xml
cloudfront-lambda-url-java/LambdaFunction/src/main/java/com/example/App.java
cloudfront-lambda-url-java/README.md
cloudfront-lambda-url-java/example-pattern.json
cloudfront-lambda-url-java/template.yml

New pattern showing how to use Lambda function URLs behind CloudFront distribution with Java. 

Java based pattern for CloudFront and Lambda URLs

---

sqs-lambda-report-batchItem-failures-rust/Cargo.toml
sqs-lambda-report-batchItem-failures-rust/Makefile
sqs-lambda-report-batchItem-failures-rust/README.md
sqs-lambda-report-batchItem-failures-rust/event.json
sqs-lambda-report-batchItem-failures-rust/src/bin/handler.rs
sqs-lambda-report-batchItem-failures-rust/template.yaml

- AWS Lambda now supports partial batch response for SQS as an event source. 
- This example shows how to handle a batch of SQS messages in parallel
- This example shows how to handle a partial batch failure 

New serverless pattern: Lambda partial batch response for SQS as an event source with AWS SAM and Rust

---

lambda-function-url-cdk/example-pattern.json

Small fix fixing the JSON file for this pattern, removed the additional comma that was in the file

Fixing invalid JSON - example-pattern for lambda-function-url-cdk

---

.github/workflows/lint.yml
Dockerfile
action.yml
cfn-nag-action/entrypoint.sh
cfn-nag-action/src/cfg-nag.js
cfn-nag-action/src/index.js

This pull request is to introduce automating [cfn-nag](https://github.com/stelligent/cfn_nag) as part of the pull request process for serverless patterns.
When users add new patterns, there is currently a manual process that takes place to run [cfn-nag](https://github.com/stelligent/cfn_nag) to verify the given template file is valid (without errors).
This workflow / GitHub Action will now run this check on any **modified or new** template files added to pull requests.
If no template files have been added to the pull request `cfn-nag` will not be run.
1. On every pull request the workflow **Lint Serverless Pattern** is triggered
2. All changed/added files are gathered and passed into the custom GitHub Action, and templates are filtered.
3. A custom script (inside a docker container with …

Added automation for cfn-nag on pull requests

---

apigw-method-cache/README.md
apigw-method-cache/example-pattern.json
apigw-method-cache/src/app.js
apigw-method-cache/template.yaml

Submission of a new serverless pattern that deploys an Amazon API Gateway REST API endpoint with a method-level cache.

New serverless pattern - apigw-method-cache

---

cognito-user-pool/template.yaml

Updated the Cognito User Pool domain name to include the AWS Account Id. The domain name must be unique across all customers.

Updated the Cognito User Pool Domain name to include the AWS Account Id.

---

apigw-websocket-api-connection-dynamodb/README.md
apigw-websocket-api-connection-dynamodb/example-pattern.json
apigw-websocket-api-connection-dynamodb/template.yaml

… Service integration type and Amazon DynamoDB
Adding pattern that uses Amazon API Gateway WebSocket API and AWS Service integration type with Amazon DynamoDB for the connection tracking. This approach simplifies architecture by eliminating the need to use additional compute components such as AWS Lambda.

New serverless pattern - apigw-websocket-api-connection-dynamodb

---

eventbridge-lambda-terraform/README.md
lambda-eventbridge-terraform/README.md
lambda-sqs-terraform/README.md

Removing references to AWS SAM from Terraform patterns, and some references to AWS Terraform.

Documentation Fix: Removing references to AWS SAM from Terraform patterns

---

systems-manager-automation-to-lambda/template.yaml

*Description of changes: Fix Cfn-lint and cfn_nag warnings. Removing unnecessary explicit resource names that disallow in-place updates for resources. Enable encryption and backups for DynamoDB

fix: make cfn-lint and cfn-nag happy

---

waf-apigw-rest/README.md
waf-apigw-rest/example-pattern.json
waf-apigw-rest/src/app.py
waf-apigw-rest/template.yaml

Adds a pattern creating an AWS WAF WebACL that restricts access to an APIGW REST API based on the originating country of the request.

New serverless pattern - WAF to APIGW REST

---

iot-dynamodb/README.md
iot-dynamodb/example-pattern.json
iot-dynamodb/template.yaml

This sample project demonstrates how to use AWS IoT Topic rules to put incoming event data to DynamoDB. One example demonstrates how to use 'DynamoDB' Action and another example demonstrates how to use 'DynamoDBv2' Action with AWS IoT Topic Rules.

[New Pattern] AWS IoT to DynamoDB

---

elemental-medialive-mediapackage-cdk-ts/lib/media_package_cdn_auth.ts
elemental-medialive-mediapackage-cdk-ts/lib/secrets.ts
elemental-medialive-mediapackage-cdk-ts/lib/streaming_stack.ts
elemental-mediapackage-cloudfront-cdk-ts/README.md
elemental-mediapackage-cloudfront-cdk-ts/helpers/stream_config.ts
elemental-mediapackage-cloudfront-cdk-ts/lib/cloudfront.ts
elemental-mediapackage-cloudfront-cdk-ts/lib/media_package.ts
elemental-mediapackage-cloudfront-cdk-ts/lib/secrets.ts
elemental-mediapackage-cloudfront-cdk-ts/lib/streaming_stack.ts

- Adding CDN Authorization to MediaPackage Endpoints
- On Amazon CloudFront distribution, providing a Header to forward to MediaPackage

Update elemental-mediapackage-cloudfront-cdk-ts to add CDN authorization

---

apigw-route53-failover/README.md
apigw-route53-failover/example-pattern.json
apigw-route53-failover/src/app.py
apigw-route53-failover/template.yaml

Adds pattern for APIGW and Route53 failover from primary to secondary regions

New pattern: APIGW, Route53 failover

---

dynamodb-eventbridge/README.md

*Description of changes:* Update destroy resource command to use _sam delete_ instead of aws cloudformation, keeping the consistency of the tool usage.

use sam delete resources command

---

README.md

Remove duplicated *services* word from the README file

remove duplicate 'services' word from root readme file

---

step-function-sync-rest-api/Readme.md
step-function-sync-rest-api/api.yaml
step-function-sync-rest-api/example-pattern.json
step-function-sync-rest-api/statemachine/stateMachine.asl.json
step-function-sync-rest-api/template.yml

*Description of changes:* The Serverless Pattern deploys an Amazon API Gateway REST API endpoint along with an Express State machine. This setup illustrate how we can invoke an Express State machine and get the output back from the execution to the client (within 29 seconds) using a Rest API. 

New serverless pattern - step-function-sync-rest-api

---

apigw-canary-deployment-cdk/README.md
apigw-canary-deployment-cdk/requirements.txt

*Issue #, if available:* 850
Removed individual aws-cdk requirements - they weren't actually used and were causing a conflict
Fixed the APIGW URL in the testing instructions (should be https).  

Fix for issue 850

---

apigw-lambda-sls/README.md
apigw-lambda-sls/serverless.yml

*Issue #, if available:* N/A
When browsing examples on Serverless Patterns website, I've noticed that some of them could be slightly simplified or improved. This PR includes changes for `apigw-lambda-sls` pattern such as:
1. Fix incorrect link to Serverless Patterns website in the docs. It was pointing to another pattern.
2. Update runtime to `nodejs16.x`
3. Simplify the change of `stage`. The `provider.stage` is only a default stage and overriding it via `--stage <stage>` will be accepted anyway, so no need to write `stage: ${opt:stage, "prod"}`, as it doesn't really change the behavior in a meaningful way and might be more confusing to users
4. Removed setting `region`, because it doesn't differ from the default behavior in any way and only adds confusion for …

Improve `apigw-lambda-sls` pattern

---

waf-appsync-cdk/.gitignore
waf-appsync-cdk/.npmignore
waf-appsync-cdk/README.md
waf-appsync-cdk/cdk-stack.ts
waf-appsync-cdk/cdk.json
waf-appsync-cdk/cdk.ts
waf-appsync-cdk/package.json
waf-appsync-cdk/schema.graphql
waf-appsync-cdk/tsconfig.json
waf-appsync-cdk/waf-appsync-cdk-pattern.json

Adds a new pattern showing WAF2 WebACL association with AWS AppSync graphql API as documented in `Readme.md` with CDK. 

New serverless pattern - waf-appsync-cdk.

---

apigw-rest-api-eventbridge-sqs-sam/README.md
apigw-rest-api-eventbridge-sqs-sam/example-pattern.json
apigw-rest-api-eventbridge-sqs-sam/src/handler.ts
apigw-rest-api-eventbridge-sqs-sam/src/package.json
apigw-rest-api-eventbridge-sqs-sam/src/tsconfig.json
apigw-rest-api-eventbridge-sqs-sam/template.yml

API Gateway REST API to EventBridge with event payload composition and SQS as target
The APIGW payload is sent to EventBridge as a custom event payload. In the integration request, a custom payload is created and passed to EventBridge to target an SQS.

New serverless pattern - API Gateway REST API to EventBridge with event payload composition and SQS as target

---

cognito-restapi-vpclink-cdk/example-pattern.json

*Description of changes:* The website is currently showing `https://www.linkedin.com/in/https://www.linkedin.com/in/justinplock//` as the LinkedIn URL. This should end up showing the proper URL of `https://www.linkedin.com/in/justinplock/`

Fix LinkedIn URL in bio

---

s3-upload-presignedurl-api-cdk-ts/.gitignore
s3-upload-presignedurl-api-cdk-ts/.npmignore
s3-upload-presignedurl-api-cdk-ts/README.md
s3-upload-presignedurl-api-cdk-ts/bin/s3-upload-presignedurl-api-cdk.ts
s3-upload-presignedurl-api-cdk-ts/cdk.json
s3-upload-presignedurl-api-cdk-ts/example-pattern.json
s3-upload-presignedurl-api-cdk-ts/jest.config.js
s3-upload-presignedurl-api-cdk-ts/lib/s3-upload-presignedurl-api-cdk-stack.ts
s3-upload-presignedurl-api-cdk-ts/package.json
s3-upload-presignedurl-api-cdk-ts/tsconfig.json

New pattern : Generation of S3 pre-signed URLs to upload files to S3 from a front 

New serverless pattern - s3-upload-presignedurl-api-cdk-ts 

---

cdk-vpc-lambda-sfn/src/stacks/vpc_stack.ts

There are two inbound rules in the security group, allowing HTTP & HTTPS from 0.0.0.0/0(anyIpv4) which are not unused.
This PR is for removing such rules

Update: stepfn-lambda-vpc -> removed unused inbound secgroup rules

---

dynamodb-streams-lambda-eventbridge-sam-rust/Cargo.toml
dynamodb-streams-lambda-eventbridge-sam-rust/Makefile
dynamodb-streams-lambda-eventbridge-sam-rust/README.md
dynamodb-streams-lambda-eventbridge-sam-rust/events.json
dynamodb-streams-lambda-eventbridge-sam-rust/example-pattern.json
dynamodb-streams-lambda-eventbridge-sam-rust/src/bin/handler.rs
dynamodb-streams-lambda-eventbridge-sam-rust/template.yml

The AWS SAM template deploys a Lambda function, a DynamoDB table and an Amazon EventBridge bus, and the minimum IAM resources required to run the application.
When items are written in the DynamoDB table, the changes are sent to a stream. This pattern configures a Lambda function to poll this stream. The function is invoked with a payload containing the contents of the table item that changed.

New serverless pattern - dynamodb-streams-lambda-eventbridge-sam-rust

---

dynamodb-streams-lambda-eventbridge-sam-node/README.md
dynamodb-streams-lambda-eventbridge-sam-node/events.json
dynamodb-streams-lambda-eventbridge-sam-node/example-pattern.json
dynamodb-streams-lambda-eventbridge-sam-node/package.json
dynamodb-streams-lambda-eventbridge-sam-node/src/handler.ts
dynamodb-streams-lambda-eventbridge-sam-node/template.yml
dynamodb-streams-lambda-eventbridge-sam-node/tsconfig.json

The AWS SAM template deploys a Lambda function, a DynamoDB table and an Amazon EventBridge bus, and the minimum IAM resources required to run the application.
When items are written in the DynamoDB table, the changes are sent to a stream. This pattern configures a Lambda function to poll this stream. The function is invoked with a payload containing the contents of the table item that changed.

New serverless pattern - dynamodb-streams-lambda-eventbridge-sam-node

---

cdk-sns-sqs-eventbridge-pipes-stepfunctions/Makefile
cdk-sns-sqs-eventbridge-pipes-stepfunctions/README.md
cdk-sns-sqs-eventbridge-pipes-stepfunctions/bin/app.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/cdk.context.json
cdk-sns-sqs-eventbridge-pipes-stepfunctions/cdk.json
cdk-sns-sqs-eventbridge-pipes-stepfunctions/environment.json
cdk-sns-sqs-eventbridge-pipes-stepfunctions/example-pattern.json
cdk-sns-sqs-eventbridge-pipes-stepfunctions/jest.config.js
cdk-sns-sqs-eventbridge-pipes-stepfunctions/lib/event-bridge-pipe-construct.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/lib/event-bridge-rule-construct.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/lib/event-bus-construct.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/lib/main-stack.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/lib/sns-sqs-construct.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/lib/state-machine-construct.ts
cdk-sns-sqs-eventbridge-pipes-stepfunctions/package.json
cdk-sns-sqs-eventbridge-pipes-stepfunctions/test/sample-message.json
cdk-sns-sqs-eventbridge-pipes-stepfunctions/tsconfig.json

*Description of changes:* This code demonstrates how to connect an SNS Topic to EventBridge Pipes by way of SQS in the middle.  The Pipe filters the messages, transforms the data and forwards it to an EventBridge Bus that has a Rule which triggers a Step Function.  In existing environments where SNS is heavily used, it gives the developer the ability to bring in EventBridge without rewriting publishers but provides new opportunities for consumers

New serverless pattern -  SNS to EventBridge Pipes triggering a Step Function via EventBus in CDK

---

s3-eventbridge-direct-java/README.md

When I ran the project the first time just with "sam deploy -g" without "sam build", I had to see in cloudwatch that the build was not done because of the "ClassNotFoundException" error.

Added "sam build" before "sam deploy -g"

---

lambda-streaming-large-sam/template.yaml

Issue #, if available:
- Remove hash symbol from InvokeMode value in AWS SAM template `lambda-streaming-large-sam`
- Correct the InvokeMode property value by removing the hash symbol (#) from "RESPONSE_STREAM#"
- This fix ensures the proper configuration of Lambda response streaming

Fix: Remove hash symbol from InvokeMode value in AWS SAM template

---

eventbridge-schedule-to-ssm-sam/README.md
eventbridge-schedule-to-ssm-sam/example-pattern.json
eventbridge-schedule-to-ssm-sam/template.yaml

Added new pattern eventbridge-schedule-to-ssm-sam. EventBridge scheduler task to run a SSM state manager association.

New pattern eventbridge-schedule-to-ssm-sam

---

eventbridge-pipes-msk-iam-auth-to-lambda/example-pattern.json
eventbridge-pipes-msk-to-lambda/example-pattern.json

#1270
A couple of patterns for eventbridge-pipes-msk-to-lambda and eventbridge-pipes-msk-iam-auth-to-lambda have broken github links. Updated those links

Fixing the github broken links

---

eventbridge-schedule-to-sns-cdk-python/.gitignore
eventbridge-schedule-to-sns-cdk-python/README.md
eventbridge-schedule-to-sns-cdk-python/app.py
eventbridge-schedule-to-sns-cdk-python/cdk.json
eventbridge-schedule-to-sns-cdk-python/eventbridge_schedule_to_sns_cdk_python/eventbridge_schedule_to_sns_cdk_python_stack.py
eventbridge-schedule-to-sns-cdk-python/example-pattern.json
eventbridge-schedule-to-sns-cdk-python/requirements.txt

This pattern creates an EventBridge Scheduler schedule that publishes messages to an Amazon SNS topic every 5 minutes. Resources are deployed using AWS CDK for Python. 

New Pattern: EventBridge Scheduler schedule publishes to Amazon SNS

---

cloudwatch-logs-to-splunk-using-lambda-kinesis/README.md
cloudwatch-logs-to-splunk-using-lambda-kinesis/bin/kinesis-data-stream-log-processor.ts
cloudwatch-logs-to-splunk-using-lambda-kinesis/cdk.json
cloudwatch-logs-to-splunk-using-lambda-kinesis/example-pattern.json
cloudwatch-logs-to-splunk-using-lambda-kinesis/package.json
cloudwatch-logs-to-splunk-using-lambda-kinesis/src/index.js
cloudwatch-logs-to-splunk-using-lambda-kinesis/src/lib/mysplunklogger.js
cloudwatch-logs-to-splunk-using-lambda-kinesis/tsconfig.json

Submitting a server-less pattern. This pattern will setup serverless stack with AWS Lambda and Kinesis data stream (KDS) to process continuously streaming CloudWatch logs from different accounts and regions. Lambda receives stream records with CloudWatch log events which it decompress and decode to prepare events to be pushed to Splunk. A log destination ARN need to be configured across all account’s CloudWatch log groups. 

Gourangharhare New serverless pattern - Stream CloudWatch logs to Splunk near real-time

---

apigw-lambda-eventbridge-lambda-sam-java/src/main/java/com/example/publisher/TicketPublisher.java

The first time I deployed the stack an error occurred because the region was different from the hard coded configuration. I just removed the region to build the EventBridgeClient and worked ok.

Removed hard coded configuration for build EventBridgeClient

---

eventbridge-schedule-to-sqs-cdk-java/.gitignore
eventbridge-schedule-to-sqs-cdk-java/README.md
eventbridge-schedule-to-sqs-cdk-java/cdk.json
eventbridge-schedule-to-sqs-cdk-java/example-pattern.json
eventbridge-schedule-to-sqs-cdk-java/pom.xml
eventbridge-schedule-to-sqs-cdk-java/src/main/java/com/myorg/EventBridgeScheduleToSqsCdkApp.java
eventbridge-schedule-to-sqs-cdk-java/src/main/java/com/myorg/EventBridgeScheduleToSqsCdkStack.java
eventbridge-schedule-to-sqs-cdk-java/src/test/java/com/myorg/EventBridgeScheduleToSqsCdkStackTest.java

Pattern that creates an EventBridge Scheduler schedule to send messages to Amazon SQS. Resources are deployed using AWS CDK for Java.

New Pattern: EventBridge Scheduler to SQS (AWS CDK Java)

---

apigw-http-api-lambda-rds-proxy-java/template-rds-proxy.yaml
apigw-http-api-lambda-rds-proxy-terraform/vpc-rds-setup/main.tf
apigw-http-api-lambda-rds-proxy/template-rds-proxy.yaml

`5.7.mysql_aurora.2.09.1`, `5.7.mysql_aurora.2.10.2` is not supported now.
```zsh
$ aws rds describe-db-engine-versions --engine aurora-mysql --query 'DBEngineVersions[].EngineVersion'
[
"5.7.mysql_aurora.2.07.0",
"5.7.mysql_aurora.2.07.1",
"5.7.mysql_aurora.2.07.2",
"5.7.mysql_aurora.2.07.3",
"5.7.mysql_aurora.2.07.4",
"5.7.mysql_aurora.2.07.5",
"5.7.mysql_aurora.2.07.6",
"5.7.mysql_aurora.2.07.7",
"5.7.mysql_aurora.2.07.8",
"5.7.mysql_aurora.2.07.9",
"5.7.mysql_aurora.2.08.3",
"5.7.mysql_aurora.2.11.1",
"5.7.mysql_aurora.2.11.2",
"8.0.mysql_aurora.3.01.0",
"8.0.mysql_aurora.3.01.1",
"8.0.mysql_aurora.3.02.0",
"8.0.mysql_aurora.3.02.1",
"8.0.mysql_aurora.3.02.2",
"8.0.mysql_aurora.3.02.3",
"8.0.mysql_aurora.3.03.0"
]
```
```zsh
$ tf …
```

fix: upgrade aurora version to `5.7.mysql_aurora.2.11.2`

---

eventbridge-schedule-to-sns-publish-cdk-java/README.md
eventbridge-schedule-to-sns-publish-cdk-java/cdk.json
eventbridge-schedule-to-sns-publish-cdk-java/eventbridge-schedule-to-sns-publish-cdk-java.json
eventbridge-schedule-to-sns-publish-cdk-java/example-pattern.json
eventbridge-schedule-to-sns-publish-cdk-java/pom.xml
eventbridge-schedule-to-sns-publish-cdk-java/src/main/java/com/myorg/EventbridgeScheduleToSnsCdkJavaApp.java
eventbridge-schedule-to-sns-publish-cdk-java/src/main/java/com/myorg/EventbridgeScheduleToSnsCdkJavaStack.java

New EventBridge Scheduler pattern: Create EventBridge Scheduler to publish message to SNS topic every 5 minutes with CDK Java Framework.

New serverless pattern - EventBridge Scheduler to SNS with CDK Java Framework

---

eventbridge-schedule-ecs-cdk-java/README.md
eventbridge-schedule-ecs-cdk-java/cdk.json
eventbridge-schedule-ecs-cdk-java/example-pattern.json
eventbridge-schedule-ecs-cdk-java/pom.xml
eventbridge-schedule-ecs-cdk-java/src/main/java/com/myorg/EventbridgeScheduleEcsCdkJavaApp.java
eventbridge-schedule-ecs-cdk-java/src/main/java/com/myorg/EventbridgeScheduleEcsCdkJavaStack.java

New EventBridge Scheduler pattern: Create EventBridge Scheduler to run a task in ECS Cluster every 15 minutes with CDK Java Framework.

New pattern: EventBridge Scheduler to run task in ECS cluster with CDK Java 

---

eventbridge-rule-to-ssm-automation-sam/README.md
eventbridge-rule-to-ssm-automation-sam/example-pattern.json
eventbridge-rule-to-ssm-automation-sam/template.yaml

https://github.com/aws-samples/serverless-patterns/issues/1344
This pattern demonstrates how to create an Amazon EventBridge Rule to trigger based on a specific event, and then run an AWS Systems Manager Automation Runbook using information from the event.

add folder and files for eventbridge-rule-to-ssm-automation pattern

---

fargate-s3-cdk/cdk/src/Dockerfile

useful when you build with Apple M*
force amd64 archi inside the Dockerfile

force amd64 archi

---

apigw-lambda-dynamodb-sam-java/template.yaml

fixed memory size for apigw-lambda-dynamodb-sam-java
*Issue 1382*
fixed memory size to fix the creation of the publisher

1382: fixed memory size for apigw-lambda-dynamodb-sam-java

---

s3-lambda/src/app.js
s3-lambda/src/package.json
s3-lambda/template.yaml

*Description of changes:* The s3-lambda example is using a version of node unsupported by lambda. Updated node to 18, and upgraded the gm and AWS sdk to a recent version.

upgrading s3-lambda to node 18 and aws sdk 3.32

---

cdk-s3-sqs-lambda-dynamodb/.gitignore
cdk-s3-sqs-lambda-dynamodb/README.md
cdk-s3-sqs-lambda-dynamodb/bin/my-cdk-project.ts
cdk-s3-sqs-lambda-dynamodb/cdk.json
cdk-s3-sqs-lambda-dynamodb/data/test.csv
cdk-s3-sqs-lambda-dynamodb/jest.config.js
cdk-s3-sqs-lambda-dynamodb/lambda/index.py
cdk-s3-sqs-lambda-dynamodb/lib/my-cdk-project-stack.ts
cdk-s3-sqs-lambda-dynamodb/package.json
cdk-s3-sqs-lambda-dynamodb/test/my-cdk-project.test.ts
cdk-s3-sqs-lambda-dynamodb/tsconfig.json
data/test.csv

This pattern provides a simple serverless workflow to process data in a csv file and store in DynamoDB table.
The pattern creates an s3 bucket, an s3 object create event listener a sqs queue that receives messages from the s3 object created event. Lambda polls the sqs queue and process data from the csv file and stores in the DynamoDB table.
Steps to deploy and validate the pattern along with sample data are listed in the Readme file.

Shankey28 feature cdk s3 sqs lambda dynamodb

---

eventbridge-schedule-to-batch-terraform/.gitignore
eventbridge-schedule-to-batch-terraform/README.md
eventbridge-schedule-to-batch-terraform/example-pattern.json
eventbridge-schedule-to-batch-terraform/main.tf
eventbridge-schedule-to-batch-terraform/variables.tf
eventbridge-schedule-to-cloudwatch-terraform/.gitignore
eventbridge-schedule-to-cloudwatch-terraform/README.md
eventbridge-schedule-to-cloudwatch-terraform/example-pattern.json
eventbridge-schedule-to-cloudwatch-terraform/main.tf

New pattern using Terraform for EventBridge Scheduler to custom metrics to CloudWatch a schedule.

New serverless pattern - eventbridge-schedule-to-cloudwatch-terraform

---

eventbridge-schedule-to-ec2-terraform/README.md
eventbridge-schedule-to-ec2-terraform/example-pattern.json
eventbridge-schedule-to-ec2-terraform/main.tf
eventbridge-schedule-to-ec2-terraform/variables.tf

This pattern is for scheduling EC2 instances with EventBridge Scheduler using Terraform. 

New serverless pattern - EventBridge Scheduler to EC2 using Terraform

---

eventbridge-schedule-to-step-function-terraform/README.md
eventbridge-schedule-to-step-function-terraform/example-pattern.json
eventbridge-schedule-to-step-function-terraform/main.tf

Added EventBridge Scheduler to Step Functions Pattern

Added EventBridge Scheduler to Step Functions Pattern

---

apigw-lambda-authorizer-custom-header/README.md
apigw-lambda-authorizer-custom-header/example-pattern.json
apigw-lambda-authorizer-custom-header/src/authorizer.js
apigw-lambda-authorizer-custom-header/template.yaml

This pattern provides users a way to inject additional information in the form of a HTTP header by using Lambda Authorizer. It can be used in the use-case where downstream legacy systems expect additional data not available from the original API request.

New Serverless Pattern - Adding custom headers using APIGW and Lambda Token Authorizer

---

eventbridge-sns-lambda/.gitignore
eventbridge-sns-lambda/Readme.md
eventbridge-sns-lambda/example-pattern.json
eventbridge-sns-lambda/src/app.py
eventbridge-sns-lambda/template.yaml

Adding SAM  based pattern for Amazon EventBridge to SNS to Lambda Function.
This sample project demonstrates how to create a SNS Topic can be used as target for an EventBridge rule and then invokes a Lambda function.

SAM based pattern for Eventbridge to SNS to Lambda

---

sqs-stepfunctions-pipes-pattern/README.md
sqs-stepfunctions-pipes-pattern/example-pattern.json
sqs-stepfunctions-pipes-pattern/lambda/lambda_function.py
sqs-stepfunctions-pipes-pattern/statemachine/StateMachine.asl.json
sqs-stepfunctions-pipes-pattern/template.yaml

This pattern demonstrates a seamless integration between an SQS queue and AWS Step Functions using Amazon EventBridge Pipes. It enables direct routing of messages from an SQS queue into a Step Functions state machine, which orchestrates the processing flow and manages AWS Lambda invocation errors. When Lambda encounters an error, the erroneous message is directed to an SQS Dead Letter Queue (DLQ) for further inspection or reprocessing.

New serverless pattern - sqs-stepfunctions-pipes-pattern

---

cdk-vpc-lambda-sfn/README.md
eventbridge-pipes-sqs-to-eventbridge-with-filters/README.md
eventbridge-pipes-sqs-to-eventbridge-with-filters/template.yaml

*Issue #, if available:* aws-samples/serverless-patterns#1559
Granted EventBridge Pipes permission to write to Cloudwatch & Cloudwatch Logs for pattern eventbridge-pipes-sqs-to-eventbridge-with-filters

fix: Granted EventBridge Pipes permission to write to Cloudwatch & Cloudwatch Logs for pattern eventbridge-pipes-sqs-to-eventbridge-with-filters

---

apigw-lambda-comprehend-sam/README.md
apigw-lambda-comprehend-sam/example-pattern.json
apigw-lambda-comprehend-sam/src/app.py
apigw-lambda-comprehend-sam/template.yaml

Adding the  apigw-lambda-comprehend-sam pattern.
This pattern deploys an Amazon API Gateway REST API with an AWS Lambda integration. The Lambda function is written in Python, calls the Amazon Comprehend DetectSentiment API, and returns a response containing the detected sentiment.

Adding apigw-lambda-comprehend-sam pattern

---

lambda-ecr/README.md
lambda-ecr/example-pattern.json
lambda-ecr/template.yaml

*Issue #1579, if available:*
New SAM template that creates a Lambda function running with a container image.
The container image needs to be entered in the parameter of the template from an ECR image already created in the account.

New serverless pattern - Lambda with container image 

---

sns-slack-teams-integration-cdk-python/README.md
sns-slack-teams-integration-cdk-python/app.py
sns-slack-teams-integration-cdk-python/cdk.json
sns-slack-teams-integration-cdk-python/example-pattern.json
sns-slack-teams-integration-cdk-python/lambda/lambda_function.py
sns-slack-teams-integration-cdk-python/requirements.txt
sns-slack-teams-integration-cdk-python/sns_slack_teams_integration_cdk_python/sns_slack_teams_integration_cdk_python_stack.py
sns-slack-teams-integration-cdk-python/source.bat

This pattern demonstrates how you can setup a fully serverless setup to integrate SNS topic with Slack/Teams channel through AWS CDK in Python.

New serverless pattern - sns-slack-teams-integration-cdk-python

---

s3-eventbridge-sns-cdk/README.md
s3-eventbridge-sns-cdk/example-pattern.json
s3-eventbridge-sns-cdk/src/.gitignore
s3-eventbridge-sns-cdk/src/.npmignore
s3-eventbridge-sns-cdk/src/README.md
s3-eventbridge-sns-cdk/src/bin/s3-eventbridge-sns-cdk.ts
s3-eventbridge-sns-cdk/src/cdk.json
s3-eventbridge-sns-cdk/src/jest.config.js
s3-eventbridge-sns-cdk/src/lib/s3-eventbridge-sns-stack.ts
s3-eventbridge-sns-cdk/src/package.json
s3-eventbridge-sns-cdk/src/test/src.test.ts
s3-eventbridge-sns-cdk/src/tsconfig.json

*Issue #1636, if available:*
* Adding a new Serverless pattern S3-Eventbridge-SNS using CDK.
* This pattern deploys one S3 Bucket, SNS Topic, EventBridge rule and a Lambda function which is used internally by CDK to apply configuration notifications on the bucket. 
* This pattern uses AWS CDK to setup an S3 bucket that publishes events to Amazon EventBridge. When an object is uploaded to the bucket, the EventBridge is triggered and a SNS notification is sent to subscribers.

New serverless pattern - s3-eventbridge-sns-cdk

---

rds-sns-event-notification-cdk-ts/README.md
rds-sns-event-notification-cdk-ts/bin/rds-sns-event-notification-cdk-ts.ts
rds-sns-event-notification-cdk-ts/cdk.json
rds-sns-event-notification-cdk-ts/example-pattern.json
rds-sns-event-notification-cdk-ts/jest.config.js
rds-sns-event-notification-cdk-ts/lib/rds-sns-event-notification-cdk-ts-stack.ts
rds-sns-event-notification-cdk-ts/package.json
rds-sns-event-notification-cdk-ts/test/rds-sns-event-notification-cdk-ts.test.ts
rds-sns-event-notification-cdk-ts/tsconfig.json

RDS Event Subscriptions allow users to configure notifications for RDS Events (provided through an SNS topic). This template configures an event subscription for failure, low storage, and availability event categories for RDS Instances.

New serverless pattern - rds-sns-event-notification-cdk-ts

---

eventbridge-pipes-dynamodbstream-to-sqs-serverless/README.md
eventbridge-pipes-dynamodbstream-to-sqs-serverless/example-pattern.json
eventbridge-pipes-dynamodbstream-to-sqs-serverless/index.js
eventbridge-pipes-dynamodbstream-to-sqs-serverless/package.json
eventbridge-pipes-dynamodbstream-to-sqs-serverless/serverless.yml

Created a new serverless framework pattern for DynamoDB Streams to SQS using EventBridge Pipes.

New serverless pattern  - DynamoDB Streams to SQS using EventBridge Pipes

---

kinesis-lambda-terraform/README.md
kinesis-lambda-terraform/example-pattern.json
kinesis-lambda-terraform/main.tf
kinesis-lambda-terraform/src/app.js

My email - rahulrsr@amazon.com

New pattern-kinesis data stream & lambda consumer

---

eventbridge-fan-in-terraform/.gitignore
eventbridge-fan-in-terraform/README.md
eventbridge-fan-in-terraform/data.tf
eventbridge-fan-in-terraform/example-pattern.json
eventbridge-fan-in-terraform/main.tf
eventbridge-fan-in-terraform/outputs.tf
eventbridge-fan-in-terraform/provider.tf
eventbridge-fan-in-terraform/src/app.js
eventbridge-fan-in-terraform/terraform.tfvars
eventbridge-fan-in-terraform/variables.tf

New serverless pattern to allow eventbridge fan-in of multiple Eventbus (in same region) to a central Eventbus in another region using Terraform

New serverless pattern - Eventbridge fan-in using Terraform

---

eventbridge-api-destinations/11-oauth-api/template.yaml
eventbridge-api-destinations/11-oauth-api/testEvent.json
eventbridge-api-destinations/README.md

*Description of changes:* This pattern creates an Amazon Eventbridge API Destination to invoke APIs protected by OAuth authorization. Eventbrige supports Basic, OAuth, and API Key authentication. This pattern exchanges OAuth Client Credentials - Authorization endpoint, HTTP method, Client ID, and Client secret for an access token and then manages it securely using AWS Secrets Manager. The template also creates a SQS dead letter queue to track any failures during API invocation. 

New pattern: Eventbridge API Destination example for OAuth API integration

---

aurora-serverless-global-db-cdk/.gitignore
aurora-serverless-global-db-cdk/.npmignore
aurora-serverless-global-db-cdk/README.md
aurora-serverless-global-db-cdk/bin/aurora-global-db-multistack.ts
aurora-serverless-global-db-cdk/cdk.json
aurora-serverless-global-db-cdk/example-pattern.json
aurora-serverless-global-db-cdk/fargate/Dockerfile
aurora-serverless-global-db-cdk/fargate/package.json
aurora-serverless-global-db-cdk/fargate/src/index.js
aurora-serverless-global-db-cdk/jest.config.js
aurora-serverless-global-db-cdk/lib/aurora-global-cluster-stack.ts
aurora-serverless-global-db-cdk/lib/aurora-regional-cluster-stack.ts
aurora-serverless-global-db-cdk/lib/fargate-test-app-stack.ts
aurora-serverless-global-db-cdk/package.json
aurora-serverless-global-db-cdk/test/global-aurora-serverless-cdk.test.ts
aurora-serverless-global-db-cdk/tsconfig.json

The pattern creates a serverless global database cluster enabling data replication from the primary to secondary cluster. The regional primary cluster contains a serverless db instance supporting both writes and reads. The regional secondary cluster contains a serverless db instance supporting only reads. In the unlikely event of a regional degradation or outage, the secondary region can be promoted to read and write capabilities in less than 1 minute. A fargate based application is also provisioned to test the replication. Also the pattern adopts the multiple stack capability of CDK to provision the resources across the primary and secondary regions. You can deploy each stack individually or deploy all the stacks using --all option.
By …

New serverless pattern - Amazon Aurora Serverless V2 Primary to Secondary Global Database

---

s3-event-sfn-lambda-ddb-sns/README.md
s3-event-sfn-lambda-ddb-sns/example-pattern.json
s3-event-sfn-lambda-ddb-sns/friends.csv
s3-event-sfn-lambda-ddb-sns/src/lambda-dynamoDb.py
s3-event-sfn-lambda-ddb-sns/template.yaml

*Issue #1726, if available:*
The SAM template deploys an Amazon S3 bucket that publishes events to Amazon EventBridge, and sets up an AWS Step Functions workflow to show how to consume these events via an EventBridge rule. It deploys the the IAM resources required to run the application. It also deploys a Lambda function, SNS topic and DynamoDB table. EventBridge consumes events directly from S3 buckets when the NotificationConfiguration is enabled, as shown in the template. 

New serverless pattern - s3-event-sfn-lambda-ddb-sns

---

lambda-extension-telemetryapi-s3/.gitignore
lambda-extension-telemetryapi-s3/README.md
lambda-extension-telemetryapi-s3/example-pattern.json
lambda-extension-telemetryapi-s3/extensionsrc/extensions/telemetryapi-s3-extension.py
lambda-extension-telemetryapi-s3/extensionsrc/makefile
lambda-extension-telemetryapi-s3/extensionsrc/requirements.txt
lambda-extension-telemetryapi-s3/sampleappsrc/app.py
lambda-extension-telemetryapi-s3/sampleappsrc/requirements.txt
lambda-extension-telemetryapi-s3/template.yaml

Add a new serverless pattern - Lambda extension using Telemetry API send Lambda log to S3 

Add new pattern Lambda-extension-telemetryapi-s3

---

apigw-rest-sagemaker/README.md
apigw-rest-sagemaker/example-pattern.json
apigw-rest-sagemaker/template.yaml

*Issue #1651
New SAM template that creates a Sagemaker endpoint for the Flan-T5 foundation model in Amazon SageMaker JumpStart and a REST API with AWS service integration to invoke the SageMaker endpoint.

New Serverless pattern - API Gateway REST API to SageMaker

---

apigw-sqs-lambda/.vscode/launch.json
appsync-notify-subscribers-of-database-updates/3-lambda/template.yml
eventbridge-lambda/template.yaml
kinesis-lambda-efo/template.yaml
kinesis-lambda/template.yaml
lambda-dynamodb/template.yaml
lambda-lambda/template.yaml
lambda-rekognition/template.yaml
lambda-s3-sfn/template.yaml
lambda-sfn/template.yaml
lambda-sns-sms/template.yaml
lambda-sns/template.yaml
lambda-sqs/template.yaml
msk-lambda/template.yaml
s3-object-lambda/template.yaml
s3-sqs-lambda/template.yaml
sfn-apigw/template.yaml
sfn-lambda-dynamodb/template.yml
sfn-lambda/template.yaml
sns-lambda/template.yaml
terraform-s3-object-lambda/main.tf

CloudFormation templates in serverless-patterns have been found to include a soon to be [deprecated Lambda function runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) (nodejs12.x). The affected templates have been updated to a supported runtime (nodejs16.x).
Please note, **this pull request has been generated by a bot**; please check the base branch and files changed before merging.

Upgrade deprecated runtime nodejs12.x

---

lambda-streaming-ttfb-write-sam-with-bedrock-streaming/README.md
lambda-streaming-ttfb-write-sam-with-bedrock-streaming/example-pattern.json
lambda-streaming-ttfb-write-sam-with-bedrock-streaming/src/index.js
lambda-streaming-ttfb-write-sam-with-bedrock-streaming/template.yaml

add example to demonstrate how to read data properly from bedrock streaming inference api with AWS JS SDK v3, along with streaming LLM response with lambda streaming ability using write()
1. Example code to demonstrate how to read from `InvokeModelWithResponseStreamCommand` inference streaming response with javascript SDK v3.
2. Demonstrate how to streaming inference response with lambda function, to support a streaming experience with llarge language model.

New Serverless Pattern. bedrock streaming inference integration with lambda streaming function

---

s3-lambda-bedrock/.gitignore
s3-lambda-bedrock/README.md
s3-lambda-bedrock/example-pattern.json
s3-lambda-bedrock/sampletext.txt
s3-lambda-bedrock/src/app.py
s3-lambda-bedrock/src/requirements.txt
s3-lambda-bedrock/template.yaml

This is a new pattern to integrate S3 to Lambda to Bedrock. This pattern is useful for LLM RAG Usecases in getting vector embeddings of the documents uploaded to S3 via S3 event notification. Once the files are placed in S3, AWS Lambda picks up the files via event notification and post the content to Amazon Bedrock embedding model and gets the vector embedding of the content as response.

New serverless pattern - s3 - lambda - bedrock

---

sns-firehose-tf/README.md
sns-firehose-tf/example-pattern.json
sns-firehose-tf/main.tf

*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1893
*Description of changes:* This pattern publishes SNS messages to a Kinesis Firehose Delivery Stream so that they can be forwarded to archival or analytics destinations.

New serverless pattern - Amazon SNS to Amazon Kinesis Data Firehose (Terraform) 

---

lambda-node-esm-cdk/cdk/node-esm-stack.ts

Uses the `node:` prefix also for the `path` import
PS: thanks for the awesome example, @lucamezzalira! ❤️

Minor: Consistent `node:` prefix in imports for `lambda-node-esm-cdk`

---

eventbridge-schedule-to-sns-tf/README.md
eventbridge-schedule-to-sns-tf/example-pattern.json
eventbridge-schedule-to-sns-tf/main.tf

*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1917
*Description of changes:* This pattern will create an EventBridge schedule to send a message to an Amazon SNS topic every 5 minutes.

New serverless pattern - Amazon EventBridge Scheduler to Amazon SNS (Terraform)

---

terraform-ecs-efs-integration/Readme.md
terraform-ecs-efs-integration/bin/build.sh
terraform-ecs-efs-integration/bin/dir_md5.sh
terraform-ecs-efs-integration/containercode/Dockerfile
terraform-ecs-efs-integration/containercode/sample-bash.sh
terraform-ecs-efs-integration/example-pattern.json
terraform-ecs-efs-integration/main.tf
terraform-ecs-efs-integration/templates/ecr-lifecycle-policy.json
terraform-ecs-efs-integration/templates/ecs-role.json
terraform-ecs-efs-integration/templates/kms-policy.json
terraform-ecs-efs-integration/variables.tf
terraform-ecs-efs-integration/versions.tf

*Issue #, if available:* 1854
Added terraform code,  a sample docker file a sample bash script which will run inside the container

New Serverless pattern for ECS and EFS Integration using terraform

---

.github/workflows/manual-validate-for-pattern.yml
dynamodb-streams-lambda-filters-tf/README.md
dynamodb-streams-lambda-filters-tf/example-pattern.json
dynamodb-streams-lambda-filters-tf/src/handler.py
dynamodb-streams-lambda-filters-tf/tf/ddb.tf
dynamodb-streams-lambda-filters-tf/tf/lambda.tf
dynamodb-streams-lambda-filters-tf/tf/provider.tf
dynamodb-streams-lambda-filters-tf/tf/variable.tf
scripts/validate.js

This pattern demonstrates how to lambda functions that can recieve DynamoDB Stream with filters. The IaC has been definied in Terraform. 

New pattern submission - Dynamodb Streams to lambda with filters in Terraform

---

eventbridge-api-destinations-idempotency-cdk/README.md
eventbridge-api-destinations-idempotency-cdk/example-pattern.json
eventbridge-api-destinations-idempotency-cdk/src/.gitignore
eventbridge-api-destinations-idempotency-cdk/src/.npmignore
eventbridge-api-destinations-idempotency-cdk/src/README.md
eventbridge-api-destinations-idempotency-cdk/src/bin/eb-api-destination.ts
eventbridge-api-destinations-idempotency-cdk/src/cdk.json
eventbridge-api-destinations-idempotency-cdk/src/events.json
eventbridge-api-destinations-idempotency-cdk/src/jest.config.js
eventbridge-api-destinations-idempotency-cdk/src/lib/eb-api-destination-stack.ts
eventbridge-api-destinations-idempotency-cdk/src/package.json
eventbridge-api-destinations-idempotency-cdk/src/test/eb-api-destination.test.ts
eventbridge-api-destinations-idempotency-cdk/src/tsconfig.json

*Issue #, if available:* #1952
*Description of changes:* This pattern describe how to use EventBridge API Destinations with the IETF HTTP `Idempotency-Key` [header](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/) to invoke HTTP APIs supporting idempotent API operations.

feat: Add API Destinations idempotency pattern

---

apigw-websocket-api-bedrock-streaming/apigw-websocket-api-bedrock-streaming.json
apigw-websocket-api-bedrock-streaming/example-pattern.json

- modified API Gateway label to WebSocket and renamed the JSON file

Fix: modify Serverlessland URL path and update diagram label to WebSocket API

---

_pattern-model/example-pattern.json

The current format of `gitHub.template.templateFile` expects just the file name. However, the `example-pattern.json` still shows the full path including the folder which leads to validation errors.

Update templateFile in example-pattern.json

---

apigw-http-api-eventbridge-lambda-sls/package.json
apigw-http-api-eventbridge-lambda-sls/serverless.yml

*Issue #, if available:* N/A
When browsing examples on Serverless Patterns website, I've noticed that some of them could be slightly simplified or improved. This PR includes changes for `apigw-http-api-eventbridge-lambda-sls` pattern such as:
- Update of runtime to `nodejs20.x`. Current `nodejs14.x`-based example is not deployable
- Remove unnecessary override of `provider.region` as the provided override configuration is the same as the default
- Added `deploymentMethod` to make the deployment faster by using direct CloudFormation `updateStack` instead of going through changesets which are slower
- Removed unnecessary `memorySize` on function level as it's already set on `provider`
- Bump versions of dependencies
Please let me know what do you think 🙇 
By …

feat(apigw-http-api-eventbridge-lambda-sls): Modernize the example

---

lambda-layer-terraform/main.tf

Use of `filebase64sha256` has been known to cause issues. Hence refactoring to `output_base64sha256`
Reference documentation and solution: https://github.com/hashicorp/terraform/issues/30042#issuecomment-981766743

refactor(lambda-layer): use output_base64sha256 source code hash

---

lambda-aurora-serverlessv2-postgresql/README.md
lambda-aurora-serverlessv2-postgresql/example-pattern.json
lambda-aurora-serverlessv2-postgresql/lambda-aurora-serverlessv2-postgresql.json
lambda-aurora-serverlessv2-postgresql/src/app.py
lambda-aurora-serverlessv2-postgresql/src/event.json
lambda-aurora-serverlessv2-postgresql/template.yaml

Currently, [lambda-aurora-serverless](https://github.com/aws-samples/serverless-patterns/tree/main/lambda-aurora-serverless) creates an Aurora Serverless v1 cluster. Now that the [Data API is available for Aurora Serverless v2, but PostgreSQL only](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-aurora-postgresql-rds-data-api/), this new pattern creates a PostgreSQL Aurora Serverless v2 cluster.

New serverless pattern: lambda-aurora-serverlessv2-postgresql

---

lambda-node-esm-cdk/cdk/node-esm-stack.ts
lambda-node-esm-cdk/package.json

…version like in previous release
I've updated the dependencies in the package.json, specifically:
- new version of CDK and CDK lib
- removed the unused dependencies like the alpha packages of HTTP API in favour of the stable versions in aws-cdk-lib
- update the analyse script in the package.json
- added the ```@types/aws-lambda``` and removed the wrong package ```aws-lambda```

Update lambda esm node

---

eventbridge-api-destinations-cloudevents-cdk-typescript/.gitignore
eventbridge-api-destinations-cloudevents-cdk-typescript/.npmignore
eventbridge-api-destinations-cloudevents-cdk-typescript/README.md
eventbridge-api-destinations-cloudevents-cdk-typescript/bin/eventbridge-api-destinations-cloudevents-cdk-typescript.ts
eventbridge-api-destinations-cloudevents-cdk-typescript/cdk.json
eventbridge-api-destinations-cloudevents-cdk-typescript/eventbridge-api-destinations-cloudevents-cdk-typescript.json
eventbridge-api-destinations-cloudevents-cdk-typescript/example-pattern.json
eventbridge-api-destinations-cloudevents-cdk-typescript/jest.config.js
eventbridge-api-destinations-cloudevents-cdk-typescript/lib/cdk-stack.ts
eventbridge-api-destinations-cloudevents-cdk-typescript/package.json
eventbridge-api-destinations-cloudevents-cdk-typescript/tsconfig.json

feat: eventbridge api-d cloudevents

---

waf-apigw-rest/template.yaml

*Fix race condition when creating a WAF ACL Association resource:*
CloudFormation expects the api gateway stage to be created, to fix this we can Reference our Api Gateway Stage resource using ${logicalId.Stage}
This fixes an issue I got when testing the proposed template
```
AWS WAF couldn?t perform the operation because your resource doesn?t exist.
```

fix: web acl association race condition

---

eventbridge-schedule-remove-one-time-schedules-cdk-python/example-pattern.json

this is a correction to earlier pull request : 
https://github.com/aws-samples/serverless-patterns/pull/1992
https://serverlessland.com/patterns/eventbridge-schedule-remove-one-time-schedules-cdk-python
i see the project merged successfully. but the github project folder name not accessible from serverlessland and  need to be corrected as below.  
Incorrect path used :
https://github.com/aws-samples/serverless-patterns/tree/main/eventbridge-schedule-remove-onetime-schedule-to-sns-cdk-python
Correct path to be used :
https://github.com/aws-samples/serverless-patterns/tree/main/eventbridge-schedule-remove-one-time-schedules-cdk-python
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

eventbridge-schedule-remove-onetime-cdk-pthon-serverless-pattern - folder name correction

---

s3-sqs-eventbridge-pipe-sfn-s3/README.md
s3-sqs-eventbridge-pipe-sfn-s3/s3-sqs-eventbridge-pipe-sfn-s3.json
s3-sqs-eventbridge-pipe-sfn-s3/template.yaml
s3-sqs-eventbridge-pipe-sfn-s3/workflow/s3-sqs-eventbridge-pipe-sfn-s3.asl.json

*Issue #, if available:*  #2086
This sample project demonstrates how to copy an object between two S3 buckets and manipulate it in transit. When an object is created in the source S3 bucket, an S3 Event Notification is fires and enqueued onto an SQS Queue. The EventBridge service polls the SQS Queue and invokes an EventBridge pipe. The EventBridge Pipe then executes an AWS Step Functions Express Workflow state machine. This copies the file from the source S3 Bucket to the destination S3 Bucket. In a real world scenario the state machine would be modified to manipulate the file as desired

Adding a pattern to copy an object between two S3 buckets using S3 Event Notification to SQS to EventBridge Pipes to Step Function

---

alb-lambda-rust/Cargo.toml
alb-lambda-rust/src/bin/handler.rs
apigw-http-api-lambda-rust/Cargo.toml
apigw-http-api-lambda-rust/src/bin/handler.rs
apigw-lambda-rust/Cargo.toml
apigw-lambda-rust/src/bin/handler.rs
appconfig-lambda-rust/Cargo.toml
cloudfront-apigw-http-api-lambda-rust/Cargo.toml
cloudfront-apigw-http-api-lambda-rust/src/bin/handler.rs
cloudfront-failover-apigw-http-api-lambda-rust/Cargo.toml
cloudfront-lambda-url-rust/Cargo.toml
cloudfront-lambda-url-rust/src/bin/handler.rs
dynamodb-streams-lambda-eventbridge-sam-rust/Cargo.toml
eventbridge-lambda-rust/Cargo.toml
lambda-dynamodb-rust/Cargo.toml
lambda-dynamodb-rust/src/bin/handler.rs
lambda-eventbridge-rust/Cargo.toml
lambda-eventbridge-rust/src/bin/handler.rs
lambda-rekognition-rust/Cargo.toml
lambda-rekognition-rust/src/bin/handler.rs
lambda-s3-rust/Cargo.toml
lambda-s3-rust/src/bin/handler.rs
lambda-sfn-rust/Cargo.toml
lambda-sqs-rust-sam/Cargo.toml
s3-eventbridge-rust-sam/Cargo.toml
sns-sqs-lambda-rust-sam/Cargo.toml
sns-sqs-lambda-rust-sam/src/bin/handler.rs
sqs-lambda-partial-batch-rust-sam/Cargo.toml
sqs-lambda-partial-batch-rust-sam/src/bin/handler.rs
sqs-lambda-rust-sam/Cargo.toml

Nov 27, 2023 - AWS announces the general availability of the AWS SDK for Rust
This MR align the current examples with the current official version of the AWS SDK for Rust

Rust: update example to GA version of AWS SDK for Rust

---

dynamodb-eventbridge-transformer/README.md
dynamodb-eventbridge-transformer/src/README.md

_Issue #, if available:_
_Description of changes:_  
Multiple customers have approached us because they were searching for this pattern but unable to identify it. The reason was that they searched for the term "unmarshall", rather than "removing type descriptors". I added the term to increase discoverability.

Clarified readme

---

eventbridge-cloudwatch-cdk-java/README.md
eventbridge-cloudwatch-cdk-java/cdk.json
eventbridge-cloudwatch-cdk-java/event.json
eventbridge-cloudwatch-cdk-java/eventbridge-cloudwatch-logs-cdk-java.json
eventbridge-cloudwatch-cdk-java/example-pattern.json
eventbridge-cloudwatch-cdk-java/pom.xml
eventbridge-cloudwatch-cdk-java/src/main/java/com/myorg/EventBridgeToCloudWatchLogsStack.java
eventbridge-cloudwatch-cdk-java/src/main/java/com/myorg/EventBridgeToCloudWatchLogsStackApp.java

Adds a sample AWS CDK template to create an EventBridge Rule that forwards events to CloudWatch logs.

New serverless pattern - eventbridge-cloudwatch-cdk-java

---

sns-sqs-fanout-cdk-java/README.md
sns-sqs-fanout-cdk-java/cdk.json
sns-sqs-fanout-cdk-java/example-pattern.json
sns-sqs-fanout-cdk-java/pom.xml
sns-sqs-fanout-cdk-java/sns-sqs-fanout-cdk-java.json
sns-sqs-fanout-cdk-java/src/main/java/com/myorg/SnsToSqsFanOutApp.java
sns-sqs-fanout-cdk-java/src/main/java/com/myorg/SnsToSqsFanOutStack.java

Added fanout pattern using SNS and SQS with CDK (Java). Subscription filters are used to route SNS topics to the the correct SQS queue.

New serverless pattern - sns-sqs-fanout-cdk-java 

---

eventbridge-schedule-to-cloudwatch-alarm-terraform/README.md
eventbridge-schedule-to-cloudwatch-alarm-terraform/eventbridge-schedule-to-cloudwatch-alarm-terraform.json
eventbridge-schedule-to-cloudwatch-alarm-terraform/example-pattern.json
eventbridge-schedule-to-cloudwatch-alarm-terraform/main.tf
eventbridge-schedule-to-cloudwatch-alarm-terraform/variable.tf

*Issue #2172, if available:*
New Terraform template that creates two EventBridge Scheduler schedules to enable and disable the action of a CloudWatch alarm

New Terraform template - EventBridge Scheduler to CloudWatch Alarm

---

eventbridge-api-destinations/2-slack/example-pattern.json

N/A
This fixes the link to the mentioned blog since acloudguru is no more.

Fix blog link since acloudguru is no more

---

s3-sqs-lambda-bedrock-s3-cdk-python/README.md
s3-sqs-lambda-bedrock-s3-cdk-python/app.py
s3-sqs-lambda-bedrock-s3-cdk-python/cdk.json
s3-sqs-lambda-bedrock-s3-cdk-python/example-pattern.json
s3-sqs-lambda-bedrock-s3-cdk-python/lambda/index.py
s3-sqs-lambda-bedrock-s3-cdk-python/lambda/prompt_template.txt
s3-sqs-lambda-bedrock-s3-cdk-python/lambda/sample_input_1.txt
s3-sqs-lambda-bedrock-s3-cdk-python/lambda/sample_input_2.txt
s3-sqs-lambda-bedrock-s3-cdk-python/lambda/sample_input_3.txt
s3-sqs-lambda-bedrock-s3-cdk-python/package.json
s3-sqs-lambda-bedrock-s3-cdk-python/requirements.txt
s3-sqs-lambda-bedrock-s3-cdk-python/s3-sqs-lambda-bedrock-s3-cdk-python.json
s3-sqs-lambda-bedrock-s3-cdk-python/s3_sqs_lambda_bedrock_s3_cdk_python/s3_sqs_lambda_bedrock_s3_cdk_python_stack.py
s3-sqs-lambda-bedrock-s3-cdk-python/tests/unit/test_s3_sqs_lambda_bedrock_s3_cdk_python_stack.py

This pattern creates an Amazon S3 bucket that sends 'OBJECT_CREATED' events to an SQS queue. These events are then processed by a Lambda function that utilizes Amazon Bedrock to extract the summary or sentiment of the input file. The summary is subsequently stored in a different S3 bucket for consumption. 

New pattern submission: Amazon S3, SQS, Lambda, and Bedrock CDK Python

---

apigw-websocket-api-sqs-lambda/template.yaml

*Description of changes:* If input payload from ApiGW contains `&`, it parses the payload as a parameter key to SQS, causing the transformation to fail.

fix an issue that causes the VTL to fail if input payload contains '&'

---

lambda/template.yaml

Refs: https://github.com/aws-samples/serverless-patterns/issues/2290
Updates nodejs version to 20.x
```
$ sam deploy --guided
...
CREATE_FAILED             AWS::Lambda::Function     SimpleFunction            Resource handler        
returned message: "The  
runtime parameter of    
nodejs14.x is no longer 
supported for creating  
or updating AWS Lambda  
functions. We recommend 
you use the new runtime 
(nodejs20.x) while      
creating or updating    
functions. (Service:    
Lambda, Status Code:    
400, Request ID: c492d1 
48-2b9e-4b74-bb84-3650a 
0c5f726)"               
(RequestToken: cff98e85 
-94ad-c6da-9d6e-5d667e9 
fbf6b,                  
HandlerErrorCode:       
InvalidRequest)         
CREATE_FAILED …
```

chore(lambda): update nodejs version to 20.x

---

apigw-websocket-api-sqs-lambda/src/SQSWebsocketResponse.js
apigw-websocket-api-sqs-lambda/template.yaml
appsync-notify-subscribers-of-database-updates/3-lambda/externalDepsLayer/nodejs/package.json
appsync-notify-subscribers-of-database-updates/3-lambda/src/lambdaUsesEventBridge.js
appsync-notify-subscribers-of-database-updates/3-lambda/src/lambdaUsesIAM.js
appsync-notify-subscribers-of-database-updates/3-lambda/template.yml
cfn-custom-resource-s3-create/src/app.js
cfn-custom-resource-s3-create/template.yml
lambda-aurora-serverless/src/app.js
lambda-aurora-serverless/template.yml
lambda-iot-sam/cf-customResource/GetIoTEndpoint.js
lambda-iot-sam/src/handler.js
lambda-iot-sam/src/handler.ts
lambda-iot-sam/template.yaml
lambda-ssm-parameter/src/app.js
lambda-ssm-parameter/template.yml
s3-object-lambda/src/app.js
s3-object-lambda/template.yaml

Refs: https://github.com/aws-samples/serverless-patterns/issues/2290
Updates samples which use AWS SDK for JavaScript from node 16 to 20.
The AWS SDK for JavaScript v2 APIs were migrated to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).

chore: update samples with JS SDK from node 16 to 20

---

cognito-restapi/README.md
cognito-restapi/template.yaml

*Issue #, if available:* Fixes 2254

Bumped nodejs version and clarified readme

---

s3-lambda-bedrock-aoss/README.md
s3-lambda-bedrock-aoss/dependencies/requirements.txt
s3-lambda-bedrock-aoss/src/index_creation.py
s3-lambda-bedrock-aoss/src/requirements.txt
s3-lambda-bedrock-aoss/template.yaml

…s.txt to dependencies folder and enabled sam build to build layers, added AOSS Index fields mapping during creation
*Issue #, if available:* 2288
Corrected default values in template.yml for AOSS resources
Added requirements.txt and Metadata section to LayerVersion to enable layer build using SAM
Updated README to update dependency build step to use sam build
Updated IndexCreationLambda function to add field mappings to newly created AoSS Index

FIX to existing pattern - Issue#2288

---

cloudfront-oac-lambda-url-nodejs-cdk/.gitignore
cloudfront-oac-lambda-url-nodejs-cdk/.npmignore
cloudfront-oac-lambda-url-nodejs-cdk/README.md
cloudfront-oac-lambda-url-nodejs-cdk/bin/cloudfront-oac-lambda-url-nodejs-cdk.js
cloudfront-oac-lambda-url-nodejs-cdk/cdk.json
cloudfront-oac-lambda-url-nodejs-cdk/cloudfront-oac-lambda-url-nodejs-cdk.json
cloudfront-oac-lambda-url-nodejs-cdk/jest.config.js
cloudfront-oac-lambda-url-nodejs-cdk/lambda/index.js
cloudfront-oac-lambda-url-nodejs-cdk/lib/cloudfront-oac-lambda-url-nodejs-cdk-construct.js
cloudfront-oac-lambda-url-nodejs-cdk/lib/cloudfront-oac-lambda-url-nodejs-cdk-stack.js
cloudfront-oac-lambda-url-nodejs-cdk/package.json
cloudfront-oac-lambda-url-nodejs-cdk/pattern.json
cloudfront-oac-lambda-url-nodejs-cdk/tsconfig.json

This pattern shows how to protect AWS Lambda URL origins by using CloudFront Origin Access Control (OAC) to only allow access from designated CloudFront distributions.

New serverless pattern - cloudfront-oac-lambda-url-nodejs-cdk

---

eventbridge-pipes-sqs-to-timestream/README.md
eventbridge-pipes-sqs-to-timestream/command.sh
eventbridge-pipes-sqs-to-timestream/eventbridge-pipes-sqs-to-timestream.json
eventbridge-pipes-sqs-to-timestream/example-pattern.json
eventbridge-pipes-sqs-to-timestream/template.yaml

https://github.com/aws-samples/serverless-patterns/issues/2329
This commit adds a new pattern to ingest data into a Timestream table from SQS Queue using EventBrigde Pipes.

New serverless pattern - eventbridge-pipes-sqs-to-timestream

---

eventbridge-schedule-remove-one-time-schedules-cdk-python/eventbridge-schedule-remove-one-time-schedules-cdk-python.json

*Issue #, if available:* #2380
Fixing the reference to the incorrect folder path in the json file.

Fixing broken github URL - eventbridge-schedule-remove-one-time-schedules-cdk-python

---

.github/workflows/create_update_release.yaml

**Description:**
This PR is to support downloading the code for a pattern easily. By creating a release for each pattern code, it'll be easy to download the code for a user by just downloading the respective asset of that pattern.
This PR adds a new GitHub Action that will create a release (v1.0.0) with all pattern folders saved as asset in the release. If the PR already exists and there are new changes to the repo, it'll update the respective asset in the release.
**Acknowledgement**

Adding Git Release

---

lambda-esm-ddb-filters-sam/README.md
lambda-esm-ddb-filters-sam/example-pattern.json

*Issue #, if available:* [2406](https://github.com/aws-samples/serverless-patterns/issues/2406)
Updating this pattern to warn users of DDB streams read throttling.
As mentioned in the issue's comments, I had to restore the json file, the only update to it is I added the following line:
```
"Please note that this template is meant to be for testing, you can subscribe more than two Lambda functions to a DynamoDB Stream, but you'll likely experience read throttling, refer to the GitHub template README for more information.",
```

Update Serverless Pattern - DDB Stream read throttling advice

---

s3-lambda-dotnet/ImageResize/Function.cs
s3-lambda-dotnet/README.md
s3-lambda-dotnet/template.yaml

Previous policy gave me the below error when trying to invoke the Lambda function:
```
errorType": "AmazonS3Exception",
"errorMessage": "User: arn:aws:sts::683517028648:assumed-role/s3dotnet-ResizerFunctionRole-TZwnuYpDb5Rv/s3dotnet-ResizerFunction-12oroDMZmSGE is not authorized to perform: s3:GetObject on resource: \"arn:aws:s3:::imageresizer-683517028648/seshub-photo.jpeg\" because no identity-based policy allows the s3:GetObject action"
```
Updated the policy so the Lambda function role has proper permissions. Tested that invocation works with updated policy.

Updated policy so lambda function role has proper permissions

---

s3-lambda-resizing-dotnet/README.md
s3-lambda-resizing-dotnet/template.yaml
s3-lambda-resizing-node/README.md
s3-lambda-resizing-node/template.yaml

Updated S3-Lambda resizing images pattern READMEs with new names of patterns (`s3-lambda-resizing-node` and `s3-lambda-resizing-dotnet`).

Update resizing READMEs with correct names

---

s3-sqs-lambda-terraform/README.md
s3-sqs-lambda-terraform/example-pattern.json
s3-sqs-lambda-terraform/main.tf
s3-sqs-lambda-terraform/s3-sqs-lambda-terraform.json
s3-sqs-lambda-terraform/src/app.mjs

Adding s3-sqs-lambda-terraform pattern
Adding the terraform version of Add s3-sqs-lambda pattern
https://serverlessland.com/patterns/s3-sqs-lambda?ref=search
[example-pattern.json](https://github.com/user-attachments/files/16124255/example-pattern.json)

Add s3-sqs-lambda-terraform pattern

---

apigw-sfn-crud-terraform/Postman.json
apigw-sfn-crud-terraform/README.md
apigw-sfn-crud-terraform/apigw-sfn-crud-terraform.json
apigw-sfn-crud-terraform/crud-asl.json
apigw-sfn-crud-terraform/example-pattern.json
apigw-sfn-crud-terraform/main.tf

https://github.com/aws-samples/serverless-patterns/issues/2443
Adding terraform version of apigw-sfn-crud pattern
https://serverlessland.com/patterns/apigw-sfn-crud

Adding apigw-sfn-crud-terraform pattern

---

lambda-aurora-serverlessv2-postgresql/README.md
lambda-aurora-serverlessv2-postgresql/template.yaml

1. Amazon Aurora Serverless v2 supports scaling to zero capacity
2. Update to python 3.13
3. Set CloudWatch LogGroup for Lambda functions

lambda-aurora-serverlessv2-postgresql: aurora scales to zero

---

cloudfront-lambda-url-iam-cdk-ts/README.md
cloudfront-lambda-url-iam-cdk-ts/cdk/.gitignore
cloudfront-lambda-url-iam-cdk-ts/cdk/.npmignore
cloudfront-lambda-url-iam-cdk-ts/cdk/bin/cdk.ts
cloudfront-lambda-url-iam-cdk-ts/cdk/cdk.json
cloudfront-lambda-url-iam-cdk-ts/cdk/lambda-edge/authEdge.js
cloudfront-lambda-url-iam-cdk-ts/cdk/lambda-edge/package.json
cloudfront-lambda-url-iam-cdk-ts/cdk/lambda/handler.ts
cloudfront-lambda-url-iam-cdk-ts/cdk/lib/cdk-stack.ts
cloudfront-lambda-url-iam-cdk-ts/cdk/package.json
cloudfront-lambda-url-iam-cdk-ts/cdk/tsconfig.json
cloudfront-lambda-url-iam-cdk-ts/cloudfront-lambda-url-iam-cdk-ts.json
cloudfront-lambda-url-iam-cdk-ts/example-pattern.json

New pattern describing how to connect Cloudfront to Lambda via an IAM-protected Lambda URL, with CDK and TS.

New serverless pattern - cloudfront-lambda-url-iam-cdk-ts

---

cloudwatch-account-subscription-Lambda-sns-notification/README.md
cloudwatch-account-subscription-Lambda-sns-notification/cloudwatch-account-subscription-Lambda-sns-notification.json
cloudwatch-account-subscription-Lambda-sns-notification/example-pattern.json
cloudwatch-account-subscription-Lambda-sns-notification/notification-lambda/index.py
cloudwatch-account-subscription-Lambda-sns-notification/template.yaml

This sample project demonstrates an alerting system using CloudWatch Logs Subscription filter to a Lambda function to trigger a SNS notification when the original function encounters timeout
- Currently we dont have out of box offering to alert the customer when there Lambda function encounters timeout. For time sensitive applciations Customer would like to get notification when their Lambda function is timedout",
- This pattern deploys one SNS topic with email subsciption, CloudWatch loggroup and Subscription filter, 
two Lambda functions - sample Lambda [ to demonstrate timeout ] , notification Lambda [Is triggered by CloudWatch log Subscription and publish a SNS message]

New serverless pattern - lambda-cloudwatch-subscription-sns-notification

---

rekognition-s3-detectlabels-python/README.md
rekognition-s3-detectlabels-python/example-pattern.json
rekognition-s3-detectlabels-python/rekognition-s3-detectlabels-python.json
rekognition-s3-detectlabels-python/src/lambda_function.py
rekognition-s3-detectlabels-python/template.yaml

*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/2569
This is a new PR created for a new serverless pattern that involves S3, Eventbridge, Lambda and Rekognition deployed using SAM that detects labels in an image.

new serverless pattern - rekognition-s3-detectlabels-python

---

apigw-http-api-lambda-rds-proxy/template-rds-proxy.yaml
apigw-http-api-lambda-rds-proxy/template.yaml

- Updated underlying template to create rds proxy + rds with up to date aurora mysql version
- Updated main template to use the latest python3.13 (up to date sam cli required).
Tested both templates in us-east-1 with success.

Apigw http api lambda rds proxy

---

delayed-eventbridge-events-terraform/README.md
delayed-eventbridge-events-terraform/delayed-eventbridge-events-terraform.json
delayed-eventbridge-events-terraform/example-pattern.json
delayed-eventbridge-events-terraform/main.tf
delayed-eventbridge-events-terraform/src/email-customer/index.mjs
delayed-eventbridge-events-terraform/src/process-user-created/index.mjs

*Issue #2376, if available:*
It is initial commit for creating terraform serverless pattern of [delayed-eventbridge-events](https://serverlessland.com/patterns/delayed-eventbridge-events). This terraform pattern listens for EventBridge events, processes them and creates schedules for every user. 24 hours after user has been created a schedule is run that publishes events directly into EventBridge.

Terraform serverless pattern - delayed-eventbridge-events

---

eventbridge-pipes-sqs-to-eventbridge-with-filters/README.md

Added missing quote in json body for OrderId,

---

apigw-rest-api-sqs-lambda-bedrock-cdk/README.md
apigw-rest-api-sqs-lambda-bedrock-cdk/src/invoke-model/lambda_function.py
apigw-rest-api-sqs-lambda-bedrock-cdk/src/invoke-model/requirements.txt

Prior to this change the Lambda Function would fail requests to Amazon Bedrock when Anthropic Claude 3 or Anthropic Claude 3.5 Models were chosen for the requests.
Lambda function has been updated with Anthropic Claude Messaging API. 

Pattern update - apigw-rest-api-sqs-lambda-bedrock-cdk 

---

apigw-translate/README.md
apigw-translate/apigw-translate.json
apigw-translate/events/event.json
apigw-translate/example-pattern.json
apigw-translate/template.yaml

This pattern creates a REST API Gateway that can perform POST API Call to Amazon Translate's TranslateText API directly using AWS service integration type.

New serverless pattern-apigw-translate

---

lambda-translate-tf/README.md
lambda-translate-tf/example-pattern.json
lambda-translate-tf/iam.tf
lambda-translate-tf/lambda-translate-tf.json
lambda-translate-tf/main.tf
lambda-translate-tf/outputs.tf
lambda-translate-tf/src/index.py
lambda-translate-tf/variables.tf

This pattern shows how to deploy a terraform template that builds a Lambda function which calls translate for text translation.

New serverless pattern - Text translation with Lambda and Translate (Terraform)

---

terraform-sqs-lambda/main.tf

N/A
Hi😀 Thanks for the useful patterns!
I updated the Lambda Python runtime version to `python3.12`.
While testing `terraform-sqs-lambda`, I noticed that the Lambda runtime version `python3.8` was deprecated. Although it's still deployable at the moment, it will not be allowed after **October 1, 2025**.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
To prevent future deployment issues, I updated the runtime to `python3.12`.
https://github.com/terraform-aws-modules/terraform-aws-lambda
`terraform apply` completed successfully.
> [!WARNING]
> Warning is likely caused by the fact that the AWS provider version is currently at v6 (due to `>= 4.9` constraint), and `data.aws_region.current.name` is now a deprecated attribute. …

terraform-sqs-lambda: Update runtime to python3.12

---

apigw-sqs-terraform/README.md

N/A
Hi😀 Thanks for the useful patterns!
I tried the pattern and  works good.
One thing I noticed. This pattern uses the [aws_api_gateway_rest_api](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api) resource in Terraform, but the README mentions `API Gateway HTTP APIs`. As you may know, Amazon API Gateway provides [two types](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html). This pattern is actually using **REST APIs**, not HTTP APIs.
It might be better to clarify this in the README to avoid confusion.
Thank you😀
---

apigw-sqs-terraform: Fix service name correctly

---

eventbridge-lambda-terraform/.gitignore
eventbridge-lambda-terraform/main.tf

N/A
Hi😀 Thanks for the useful patterns!
To prevent future deployment issues, I updated the Lambda Node.js runtime version to `nodejs22.x`.
While testing `eventbridge-lambda-terraform`, I noticed that the Lambda runtime version `nodejs16.x` was deprecated. Although it's still deployable at the moment, it will not be allowed after **October 1, 2025**.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
`terraform apply` completed successfully and works good.
```sh
$ aws events put-events --entries file://event.json --region us-east-1
{
"FailedEntryCount": 0,
"Entries": [
{
"EventId": "d51b5dd2-c12f-70f1-cd71-fc0ab611cbf1"
}
]
}
```
Thank you😀
---
By submitting this pull request, I confirm that you can use, modify, copy, and …

eventbridge-lambda-terraform: Update runtime to nodejs22.x
