apigw-http-api-lambda/README.md, apigw-http-api-lambda/src/app.js, apigw-http-api-lambda/template.yml
Submitting a new serverless pattern for consideration.
=> Add apigw-http-api-lambda

apigw-sqs-lambda/.vscode/launch.json, apigw-sqs-lambda/README.md, apigw-sqs-lambda/api.yaml, apigw-sqs-lambda/event.json, apigw-sqs-lambda/src/app.js, apigw-sqs-lambda/template.yaml
Submitting a new serverless pattern for consideration.
=> Add Queue based leveling pattern

sqs-lambda/template.yaml
Removed unnecessary policy template for brevity
=> fix: Removing unnecessary policy

apigw-sqs-lambda/template.yaml
Removed  unnecessary policy template and changed to latest supported nodejs version
=> Removing unnecessary policy

apigw-http-api-lambda/template.yml
Description of changes: 
Removed unnecessary execution role as it gets added by the SAM transform
=> fix: removing unnecessary role

apigw-rest-api-dynamodb/README.md, apigw-rest-api-dynamodb/template.yml
This pattern creates an Amazon API Gateway REST API that integrates with an Amazon DynamoDB table.
=> Added new serverless pattern - apigw-rest-api-dynamodb

lambda-ssm-parameter/README.md, lambda-ssm-parameter/events/getEvent.json, lambda-ssm-parameter/events/putEvent.json, lambda-ssm-parameter/src/app.js, lambda-ssm-parameter/template.yml
Added new serverless pattern - lambda-ssm-parameter
=> Added new serverless pattern - lambda-ssm-parameter

apigw-sqs-lambda/README.md, apigw-sqs-lambda/api.yaml, apigw-sqs-lambda/template.yaml
Added test steps and cleaned some code for consistency
=> Apigw sqs lambda

lambda-s3/README.md, lambda-s3/src/app.py, lambda-s3/template.yaml
Adding Lambda-S3 Pattern for Serverlessland.
=> Adding AWS Lambda-AWS S3 Pattern

s3-sqs/src/README.md, s3-sqs/template.yaml
Sends notifications from S3 to SQS when an object is created
=> Adding AWS S3-AWS SQS Pattern

s3-sns/src/README.md, s3-sns/template.yaml
=> Adding AWS S3-AWS SNS Pattern

eventbridge-scheduled-lambda/README.md, eventbridge-scheduled-lambda/src/app.py, eventbridge-scheduled-lambda/template.yaml
Amazon EventBridge Scheduled to AWS Lambda Pattern
=> Amazon EventBridge Scheduled to AWS Lambda Pattern

cdk-cloudfront-to-s3-and-lambda/cdk/lib/cloudfront/cors.js, cdk-cloudfront-to-s3-and-lambda/cdk/lib/cloudfront/rewrite.js
Two files that are required for the pattern to function were ignored by the .gitignore and got missed out!
=> added files that were excluded by .gitignore

apigw-websocket-api-lambda/README.md, apigw-websocket-api-lambda/src/onconnect.js, apigw-websocket-api-lambda/src/ondisconnect.js, apigw-websocket-api-lambda/src/post.js, apigw-websocket-api-lambda/template.yml
This pattern creates an Amazon API Gateway WebSocket API and an AWS Lambda function.
=> Added new pattern - Amazon API Gateway WebSocket API and an AWS Lambda function

sfn-sqs/README.md, sfn-sqs/template.yaml
https://github.com/aws-samples/serverless-patterns/issues/52
Adding the AWS Step Functions to SQS (without callback from SQS) for serverless land.
=> Sfn to sqs

lambda-ses/README.md, lambda-ses/lambda-to-ses.json, lambda-ses/src/app.js, lambda-ses/template.yaml
New Serverless Pattern: Lambda to SES
=> New Serverless Pattern - Lambda to SES

cfn-custom-resource-s3-create/README.md, cfn-custom-resource-s3-create/src/app.js, cfn-custom-resource-s3-create/src/cfn-response.js, cfn-custom-resource-s3-create/template.yml
This pattern creates an Amazon S3 object by using an AWS CloudFormation custom resource and an AWS Lambda function.
=> Added new serverless pattern: cfn-custom-resource-s3-create

sfn-dynamodb/README.md, sfn-dynamodb/template.yaml
https://github.com/aws-samples/serverless-patterns/issues/59
Adding the AWS Step Functions to DynamoDB integration (PutItem & GetItem) for serverless land
=> Added Step Function to DynamoDB integration

cognito-httpapi/template.yaml
Fixes a minor typo in app.handler
=> Fixes minor typo in app.handler

PUBLISHING.md
=> Created publishing file

lambda-aurora-serverless/README.md, lambda-aurora-serverless/src/app.js, lambda-aurora-serverless/src/event.json, lambda-aurora-serverless/template.yml
Added new serverless pattern - lambda-aurora-serverless
=> Added new serverless pattern - lambda-aurora-serverless

s3-sns/template.yaml, s3-sqs-lambda/template.yaml, s3-sqs/template.yaml
Added aws:SourceAccount Condition to three templates.
=> Added aws:SourceAccount Condition

apigw-rest-api-dynamodb/template.yml
Changed from dynamodb:* to dynamodb:PutItem and dynamodb:Query.
=> Reduced IAM permissions to required only.

sfn-eventbridge/README.md, sfn-eventbridge/template.yaml
Added new serverless pattern - sfn-eventbridge
=> Added new serverless pattern - sfn-eventbridge

appsync-dynamodb/README.md
=> Fixed title typo

appsync-dynamodb/README.md
=> Fixed a typo and removed a space for a proper name.

msk-lambda/README.md, msk-lambda/example-pattern.json, msk-lambda/src/app.js, msk-lambda/template.yaml
*Issue #, if available:* #86
This pattern deploys a Lambda function that uses an Amazon MSK topic as an event source.
=> New serverless pattern - Parnabbasak feature msk lambda

private-apigw-lambda-cdk/README.md, private-apigw-lambda-cdk/src/api/config.json, private-apigw-lambda-cdk/src/api/dist/index.js, private-apigw-lambda-cdk/src/api/dist/index.js.map, private-apigw-lambda-cdk/src/api/index.ts, private-apigw-lambda-cdk/src/api/lambda/api-handler.ts, private-apigw-lambda-cdk/src/api/lambda/index.ts, private-apigw-lambda-cdk/src/ec2/index.ts, private-apigw-lambda-cdk/src/index.ts, private-apigw-lambda-cdk/src/package.json, private-apigw-lambda-cdk/src/tsconfig.json, private-apigw-lambda-cdk/src/vpc/index.ts
*Description of changes:* Add private API Gateway pattern
=> Private API gateway

private-apigw-lambda-cdk/README.md
*Description of changes: Update to testing instruction
=> Updated Testing Instruction

eventbridge-cloudwatch/event.json
Update sample event to use custom EventBusName specified in SAM template. Remove duplicate Detail property. 
=> Update event bus name in sample event

apigw-http-api-lambda-rds-proxy/template.yaml
=> fix: remove unused paramter for VPC id

lambda-aurora-serverless/template.yml
I removed the separate IAM Role resource and replaced with the SAM managed policies for the Lambda function.  Also, secretsmanager:DescribeSecret was not required.
=> Updated template to use SAM policies

eventbridge-lambda-cdk/.gitignore, eventbridge-lambda-cdk/README.md, eventbridge-lambda-cdk/cdk/app.py, eventbridge-lambda-cdk/cdk/cdk.json, eventbridge-lambda-cdk/cdk/event.json, eventbridge-lambda-cdk/cdk/lambda-handler.py, eventbridge-lambda-cdk/cdk/requirements.txt
https://github.com/aws-samples/serverless-patterns/issues/118
Initial commit. Provides CDK code (Python) to create an EventBridge Rule and a Lambda function. The Lambda function code (Python) simply logs the incoming event to CloudWatch Logs.
=> cdk eventbridge lambda

s3-lambda/README.md
Updated example.jpg name to match filename in events folder.
=> Updated ReadMe for S3 to Lambda pattern

cdk-lambda-appsync/README.md
Simple update of URL to correct Lambda URL.
=> docs: update lambda url

lambda-ssm-parameter/template.yml
I updated the template to use SAM policies in the Lambda function.
=> Using SAM policies in Lambda function

eventbridge-sns-cdk/.gitignore, eventbridge-sns-cdk/README.md, eventbridge-sns-cdk/app.py, eventbridge-sns-cdk/cdk.json, eventbridge-sns-cdk/event.json, eventbridge-sns-cdk/requirements.txt
https://github.com/aws-samples/serverless-patterns/issues/188
This CDK template deploys a SNS topic that is triggered by an EventBridge rule. The SNS topic policy provides the permission for EventBridge to invoke the SNS topic.
=> New serverless pattern - eventbridge-sns-cdk

apigw-iam/README.md, apigw-iam/src/app.js, apigw-iam/template.yaml
#190 
Creates Amazon API Gateway REST API with IAM authorizer
=> New serverless pattern - apigw-iam

lambda-s3-sfn/README.md
=> Fixed some grammar

apigw-http-api-lambda-cdk/.gitignore, apigw-http-api-lambda-cdk/README.md, apigw-http-api-lambda-cdk/app.py, apigw-http-api-lambda-cdk/cdk.json, apigw-http-api-lambda-cdk/requirements.txt, apigw-http-api-lambda-cdk/src/index.py
This pattern creates an Amazon API Gateway HTTP API and an AWS Lambda function using AWS Cloud Development Kit (AWS CDK) in Python. This template also has a sample CORS configuration. The sample application was developed in Python and it shows some context, event and environment variables properties.
=> New serverless pattern - apigw-http-api-lambda-cdk

apigw-rest-api-batch-sam/README.md, apigw-rest-api-batch-sam/template.yaml
This template creates an API Gateway REST API integration with AWS Batch and can submit jobs to AWS Batch. This pattern addresses some nuances with defining the VTL template mapping when integrating with AWS Batch. It also creates an IAM execution role with permissions to submit AWS Batch job.
=> New pattern - API Rest API to AWS Batch

lambda-sfn/template.yaml
I was unable to deploy the stack, so made a few tweaks. Template format error: Unresolved resource dependencies [StateMachine.StateMachineName]
Fixed StateMachineName to get the name. Tweaked output to show the Satemachine Arn and Lambda Name (needed to send test event)
=> bug: Unresolved resource dependencies

sfn-log-export/README.md, sfn-log-export/src/functions/cloudwatch_snapshot/index.py, sfn-log-export/src/functions/export_status_check/index.py, sfn-log-export/src/functions/query_log_groups/index.py, sfn-log-export/src/statemachine/stateMachine.asl.json, sfn-log-export/template.yaml
Adding CloudWatch Log export to S3 using SNF on monthly schedule triggered by EventBridge rules.
=> New serverless pattern - SFN export logs to S3

lambda-efs-cdk/README.md, lambda-efs-cdk/app.py, lambda-efs-cdk/cdk.json, lambda-efs-cdk/lambda_efs_cdk/lambda_efs_cdk_stack.py, lambda-efs-cdk/lambda_function/lambda_function.py, lambda-efs-cdk/requirements.txt, lambda-efs-cdk/setup.py, lambda-efs-cdk/source.bat
This pattern demosntrate how to call EFS from Lambda.
=> New Serverless Pattern - lambda-efs-cdk

apigw-lambda-dynamodb/README.md, apigw-lambda-dynamodb/src/index.py, apigw-lambda-dynamodb/template.yaml
API Gateway to Lambda to DynamoDB
This pattern demonstrates how making an HTTP POST request to an Amazon API Gateway endpoint invokes an AWS Lambda function and inserts an item into an Amazon DynamoDB table.
=> New Serverless pattern - API Gateway to Lambda to DynamoDB

apigw-canary-deployment-cdk/.gitignore, apigw-canary-deployment-cdk/README.md, apigw-canary-deployment-cdk/app.py, apigw-canary-deployment-cdk/cdk.json, apigw-canary-deployment-cdk/requirements.txt, apigw-canary-deployment-cdk/src/index.py
N/A
Add pattern for an API Gateway Canary deployment using the AWS CDK
=> New pattern submission - apigw canary deployment cdk

sqs-lambda-cdk/README.md, sqs-lambda-cdk/cdk/.gitignore, sqs-lambda-cdk/cdk/.npmignore, sqs-lambda-cdk/cdk/README.md, sqs-lambda-cdk/cdk/bin/cdk.ts, sqs-lambda-cdk/cdk/cdk.json, sqs-lambda-cdk/cdk/jest.config.js, sqs-lambda-cdk/cdk/lib/cdk-stack.ts, sqs-lambda-cdk/cdk/package.json, sqs-lambda-cdk/cdk/test/cdk.test.ts, sqs-lambda-cdk/cdk/tsconfig.json
The CDK template deploys a Lambda function, an SQS queue and the IAM permissions required to run the application. SQS invokes the Lambda function when new messages are available.
=> serverless pattern - sqs to lambda using cdk

s3-eventbridge/README.md, s3-eventbridge/template.yaml
*Issue #, if available:* NA
*Description of changes:
Fixed bucket policy since cloudformation stack was failing.
Updated readme
=> Fix Bucket Policy issue, update Readme

lambda-sns-cdk/README.md, lambda-sns-cdk/src/app.py, lambda-sns-cdk/src/cdk.json, lambda-sns-cdk/src/lambda/handler.py, lambda-sns-cdk/src/requirements.txt
Creation of a Lambda to SNS pattern implemented in the AWS CDK.
=> New Serverless pattern - Lambda to SNS CDK 

sfn-callback-cdk/README.md, sqs-lambda-cdk-python/README.md, sqs-lambda-eb-cdk-python/README.md
cleanup typo and remove duplicate line in readme.
=> Cornelcroi fix cleanup readme

aurora-serverless-s3-ingestion/README.md
Fixed some Typos on  aurora-serverless-s3-ingestion/readme.md file.
=> Updated Readme.md on aurora-serverless-s3-ingestion

iot-mqttoverhttp-customauth/README.md, iot-mqttoverhttp-customauth/template.yaml
=> update to read me and fix authorizer policy

cdk-vpc-lambda-sfn/.gitignore, cdk-vpc-lambda-sfn/.npmignore, cdk-vpc-lambda-sfn/README.md, cdk-vpc-lambda-sfn/app.ts, cdk-vpc-lambda-sfn/cdk.json, cdk-vpc-lambda-sfn/jest.config.js, cdk-vpc-lambda-sfn/package.json, cdk-vpc-lambda-sfn/src/lambda_code/app.js, cdk-vpc-lambda-sfn/src/lambda_code/package.json, cdk-vpc-lambda-sfn/src/stacks/lambda_stack.ts, cdk-vpc-lambda-sfn/src/stacks/sfn_stack.ts, cdk-vpc-lambda-sfn/src/stacks/vpc_stack.ts, cdk-vpc-lambda-sfn/tsconfig.json
This pattern in CDK offers a example to generate an Amazon State Machine which
consumes AWS Lambda function which is deployed inside AWS VPC.
Learn more about this pattern at Serverless Land Patterns: https://serverlessland.com/patterns/vpc-lambda-sfn
Important: this application uses various AWS services and there are costs associated with these services after the Free Tier usage - please see the [AWS Pricing page](https://aws.amazon.com/pricing/) for details. You are responsible for any AWS costs incurred. No warranty is implied in this example.
* [Create an AWS account](https://portal.aws.amazon.com/gp/aws/developer/registration/index.html) if you do not already have one and log in. The IAM user that you use must have sufficient permissions to make necessary AWS service calls and manage …
=> New Pattern: AWS State Functions (SFN) integration with AWS VPC Lambda

apigw-lambda-qldb/README.md, apigw-lambda-qldb/src/create-person.js, apigw-lambda-qldb/src/delete-person.js, apigw-lambda-qldb/src/get-person-history.js, apigw-lambda-qldb/src/get-person.js, apigw-lambda-qldb/src/package.json, apigw-lambda-qldb/src/update-person.js, apigw-lambda-qldb/template.yaml
This pattern shows how to deploy a SAM template with Amazon API Gateway, AWS Lambda and Amazon Quantum Ledger Database (QLDB). The API Gateway exposes a REST API with a number of methods. Each API method uses a Lambda proxy integration to invoke a separate AWS Lambda function that interacts with a ledger in Amazon QLDB. This allows you to create a new Person record, update the record, view the current state of the record, and view the entire revision history.
=> New serverless pattern -  APIGW-Lambda-QLDB 

dynamodb-streams-lambda-event-filters/README.md, dynamodb-streams-lambda-event-filters/src/dynamodb-delete-trigger.js, dynamodb-streams-lambda-event-filters/src/dynamodb-insert-trigger.js, dynamodb-streams-lambda-event-filters/template.yaml
Added event pattern for DynamoDB Streams - Lambda fn - event filters
Added a new pattern which demonstrates DynamoDB Streams triggering Lambda fns with event based filtering.
=> Added event pattern for DynamoDB Streams - Lambda fn - event filters

lambda-pinpoint/template.yaml
Fix for removing phone numbers associated with my account in the SAM template file.
=> Lambda -> Pinpoint: Remove phone numbers from template.yaml

cdk-vpc-lambda-sfn/package.json, cdk-vpc-lambda-sfn/src/lambda_code/app.js, cdk-vpc-lambda-sfn/src/stacks/lambda_stack.ts, cdk-vpc-lambda-sfn/src/stacks/sfn_stack.ts, cdk-vpc-lambda-sfn/src/stacks/vpc_stack.ts
We have upgraded the version of this pattern example from 1.132.0 to 1.138.0.
Original  PR was  https://github.com/aws-samples/serverless-patterns/pull/281
Will be great if you merge this.
=> Bug: Version upgrade for existing pattern(Origional PR: https://github.com/aws-samples/serverless-patterns/pull/281)

cdk-codecommit-codepipeline-sfn-athena-glue/src/config.ts, cdk-codecommit-codepipeline-sfn-athena-glue/src/glue/view.sql, cdk-codecommit-codepipeline-sfn-athena-glue/src/stacks/stack_athena.ts
Updating minor code changes, where origional PR was https://github.com/aws-samples/serverless-patterns/pull/311
1. Config changes for database.
=> Bug: Minor Code Changes (Org: https://github.com/aws-samples/serverless-patterns/pull/311)

cloudwatch-rum-cognito/README.md, cloudwatch-rum-cognito/example-pattern.json, cloudwatch-rum-cognito/src/app.js, cloudwatch-rum-cognito/template.yaml
Adding new SAM pattern for CloudWatch RUM using Cognito IdentityPool
=> Adding pattern for CloudWatch RUM using Cognito IdentityPool

eventbridge-api-destinations/5-zendesk/ZendeskAPIDestination.yaml, eventbridge-api-destinations/README.md
added NoEcho flag to username and password. also added material to readme
=> Zendesk Eventbridge Destination API password fix

sqs-lambda-cdk/cdk/.gitignore, sqs-lambda-cdk/cdk/src/app.js
Added missing `app.js` in SQS-Lambda using CDK
=> Added missing app.js in SQS-Lambda using CDK

xray-lambdalayers-cdk-python/README.md, xray-lambdalayers-cdk-python/lambda_layer_x_ray_stack/lambda_layer_x_ray_stack_stack.py
updated readme so instructions worked and updated stack.py file as a line of code did not work
=> updated readme and stack.py file

apigw-rest-api-eventbridge-sam/README.md
Update the testing section with the corrected request data
The request data format in the testing section of the README.doc is updated 
FROM
```
{
"Detail":{
"message": "This is my test"
}
}
```
TO
```
"items":[
{
"Detail":"{\"data\":\"Order is created\"}",
"DetailType":"Test",
"Source":"com.inv.order"
}
]
}
```
=> Update the testing section with the corrected request data

eventbridge-api-destinations/README.md
added readme information on how to use Serverless patterns.
=> readme update for datadog and freshdesk Eventbridge API Destination

apigw-sns-sqs-lambda-cdk-dotnet/README.md
*Issue #378 
Corrected the readme "How it works" section.
=> Updated Readme How it works section

apigw-lambda-request-validator/README.md, apigw-lambda-request-validator/src/app.js, apigw-lambda-request-validator/template.yaml
https://github.com/aws-samples/serverless-patterns/issues/385
This pattern deploys an Amazon API Gateway REST API with a request validator and a default route integrated with an AWS Lambda function written in Node.js. The request validator is used to validate query string, header and request body passed on each REST API call. The lambda function returns a basic response when all validations are passed and when any validation fails API will return a response.
=> Pattern changes for APIGateway Lambda with request validator

lambda-sfn-rust/Cargo.toml, lambda-sfn-rust/Makefile, lambda-sfn-rust/README.md, lambda-sfn-rust/src/bin/handler.rs, lambda-sfn-rust/statemachine/stateMachine.asl.json, lambda-sfn-rust/template.yaml
Invoke an AWS Step Functions workflow from AWS Lambda
=> New Pattern: lambda-sfn in rust

lambda-s3-rust/Cargo.toml, lambda-s3-rust/Makefile, lambda-s3-rust/README.md, lambda-s3-rust/src/bin/handler.rs, lambda-s3-rust/template.yaml
Lambda function that writes to an S3 bucket when invoked
=> New Pattern: lambda-s3 in rust

eventbridge-lambda-rust/Cargo.toml, eventbridge-lambda-rust/Makefile, eventbridge-lambda-rust/README.md, eventbridge-lambda-rust/event.json, eventbridge-lambda-rust/src/bin/handler.rs, eventbridge-lambda-rust/template.yaml
Create an EventBridge rule that invokes a Lambda function
=> New Pattern: eventbridge-lambda-rust

lambda-eventbridge-rust/Cargo.toml, lambda-eventbridge-rust/Makefile, lambda-eventbridge-rust/README.md, lambda-eventbridge-rust/src/bin/handler.rs, lambda-eventbridge-rust/template.yaml
Create a Lambda function that sends events to EventBridge.
=> New Pattern: lambda-eventbridge-rust

lambda-dynamodb-rust/Cargo.toml, lambda-dynamodb-rust/Makefile, lambda-dynamodb-rust/README.md, lambda-dynamodb-rust/src/bin/handler.rs, lambda-dynamodb-rust/template.yaml
Persist an item to a DynamoDB table from a Lambda function
=> New Pattern: lambda-dynamodb-rust

apigw-lambda-request-validator/README.md
Fixed the serverlessland web page link in the README file to have the right web link.
=> README file fix for serverlessland pattern link

apigw-lambda-rust/Cargo.toml, apigw-lambda-rust/Makefile, apigw-lambda-rust/README.md, apigw-lambda-rust/src/bin/handler.rs, apigw-lambda-rust/template.yml
APIGW REST API to Lambda in rust
=> New Pattern: apigw-lambda-rust

apigw-http-api-lambda-cdk/app.py, apigw-http-api-lambda-cdk/cdk.json, apigw-http-api-lambda-cdk/requirements.txt
*Issue #, if available:* #412
-  updating feature flags in ```cdk.json```
- dependency updates in ```requirements.txt```
- updating imports to use the new ```constructs``` module and consolidated ```aws-cdk-lib``` package
=> migrated to AWS CDK v2 (python)

s3-lambda-dynamodb-cdk/.gitignore, s3-lambda-dynamodb-cdk/.npmignore, s3-lambda-dynamodb-cdk/README.md, s3-lambda-dynamodb-cdk/cdk/bin/s3-lambda-dynamodb-cdk.ts, s3-lambda-dynamodb-cdk/cdk/cdk.json, s3-lambda-dynamodb-cdk/cdk/code/data-load.py, s3-lambda-dynamodb-cdk/cdk/jest.config.js, s3-lambda-dynamodb-cdk/cdk/lib/s3-lambda-dynamodb-cdk-stack.ts, s3-lambda-dynamodb-cdk/cdk/package.json, s3-lambda-dynamodb-cdk/cdk/test/s3-lambda-dynamodb-cdk.test.ts, s3-lambda-dynamodb-cdk/cdk/tsconfig.json
New CDK pattern that creates a lambda function that reads CSV files from S3 bucket and loads into a DynamoDB table.
=> New pattern: s3-lambda-dynamodb CDK

lambda-cloudwatch-cdk/bin/lambda-cloudwatch-cdk.js, lambda-cloudwatch-cdk/cdk.json, lambda-cloudwatch-cdk/lib/lambda-cloudwatch-cdk-stack.js, lambda-cloudwatch-cdk/package.json, lambda-cloudwatch-cdk/test/lambda-cloudwatch-cdk.test.js
*Issue #, if available:* closes #447
* updating feature flags in cdk.json
* dependency updates in package.json
* updating imports to use the new constructs and consolidated aws-cdk-lib libraries
=> migrated to AWS CDK v2 (javascript)

.github/ISSUE_TEMPLATE/new-serverless-pattern-submission.md
*Issue #, if available:* N/A
README.me => README.md
=> Fix README spelling error in issue template

eventbridge-api-destinations/9-shopify/ShopifyAPIDestination.yaml, eventbridge-api-destinations/9-shopify/testEvent.json, eventbridge-api-destinations/README.md
Adding shopify event bridge Api destination pattern 
=> Eventbridge-apidestination-shopify-integration

cloudfront-apigw-http-api-lambda-rust/Cargo.toml, cloudfront-apigw-http-api-lambda-rust/Makefile, cloudfront-apigw-http-api-lambda-rust/README.md, cloudfront-apigw-http-api-lambda-rust/src/bin/handler.rs, cloudfront-apigw-http-api-lambda-rust/template.yml
This is a SAM template for a CloudFront distribution in front of APIGW REST API to Lambda in Rust
=> New Pattern: cloudfront-apigw-http-api-rust

dynamodb-kinesis-cdk/cdk/bin/dynamodb-kinesis-cdk.ts, dynamodb-kinesis-cdk/cdk/cdk.json, dynamodb-kinesis-cdk/cdk/lib/dynamodb-kinesis-cdk-stack.ts, dynamodb-kinesis-cdk/cdk/package.json, dynamodb-kinesis-cdk/cdk/test/dynamodb-kinesis-cdk.test.ts
*Issue #, if available:* closes #493
* updating feature flags in cdk.json
* dependency updates in package.json
* updating imports to use the new constructs and consolidated aws-cdk-lib libraries
=> migrated to AWS CDK v2 (typescript)

sqs-lambda-terraform-python/README.md, sqs-lambda-terraform-python/main.tf, sqs-lambda-terraform-python/sqs-lambda-terraform-python.json, sqs-lambda-terraform-python/src/app.py
Add a new patter for sqs triggering lambda using Terraform and a Lambda written in Python
=> New serverless pattern - sqs-lambda-terraform-python

s3-eventbridge-terraform/README.md, s3-eventbridge-terraform/main.tf
*Description of changes:* Added a new serverless pattern for s3-eventbridge using terraform
=> New serverless pattern - s3-eventbridge-terraform

.gitignore, sns-sqs-terraform/README.md, sns-sqs-terraform/main.tf, sns-sqs-terraform/sns-sqs-terraform.json
*Issue #548*
*Description of changes: Terraform stack to create a SNS topic and a SQS queue subscribed to the SNS topic*
=> New pattern : sns sqs terraform

apigw-http-api-sqs-lambda-sls/README.md, apigw-http-api-sqs-lambda-sls/api.json, apigw-http-api-sqs-lambda-sls/example-pattern.json, apigw-http-api-sqs-lambda-sls/package.json, apigw-http-api-sqs-lambda-sls/serverless.yml, apigw-http-api-sqs-lambda-sls/src/handler.ts, apigw-http-api-sqs-lambda-sls/tsconfig.json
#566 
Add support for APIGW (HTTP API) - SQS - Lambda pattern, implemented with Serverless Framework
=> APIGW SQS Lambda - Serverless Framework

apigw-lambda-sls/README.md, apigw-lambda-sls/example-pattern.json, apigw-lambda-sls/package.json, apigw-lambda-sls/serverless.yml, apigw-lambda-sls/src/handler.ts, apigw-lambda-sls/tsconfig.json
#566 
Add support for APIGW - Lambda pattern, implemented with Serverless Framework
=> APIGW Lambda - Serverless Framework

alb-lambda-rust/Cargo.toml, alb-lambda-rust/Makefile, alb-lambda-rust/README.md, alb-lambda-rust/src/bin/handler.rs, alb-lambda-rust/template.yml
This AWS SAM pattern creates an Application Load Balancer with an AWS Lambda function (rust) as a target.
=> New Pattern: Lambda functions as targets for Application Load Balancers in rust

apigw-rest-api-dynamodb-sls/README.md, apigw-rest-api-dynamodb-sls/example-pattern.json, apigw-rest-api-dynamodb-sls/serverless.yml
#566 
Add support for APIGW (REST) - DynamoDB pattern, implemented with Serverless Framework
=> APIGW (REST) DynamoDB - Serverless Framework

eventbridge-lambda-sls/README.md, eventbridge-lambda-sls/event.json, eventbridge-lambda-sls/package.json, eventbridge-lambda-sls/serverless.yml, eventbridge-lambda-sls/src/handler.ts, eventbridge-lambda-sls/tsconfig.json
#566
Add support for EventBridge - Lambda pattern, implemented with Serverless Framework
=> EventBridge Lambda - Serverless Framework

lambda-sfn-sls/.gitignore, lambda-sfn-sls/README.md, lambda-sfn-sls/package.json, lambda-sfn-sls/serverless.yml, lambda-sfn-sls/src/handler.ts, lambda-sfn-sls/statemachine/stateMachine.asl.yml, lambda-sfn-sls/tsconfig.json
#566 
Add support for Lambda - Step Function pattern, implemented with Serverless Framework
=> Lambda to Step Function - Serverless Framework

apigw-lambda-dynamodb-sam-java/README.md
=> README update

fifo-sns-sqs-lambda-firehose-s3/README.md, fifo-sns-sqs-lambda-firehose-s3/fifo-sns-sqs-lambda-firehose-s3-pattern.json, fifo-sns-sqs-lambda-firehose-s3/main.tf
- Fixing typo
- Updating tags in main.tf (remove broken link to patterns)
- Adding link to author image in json file
- Updating broken link in  README.md
=> Fixing typo, Adding author image and  and Updating README.md

lambda-eventbridge-java/PublisherFunction/pom.xml, lambda-eventbridge-java/PublisherFunction/src/main/java/com/example/App.java, lambda-eventbridge-java/README.md, lambda-eventbridge-java/example-pattern.json, lambda-eventbridge-java/input.json, lambda-eventbridge-java/template.yaml
Port of Lambda to EventBridge pattern to Java. This version takes an input event from the invoke command and passes that to EventBridge. 
=> Java port of Lambda to EventBridge

eventbridge-scheduled-lambda-java/EBLambdaFunction/pom.xml, eventbridge-scheduled-lambda-java/EBLambdaFunction/src/main/java/com/example/App.java, eventbridge-scheduled-lambda-java/README.md, eventbridge-scheduled-lambda-java/example-pattern.json, eventbridge-scheduled-lambda-java/template.yaml
This is a Java port of the pattern https://serverlessland.com/patterns/eventbridge-scheduled-lambda
Keep as close to the original as possible with standard SAM/Java build and Java event lib used for handler. 
=> Java port of Scheduled Event Bridge to Lambda Pattern

apigw-websocket-api-sqs-lambda-java/README.md, apigw-websocket-api-sqs-lambda-java/SQSWebsocketResponse/pom.xml, apigw-websocket-api-sqs-lambda-java/SQSWebsocketResponse/src/main/java/com/example/App.java, apigw-websocket-api-sqs-lambda-java/example-pattern.json, apigw-websocket-api-sqs-lambda-java/template.yaml
Java port of https://serverlessland.com/patterns/apigw-websocket-sqs-lambda
The Java version uses the AWS CRT Async Http client in this example. 
=> Java port of API Gateway WebSocket API to SQS to AWS Lambda Pattern

apigw-lambda-dynamodb-terraform/README.md, apigw-lambda-dynamodb-terraform/example-pattern.json, apigw-lambda-dynamodb-terraform/main.tf, apigw-lambda-dynamodb-terraform/outputs.tf, apigw-lambda-dynamodb-terraform/src/app.py, apigw-lambda-dynamodb-terraform/variables.tf
Created an existing pattern using terraform.
=> New serverless pattern - apigw-lambda-dynamodb-terraform

sqs-fargate-cdk-python/sqs_fargate_cdk_python/sqs_fargate_cdk_python_stack.py
Making the configuration less permissive by adding a consume message to the role.
=> Ajdusting permission

apigw-websocket-api-sqs-lambda-terraform/README.md, apigw-websocket-api-sqs-lambda-terraform/example-pattern.json, apigw-websocket-api-sqs-lambda-terraform/main.tf, apigw-websocket-api-sqs-lambda-terraform/outputs.tf, apigw-websocket-api-sqs-lambda-terraform/src/app.py, apigw-websocket-api-sqs-lambda-terraform/variables.tf
Implemented an existing pattern using Terraform and Python.
=> New serverless pattern - apigw-websocket-api-sqs-lambda-terraform

apigw-rest-api-eventbridge-terraform/README.md, apigw-rest-api-eventbridge-terraform/example-pattern.json, apigw-rest-api-eventbridge-terraform/main.tf, apigw-rest-api-eventbridge-terraform/outputs.tf, apigw-rest-api-eventbridge-terraform/variables.tf
Implementation of existing pattern using Terraform
=> New serverless pattern - apigw-rest-api-eventbridge-terraform

apigw-http-api-lambda-rds-proxy-terraform/README.md, apigw-http-api-lambda-rds-proxy-terraform/example-pattern.json, apigw-http-api-lambda-rds-proxy-terraform/main.tf, apigw-http-api-lambda-rds-proxy-terraform/outputs.tf, apigw-http-api-lambda-rds-proxy-terraform/src/app.py, apigw-http-api-lambda-rds-proxy-terraform/src/build.sh, apigw-http-api-lambda-rds-proxy-terraform/src/requirements.txt, apigw-http-api-lambda-rds-proxy-terraform/variables.tf, apigw-http-api-lambda-rds-proxy-terraform/vpc-rds-setup/README.md, apigw-http-api-lambda-rds-proxy-terraform/vpc-rds-setup/main.tf, apigw-http-api-lambda-rds-proxy-terraform/vpc-rds-setup/outputs.tf, apigw-http-api-lambda-rds-proxy-terraform/vpc-rds-setup/variables.tf
Implementation of apigw-http-api-lambda-rds-proxy pattern in terraform
=> New serverless pattern - apigw-http-api-lambda-rds-proxy-terraform

apigw-http-api-lambda-terraform/README.md, apigw-http-api-lambda-terraform/example-pattern.json, apigw-http-api-lambda-terraform/main.tf, apigw-http-api-lambda-terraform/outputs.tf, apigw-http-api-lambda-terraform/src/app.py, apigw-http-api-lambda-terraform/variables.tf
This pattern creates an Amazon API Gateway HTTP API and an AWS Lambda function.
=> New serverless pattern - apigw-http-api-lambda-terraform

dynamodb-streams-lambda-terraform-java/README.md, dynamodb-streams-lambda-terraform-java/example-pattern.json, dynamodb-streams-lambda-terraform-java/main.tf, dynamodb-streams-lambda-terraform-java/pom.xml, dynamodb-streams-lambda-terraform-java/src/main/java/com/example/App.java
Java port of the pattern using Terraform to setup a Lambda function that processes streaming events from DynamoDB table changes. 
=> Dynamodb Streams to AWS Lambda Java Port

lambda-function-url/README.md, lambda-function-url/example-pattern.json, lambda-function-url/src/app.js, lambda-function-url/template.yaml
Lambda Function URL with SAM and Node.js
=> New serverless pattern Lambda Function URL

apigw-eventbridge/README.md
=> -guided =>  --guided

lambda-sqs-java/QueuePublisherFunction/pom.xml, lambda-sqs-java/QueuePublisherFunction/src/main/java/com/example/App.java, lambda-sqs-java/README.md, lambda-sqs-java/example-pattern.json, lambda-sqs-java/template.yaml
Java port of https://serverlessland.com/patterns/lambda-sqs
=> Java port of Lambda to SQS example. 

apigw-dynamodb-terraform/main.tf
*Issue #, if available:* #620
*Description of changes:* solving issue #620 by adding explicit depends on clause.
=> Solving issue #620

apigw-resource-policy/README.md, apigw-resource-policy/example-pattern.json, apigw-resource-policy/src/app.js, apigw-resource-policy/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway REST API endpoint that uses a Resource Policy for access control.
=> New serverless pattern - apigw-resource-policy

lambda-ssm-parameter-java/LambdaFunction/pom.xml, lambda-ssm-parameter-java/LambdaFunction/src/main/java/com/example/App.java, lambda-ssm-parameter-java/README.md, lambda-ssm-parameter-java/events/getEvent.json, lambda-ssm-parameter-java/events/putEvent.json, lambda-ssm-parameter-java/example-pattern.json, lambda-ssm-parameter-java/template.yml
Java port of the /patterns/lambda-ssm example. 
=> Java port of Lambda SSM Pattern

apigw-resource-policy/README.md, apigw-resource-policy/example-pattern.json
Added 'sam delete' and instructions for parameters
=> Added 'sam delete' and instructions for parameters

lambda-function-url-cdk/README.md, lambda-function-url-cdk/example-pattern.json, lambda-function-url-cdk/src/.npmignore, lambda-function-url-cdk/src/README.md, lambda-function-url-cdk/src/bin/src.ts, lambda-function-url-cdk/src/cdk.json, lambda-function-url-cdk/src/functions/handler.js, lambda-function-url-cdk/src/jest.config.js, lambda-function-url-cdk/src/package.json, lambda-function-url-cdk/src/tsconfig.json
*Description of changes: New pattern for lambda url with cdk
=> New pattern function url for cdk

lambda-function-url-cdk/.gitignore, lambda-function-url-cdk/README.md, lambda-function-url-cdk/src/bin/src.ts, lambda-function-url-cdk/src/lib/cdk-stack.ts
=> fixing lambda url

cloudfront-lambda-url-rust/Cargo.toml, cloudfront-lambda-url-rust/Makefile, cloudfront-lambda-url-rust/README.md, cloudfront-lambda-url-rust/src/bin/handler.rs, cloudfront-lambda-url-rust/template.yml
CloudFront to Lambda Url using AWS SAM and Rust
=> New serverless pattern: CloudFront to Lambda Url using AWS SAM and Rust

sns-sqs-lambda-rust/Cargo.toml, sns-sqs-lambda-rust/Makefile, sns-sqs-lambda-rust/README.md, sns-sqs-lambda-rust/event.json, sns-sqs-lambda-rust/src/bin/handler.rs, sns-sqs-lambda-rust/template.yaml
SNS to SQS to Lambda using AWS SAM and Rust
=> New serverless pattern: SNS to SQS to Lambda using AWS SAM and Rust

apigw-rest-api-http-integration/README.md, apigw-rest-api-http-integration/example-pattern.json, apigw-rest-api-http-integration/template.yaml, apigw-rest-api-mock-integration/README.md, apigw-rest-api-mock-integration/example-pattern.json, apigw-rest-api-mock-integration/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway REST API endpoint with a Mock integration.
=>  New serverless pattern - apigw-rest-api-mock-integration

apigw-lambda-authorizer/README.md, apigw-lambda-authorizer/example-pattern.json, apigw-lambda-authorizer/src/app.js, apigw-lambda-authorizer/src/tokenauthorizer.js, apigw-lambda-authorizer/template.yaml, apigw-rest-api-http-integration/README.md, apigw-rest-api-http-integration/example-pattern.json, apigw-rest-api-http-integration/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway REST API endpoint with an HTTP integration.
=> New serverless pattern - apigw-rest-api-http-integration

lambda-comprehend/example-pattern.json
Small fix fixing the JSON file for this pattern, removed the additional comma that was in the file
=> Fixing invalid JSON - example-pattern for lambda-comprehend

apigw-rest-api-http-integration/README.md, apigw-rest-api-http-integration/example-pattern.json, apigw-rest-api-http-integration/template.yaml, apigw-rest-api-mock-integration/README.md, apigw-rest-api-mock-integration/example-pattern.json, apigw-rest-api-mock-integration/template.yaml, apigw-s3-proxy/README.md, apigw-s3-proxy/example-pattern.json, apigw-s3-proxy/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway REST API with a S3 read-only integration.
=> New serverless pattern - apigw-s3-proxy

apigw-rest-api-http-integration/README.md, apigw-rest-api-http-integration/example-pattern.json, apigw-rest-api-http-integration/template.yaml, apigw-rest-api-mock-integration/README.md, apigw-rest-api-mock-integration/example-pattern.json, apigw-rest-api-mock-integration/template.yaml, apigw-rest-api-vpclink/README.md, apigw-rest-api-vpclink/example-pattern.json, apigw-rest-api-vpclink/template.yaml, apigw-s3-proxy/README.md, apigw-s3-proxy/example-pattern.json, apigw-s3-proxy/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway REST API endpoint with a VPC Link integration.
=> New serverless pattern - apigw-rest-api-vpclink

apigw-rest-api-http-integration/README.md, apigw-rest-api-http-integration/example-pattern.json, apigw-rest-api-http-integration/template.yaml, apigw-rest-api-mock-integration/README.md, apigw-rest-api-mock-integration/example-pattern.json, apigw-rest-api-mock-integration/template.yaml, apigw-s3-proxy/README.md, apigw-s3-proxy/example-pattern.json, apigw-s3-proxy/template.yaml, cognito-user-pool/README.md, cognito-user-pool/example-pattern.json, cognito-user-pool/template.yaml
Submission of a new serverless pattern that deploys an Amazon Cognito User Pool with its associated User, App Client, Domain and Resource Server.
=> New serverless pattern - cognito-user-pool

apigw-custom-domain-regional/README.md, apigw-custom-domain-regional/example-pattern.json, apigw-custom-domain-regional/template.yaml, apigw-rest-api-http-integration/README.md, apigw-rest-api-http-integration/example-pattern.json, apigw-rest-api-http-integration/template.yaml, apigw-rest-api-mock-integration/README.md, apigw-rest-api-mock-integration/example-pattern.json, apigw-rest-api-mock-integration/template.yaml, apigw-s3-proxy/README.md, apigw-s3-proxy/example-pattern.json, apigw-s3-proxy/template.yaml, cognito-user-pool/README.md, cognito-user-pool/example-pattern.json, cognito-user-pool/template.yaml
Submission of a new serverless pattern that deploys a Regional Custom Domain Name in API Gateway.
=>  New serverless pattern - apigw-custom-domain-regional

apigw-api-key/README.md, apigw-api-key/example-pattern.json, apigw-api-key/src/app.js, apigw-api-key/src/tokenauthorizer.js, apigw-api-key/template.yaml, apigw-client-certificate/README.md, apigw-client-certificate/example-pattern.json, apigw-client-certificate/src/app.js, apigw-client-certificate/template.yaml, apigw-custom-domain-edge/README.md, apigw-custom-domain-edge/example-pattern.json, apigw-custom-domain-edge/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway REST API endpoint with a client certificate associated to the stage 'Prod'.
=> New serverless pattern - apigw-client-certificate

apigw-custom-domain-edge/README.md, apigw-custom-domain-edge/example-pattern.json, apigw-custom-domain-edge/template.yaml
Submission of a new serverless pattern that deploys an Amazon API Gateway Edge Custom Domain.
=> New serverless pattern - apigw-custom-domain-edge

cloudfront-le-apigw-cdk/lib/cloudfront-le-apigw-cdk-stack.ts
=> add missing file 

lambda-glue-s3/README.md, lambda-glue-s3/app.py, lambda-glue-s3/assets/file.csv, lambda-glue-s3/assets/script.py, lambda-glue-s3/cdk.json, lambda-glue-s3/example-pattern.json, lambda-glue-s3/functions/glue.py, lambda-glue-s3/requirements.txt
=> New serverless pattern - lambda-glue-s3

lambda-powershell-runtime-sam/README.md, lambda-powershell-runtime-sam/example-pattern.json, lambda-powershell-runtime-sam/function/Makefile, lambda-powershell-runtime-sam/function/examplehandler.ps1, lambda-powershell-runtime-sam/function/examplemodule/examplemodule.psd1, lambda-powershell-runtime-sam/function/examplemodule/examplemodule.psm1, lambda-powershell-runtime-sam/function/examplescript.ps1, lambda-powershell-runtime-sam/invoke-result, lambda-powershell-runtime-sam/powershell-runtime/Makefile, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/PowerShellLambdaContext.cs, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/bootstrap, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Get-Handler.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Get-LambdaNextInvocation.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Invoke-FunctionHandler.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Send-FunctionHandlerError.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Send-FunctionHandlerResponse.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Set-HandlerEnvironmentVariables.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Set-LambdaContext.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/Private/Set-PSModulePath.ps1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/pwsh-runtime.psd1, lambda-powershell-runtime-sam/powershell-runtime/pwsh-runtime/modules/pwsh-runtime.psm1, lambda-powershell-runtime-sam/template.yml
*Adding: lambda-powershell-runtime-sam*
=> lambda-powershell-runtime-sam

lambda-glue-s3/README.md
*Description of changes:*  This is an existing pattern in repo , just updated the README.md with correct formatting
AUTHOR images arent displayed on serverless pattern even thought the phonetool link is provided in example-pattern.json. Kindly reach out if any furthur steps is required or it takes time to be made visble.
https://serverlessland.com/patterns/lambda-glue-s3
=> Existing serverless pattern - lambda-glue-s3

eventbridge-api-destinations/4-mongodb/mongoDB.yaml
Added security by using no echo and secret values
=> mongodb no echo update

apigw-websocket-api-sfn-sync/README.md, apigw-websocket-api-sfn-sync/example-pattern.json, apigw-websocket-api-sfn-sync/template.yaml
Adding pattern that uses Amazon API Gateway WebSocket API and AWS Service integration type with AWS Step Functions workflow as a business logics implementation.
=> New serverless pattern - apigw-websocket-api-sfn-sync

apigw-websocket-api-sfn-async/README.md, apigw-websocket-api-sfn-async/example-pattern.json, apigw-websocket-api-sfn-async/template.yaml
Adding pattern that uses Amazon API Gateway WebSocket API and AWS Service integration type with AWS Step Functions workflow as a business logics implementation.
=> New serverless pattern - apigw-websocket-api-sfn-async

iot-kinesis-lambda-cdk/.gitignore, iot-kinesis-lambda-cdk/README.md, iot-kinesis-lambda-cdk/app.py, iot-kinesis-lambda-cdk/cdk.json, iot-kinesis-lambda-cdk/iot-kinesis-lambda-cdk-pattern.json, iot-kinesis-lambda-cdk/iot_kinesis_lambda_cdk/iot_kinesis_lambda_cdk_stack.py, iot-kinesis-lambda-cdk/requirements.txt, iot-kinesis-lambda-cdk/src/lambda_function.py
https://github.com/aws-samples/serverless-patterns/issues/720
new pattern iot -> kinesis Data Stream -> lambda with CDK in Python
=> new pattern iot-kinesis-lambda-cdk

iot-s3-lambda-cdk/.gitignore, iot-s3-lambda-cdk/README.md, iot-s3-lambda-cdk/app.py, iot-s3-lambda-cdk/cdk.json, iot-s3-lambda-cdk/iot-s3-lamdba-cdk-pattern.json, iot-s3-lambda-cdk/iot_s3_lambda_cdk/iot_s3_lambda_cdk_stack.py, iot-s3-lambda-cdk/requirements.txt, iot-s3-lambda-cdk/src/lambda_function.py
https://github.com/aws-samples/serverless-patterns/issues/718
New pattern IoT Rule -> S3 -> Lambda with CDK in Python
=> new pattern iot-s3-lambda-cdk

cdk-sfn-s3/README.md
Its an existing pattern thats already accepted - updated the readMe with correct link.
=> Existing serverless pattern- Readme updated with proper link

s3-eventbridge-sfn/README.md, s3-eventbridge-sfn/example-pattern.json, s3-eventbridge-sfn/statemachine/statemachine.asl.json, s3-eventbridge-sfn/template.yaml
New SAM pattern for triggering a Step Functions workflow if an object is uploaded to an Amazon S3 bucket via an Amazon EventBridge rule.
=> Adding s3-eventbridge-sfn SAM pattern

lambda-kinesis-lambda/README.md, lambda-kinesis-lambda/consumer/consumer-function.py, lambda-kinesis-lambda/example-pattern.json, lambda-kinesis-lambda/producer/producer-function.py, lambda-kinesis-lambda/template.yaml
Adding a use case where Kinesis Data Stream can have serverless producers and consumers. The folder lambda-kinesis-lambda contains the tests.
=> Lambda-Kinesis Data Stream-Lambda

.gitignore, lambda-function-url-sls/README.md, lambda-function-url-sls/example-pattern.json, lambda-function-url-sls/package.json, lambda-function-url-sls/serverless.yml, lambda-function-url-sls/src/lambda.ts, lambda-function-url-sls/test/deleteHello.json, lambda-function-url-sls/test/getHello.json, lambda-function-url-sls/test/postHello.json, lambda-function-url-sls/tsconfig.json
New pattern for Lambda URL endpoint using serverless framework
=> new pattern lambda-function-url-sls

eventbridge-lambda-terraform/example-pattern.json, eventbridge-lambda-terraform/main.tf, eventbridge-scheduled-lambda-terraform/example-pattern.json, eventbridge-scheduled-lambda-terraform/main.tf, lambda-eventbridge-terraform/example-pattern.json, lambda-eventbridge-terraform/main.tf, lambda-sns-terraform/example-pattern.json, lambda-sns-terraform/main.tf, lambda-sqs-terraform/example-pattern.json, lambda-sqs-terraform/main.tf, lambda-ssm-parameter-terraform/example-pattern.json, lambda-ssm-parameter-terraform/main.tf
The way these modules handled IAM roles/policies created issues when apply was run a second time.  Also adding example-pattern.json files to them
=> Fixing some Terraform module role configurations

apigw-lambda-qldb-terraform/README.md, apigw-lambda-qldb-terraform/example-pattern.json, apigw-lambda-qldb-terraform/main.tf, apigw-lambda-qldb-terraform/src/create-person.js, apigw-lambda-qldb-terraform/src/delete-person.js, apigw-lambda-qldb-terraform/src/get-person-history.js, apigw-lambda-qldb-terraform/src/get-person.js, apigw-lambda-qldb-terraform/src/package.json, apigw-lambda-qldb-terraform/src/update-person.js
Adding a module for apigw-lambda-qldb-terraform
=> New Pattern: apigw-lambda-qldb-terraform

apigw-lambda-memorydb/template.yaml
Fixing sam template failure due to missing security group egress
=> fix: apigw-lambda-memorydb

sfn-lambda-lambda/README.md, sfn-lambda-lambda/example-pattern.json, sfn-lambda-lambda/firstfunction/first-function.js, sfn-lambda-lambda/secondfunction/second-function.js, sfn-lambda-lambda/statemachine/StateMachine.asl.json, sfn-lambda-lambda/template.yaml
This create a Step Functions Standard Workflow that orchestrates two Lambda functions executions.
=> [New Pattern] sfn-lambda-lambda

lambda-function-url-sls/example-pattern.json, lambda-vpc-secrets-sls/example-pattern.json
Removing the Node.js from language in example-pattern.json to match other patterns.
=> remove node.js to match other patterns

elemental-medialive-mediapackage-cdk-ts/lib/media_package_cdn_auth.ts, elemental-medialive-mediapackage-cdk-ts/lib/secrets.ts, elemental-mediapackage-cloudfront-cdk-ts/lib/streaming_stack.ts
=> updating missing files for elemental-medialive-mediapackage-cdk-ts

lambda-eventbridge-sns-sam/README.md, lambda-eventbridge-sns-sam/example-pattern.json, lambda-eventbridge-sns-sam/src/app.py, lambda-eventbridge-sns-sam/template.yaml
*Description of changes:* First commit of new pattern
=> New serverless pattern - lambda-eventbridge-sns-sam-serverless

public-alb-private-api-terraform/README.md, step-functions-athena-glue-sam/README.md, step-functions-athena-glue-sam/example-pattern.json
Updated README file to add more information on the implementation of the solution.
=> Updated README files for patterns - public-alb-private-api-terraform and step-functions-athena-glue-sam

apigw-sns-sms/README.md, apigw-sns-sms/api.yaml, apigw-sns-sms/example-pattern.json, apigw-sns-sms/template.yaml
*Description of changes:* API Gateway integration with SNS SMS to send transactional SMS messages.
=> New serverless pattern - apigw-sns-sms

apigw-lambda-sns/Readme.md, apigw-lambda-sns/api.yaml, apigw-lambda-sns/example-pattern.json, apigw-lambda-sns/src/code.py, apigw-lambda-sns/template.yaml
*Description of changes: Publishing to a SNS Topic using API Gateway REST API with integration of Lambda function.
=> Ssnskar feature apigw lambda sns

apigw-custom-resource-policy/README.md, apigw-custom-resource-policy/example-pattern.json, apigw-custom-resource-policy/src/app.py, apigw-custom-resource-policy/template.yaml
Creates a pattern with an API Gateway REST API and a custom resource policy limiting access to a date range.
=> Added apigw custom resource example

iot-timestream-cdk/iot-timestream/.gitignore, iot-timestream-cdk/iot-timestream/lib/iot-timestream-stack.ts, iot-timestream-cdk/iot-timestream/lib/timestream.ts
The original PR 793 was missing the lib folder - creating a fix PR to merge the lib folder that has the CDK stack files.
#793
=> Fix to include the lib folder for the pattern iot-timestream-cdk (pr 793)

public-nlb-or-alb-private-api-cfn/example-pattern.json
*Description of changes: made a very minor change in example-pattern file. 
=> corrected examples-pattern file

lambda-glue-s3/app.py, lambda-glue-s3/assets/script.py
*Description of changes:* refactored code and updated variables
=> Updated existing pattern : lambda-glue-s3

eventbridge-webhooks/1-stripe/example-pattern.json, eventbridge-webhooks/1-stripe/template.yml, eventbridge-webhooks/README.md
Create folder for EventBridge Webhooks. Starting with Stripe SAM template with more to follow.
=> New serverless pattern - EventBridge Webhooks

msk-lambda/template.yaml
Fixed the typo to point to correct source folder  for the lambda
=> Update template.yaml for incorrect source folder 

eventbridge-scheduled-lambda-cdk-typescript/lib/eventbridge-scheduled-lambda-cdk-stack.ts
*Issue #, if available:* no issue just a tiny typo
fix typo in console.log example
=> fix typo in console.log example

eventbridge-webhooks/3-twilio/example-pattern.json, eventbridge-webhooks/3-twilio/template.yaml, eventbridge-webhooks/README.md
=> Twilio EventBridge Webhook

apigw-data-validation/src/app.py
=> Spelling correction

lambda-web-adapter-cdk/README.md, lambda-web-adapter-cdk/cdk/.gitignore, lambda-web-adapter-cdk/cdk/.npmignore, lambda-web-adapter-cdk/cdk/README.md, lambda-web-adapter-cdk/cdk/app/app.js, lambda-web-adapter-cdk/cdk/app/package.json, lambda-web-adapter-cdk/cdk/app/run.sh, lambda-web-adapter-cdk/cdk/bin/cdk.ts, lambda-web-adapter-cdk/cdk/cdk.json, lambda-web-adapter-cdk/cdk/jest.config.js, lambda-web-adapter-cdk/cdk/package.json, lambda-web-adapter-cdk/cdk/stack/lambda-web-adapter-stack.ts, lambda-web-adapter-cdk/cdk/test/cdk.test.ts, lambda-web-adapter-cdk/cdk/tsconfig.json, lambda-web-adapter-cdk/example-pattern.json
=> Adding pattern lambda-web-adapter-cdk

apigw-lambda-dynamodb/src/index.py
*Issue #, if available:* 817
*Description of changes:* Moved the DDBClient definition above the handler
=> Moved DDBClient above handler

appconfig-feature-flag-cdk/.gitignore, appconfig-feature-flag-cdk/.npmignore, appconfig-feature-flag-cdk/README.md, appconfig-feature-flag-cdk/bin/app-config-feature-flag-cdk.ts, appconfig-feature-flag-cdk/cdk.json, appconfig-feature-flag-cdk/example-pattern.json, appconfig-feature-flag-cdk/lambda/index.ts, appconfig-feature-flag-cdk/lambda/package.json, appconfig-feature-flag-cdk/lib/app-config-feature-flag-cdk-stack.ts, appconfig-feature-flag-cdk/package.json, appconfig-feature-flag-cdk/tsconfig.json
Added example for AppConfig Feature Flag with CDK and how to use AppConfig extension for Lambda to check the feature flag status.
=> New serverless pattern - AppConfig feature flag with cdk

.github/workflows/validate-pattern.yml, cdk-sfn-s3/example-pattern.json, scripts/package.json, scripts/pattern-schema.json, scripts/validate.js
GitHub action that will automatically validate the `example-pattern.json` files for any new PR that is made. It uses json-schema to verify the file.
More features can/will be added in the future as we go.
=> Adding new GitHub action to validate the example-pattern.json file in pull requests.

iot-dynamodbv2-ttl-cdk/README.md
Updated the README file to provide correct folder and file names for iot-dynamodbv2-ttl-cdk
=> Update readme for correct folder-file names 

lambda-destinations-cdk/README.md, lambda-destinations-cdk/cdk/.gitignore, lambda-destinations-cdk/cdk/.npmignore, lambda-destinations-cdk/cdk/README.md, lambda-destinations-cdk/cdk/bin/cdk.ts, lambda-destinations-cdk/cdk/cdk.json, lambda-destinations-cdk/cdk/functions/reciever.js, lambda-destinations-cdk/cdk/functions/senderDestination.js, lambda-destinations-cdk/cdk/jest.config.js, lambda-destinations-cdk/cdk/lib/async-functions.ts, lambda-destinations-cdk/cdk/package.json, lambda-destinations-cdk/cdk/test/cdk.test.ts, lambda-destinations-cdk/cdk/tsconfig.json, lambda-destinations-cdk/example-pattern.json
=> Adding pattern lambda destinations cdk

alb-lambda-cdk/.gitignore, alb-lambda-cdk/.npmignore, alb-lambda-cdk/README.md, alb-lambda-cdk/bin/alb-lambda-cdk.ts, alb-lambda-cdk/cdk.json, alb-lambda-cdk/example-pattern.json, alb-lambda-cdk/lambda/index.ts, alb-lambda-cdk/lambda/package.json, alb-lambda-cdk/lib/alb-lambda-cdk-stack.ts, alb-lambda-cdk/package.json, alb-lambda-cdk/tsconfig.json
N/A
Example added for Application Load Balancer, Lambda target with CDK.
=> New serverless pattern - ALB - Lambda target - CDK

s3-lambda-rekognition-cdk/.gitignore, s3-lambda-rekognition-cdk/.npmignore, s3-lambda-rekognition-cdk/README.md, s3-lambda-rekognition-cdk/bin/s3-lambda-rekognition-cdk.ts, s3-lambda-rekognition-cdk/cdk.json, s3-lambda-rekognition-cdk/example-pattern.json, s3-lambda-rekognition-cdk/jest.config.js, s3-lambda-rekognition-cdk/lambda/IndexFace/index.ts, s3-lambda-rekognition-cdk/lambda/IndexFace/package.json, s3-lambda-rekognition-cdk/lib/s3-lambda-rekognition-cdk-stack.ts, s3-lambda-rekognition-cdk/package.json, s3-lambda-rekognition-cdk/tsconfig.json
N/A
Example added for face index with Amazon Rekognition. Image upload to S3 will trigger a Lambda function to index the face in Rekognition faces collection.
=> New serverless pattern - Face index with Amazon Rekognition - CDK

s3-s3-replication-cdk/.gitignore, s3-s3-replication-cdk/.npmignore, s3-s3-replication-cdk/README.md, s3-s3-replication-cdk/bin/s3-s3-replication-cdk.ts, s3-s3-replication-cdk/cdk.json, s3-s3-replication-cdk/example-pattern.json, s3-s3-replication-cdk/lib/s3-s3-replication-cdk-stack.ts, s3-s3-replication-cdk/package.json, s3-s3-replication-cdk/remove_objects.sh, s3-s3-replication-cdk/tsconfig.json
N/A
Example added for S3 object replication to different buckets based on prefixes. Implemented with CDK.
=> New Serverless pattern - S3 to S3 replication

cdk-eventbridge-appsync/README.md
=> Fixed some typos

sfn-to-sfn-cdk/.gitignore, sfn-to-sfn-cdk/.npmignore, sfn-to-sfn-cdk/README.md, sfn-to-sfn-cdk/bin/sfn-to-sfn-cdk.ts, sfn-to-sfn-cdk/cdk.json, sfn-to-sfn-cdk/example-pattern.json, sfn-to-sfn-cdk/lib/sfn-to-sfn-cdk-stack.ts, sfn-to-sfn-cdk/package.json, sfn-to-sfn-cdk/tsconfig.json
N/A
Example added for starting a Step Function execution as a step in another Step Function with CDK.
=> New serverless pattern - Step function to Step function with CDK

cloudwatch-logs-subscription-firehose-cdk/.gitignore, cloudwatch-logs-subscription-firehose-cdk/.npmignore, cloudwatch-logs-subscription-firehose-cdk/README.md, cloudwatch-logs-subscription-firehose-cdk/bin/cloudwatch-logs-subscription-firehose-cdk.ts, cloudwatch-logs-subscription-firehose-cdk/cdk.json, cloudwatch-logs-subscription-firehose-cdk/example-pattern.json, cloudwatch-logs-subscription-firehose-cdk/example_logs.log, cloudwatch-logs-subscription-firehose-cdk/lib/cloudwatch-logs-subscription-firehose-cdk-stack.ts, cloudwatch-logs-subscription-firehose-cdk/package.json, cloudwatch-logs-subscription-firehose-cdk/tsconfig.json
N/A
Example added for CloudWatch Logs subscription for Kinesis Firehose to S3 with CDK.
=> New Serverless pattern - CloudWatch Logs subscription for Kinesis Firehose - CDK

lambda-secrets-manager-extension-python/README.md, lambda-secrets-manager-extension-python/example-pattern.json, lambda-secrets-manager-extension-python/hello_world/app.py, lambda-secrets-manager-extension-python/hello_world/requirements.txt, lambda-secrets-manager-extension-python/template.yaml
The new AWS Secrets Manager Lambda Extension is now generally available. This pattern demonstrates an example written in Python of its usage.
=> Adding Secrets Manager Lambda Extension pattern

dynamodb-seed-data-on-create-cdk/.gitignore, dynamodb-seed-data-on-create-cdk/.npmignore, dynamodb-seed-data-on-create-cdk/README.md, dynamodb-seed-data-on-create-cdk/bin/dynamodb-seed-data-on-create-cdk.ts, dynamodb-seed-data-on-create-cdk/cdk.json, dynamodb-seed-data-on-create-cdk/example-pattern.json, dynamodb-seed-data-on-create-cdk/lib/dynamodb-seed-data-on-create-cdk-stack.ts, dynamodb-seed-data-on-create-cdk/package.json, dynamodb-seed-data-on-create-cdk/tsconfig.json
N/A
DynamoDB data seed on create with custom resource added. Implemented with CDK TypeScript.
=> New Serverless pattern - DynamoDB data seed on create with custom resource

cdk-cognito-apigateway-lambda/.gitignore, cdk-cognito-apigateway-lambda/.npmignore, cdk-cognito-apigateway-lambda/README.md, cdk-cognito-apigateway-lambda/bin/cdk-cognito-apigateway-lambda.ts, cdk-cognito-apigateway-lambda/cdk.json, cdk-cognito-apigateway-lambda/example-pattern.json, cdk-cognito-apigateway-lambda/jest.config.js, cdk-cognito-apigateway-lambda/lambda/user.js, cdk-cognito-apigateway-lambda/package.json, cdk-cognito-apigateway-lambda/tsconfig.json
- cdk project for cognito authenticated api
CDK TypeScript project for APG pattern [service to service call using Cognito client credentials flow](https://apg-library.amazonaws.com/content-viewer/author/8567548d-91a4-409f-a3cd-25560b0a07c7)
=> CDK project to authenticate API using Cognito client credentials flow

apigw-lambda-dynamodb-sam-java/src/main/java/com/example/utils/DDBUtils.java
https://github.com/aws-samples/serverless-patterns/issues/877
Added the missing import
=> import fix

cdk-cognito-apigateway-lambda/.gitignore, cdk-cognito-apigateway-lambda/lib/cdk-cognito-apigateway-lambda-stack.ts
- Update gitignore to include lib folder
Include lib folder
=> Fix to include lib folder for cdk-cognito-apigateway-lambda

lambda-efs-cdk/README.md
=> Corrected folder name

cdk-eventbridge-stepfunction-sqs/README.md, cdk-eventbridge-stepfunction-sqs/example-pattern.json
=> cdk-eventbridge-stepfunction-sqs package - Updates to example-pattern.json text

sns-firehose/README.md, sns-firehose/example-pattern.json, sns-firehose/template.yaml
*Issue #, if available:* #921
Adds a new SAM serverless pattern that subscribes a Firehose delivery stream to an SNS topic.
=> sns-firehose-SAM

kinesis-video-rekognition-lambda/README.md, kinesis-video-rekognition-lambda/example-pattern.json, kinesis-video-rekognition-lambda/src/.gitignore, kinesis-video-rekognition-lambda/src/.npmignore, kinesis-video-rekognition-lambda/src/README.md, kinesis-video-rekognition-lambda/src/bin/src.ts, kinesis-video-rekognition-lambda/src/cdk.json, kinesis-video-rekognition-lambda/src/jest.config.js, kinesis-video-rekognition-lambda/src/lib/kvs-rekognition-stack.ts, kinesis-video-rekognition-lambda/src/lib/lambda/index.py, kinesis-video-rekognition-lambda/src/package.json, kinesis-video-rekognition-lambda/src/test/src.test.ts, kinesis-video-rekognition-lambda/src/tsconfig.json
*Issue #, if available:* #900 
*Description of changes:* Added new folder kinesis-video-rekognition-lambda which describes an example pattern for connecting KVS to Rekognition to Lambda for serverless video processing and generated metadata analysis.
=> New Serverless Pattern Connected Home Label Detection + Actions with KVS, Rekognition, Lambda ft. CDK

.gitignore, apigw-lambda-snapstart/README.md, apigw-lambda-snapstart/UnicornFunction/pom.xml, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/StoreApplication.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/StreamLambdaHandler.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/UnicornPrimingResource.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/controller/UnicornController.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/data/DynamoDBUnicornRepository.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/data/UnicornMapper.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/data/UnicornRepository.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/exceptions/ResourceNotFoundException.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/model/Unicorn.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/service/UnicornService.java, apigw-lambda-snapstart/UnicornFunction/src/main/resources/application.properties, apigw-lambda-snapstart/example-pattern.json, apigw-lambda-snapstart/template.yaml
API GW -> Lambda -> DynamoDB with SnapStart
=> Lambda SnapStart pattern

apigw-eventbridge/README.md
*Issue #, if available:* n/a
*Description of changes:* Fix a few typos in README of apigw-eventbridge
=> Fix typos in README of apigw-eventbridge

apigw-lambda-snapstart/README.md
I've updated the readme.md to include testing instructions.
=> Update apigw-lambda-snapstart pattern to include testing

lambda-sns-sls/README.md, lambda-sns-sls/serverless.yml
*Issue #, if available:* N/A
When browsing examples on Serverless Patterns website, I've noticed that some of them could be slightly simplified or improved. This PR includes changes for `lambda-sns-sls` pattern such as:
1. Removed unnecessary requirement of `serverless-python-requirements` from docs. There are no dependencies for bundling and the example doesn't use that plugin at all.
2. Upgrade runtime to `python3.9`
3. Remove unnecessary `custom.topicArn` from `serverless.yml`, which might be confusing to people reading the example as it is not used anywhere and is not needed in general.
4. Removed change of default region to `us-east-2`. Unless there's a big reason to change the default, I would recommend just removing it as it allows to focus better on the …
=> Improvements to `lambda-sns-sls` pattern

eventbridge-pipes-dynamodbstream-sns/example-pattern.json
*Issue #, if available:* n/a
*Description of changes:* Fixing cleanup typo in example-pattern.json
=> Fixing cleanup typo in example-pattern.json

apigw-lambda-dynamodb-cdk/example-pattern.json, apigw-lambda-s3-cdk-dotnet/example-pattern.json, apigw-sfn-cdk/example-pattern.json, cdk-sns-sqs-lambda-dynamodb-dotnet/example-pattern.json, cloudfront-cff-s3-staticsite-dotnet/example-pattern.json, cloudfront-waf-s3-cdk/example-pattern.json, eventbridge-firehose-s3-cdk/example-pattern.json
#950 
Standardising all .NET examples to use '.NET' as the language.
=> #950: Standardise .NET naming

eventbridge-pipes-sqs-to-eventbridge-cdk-python/.gitignore, eventbridge-pipes-sqs-to-eventbridge-cdk-python/README.md, eventbridge-pipes-sqs-to-eventbridge-cdk-python/app.py, eventbridge-pipes-sqs-to-eventbridge-cdk-python/cdk.json, eventbridge-pipes-sqs-to-eventbridge-cdk-python/commands.sh, eventbridge-pipes-sqs-to-eventbridge-cdk-python/eventbridge_pipes_sqs_to_eventbridge_cdk_python/eventbridge_pipes_sqs_to_eventbridge_cdk_python_stack.py, eventbridge-pipes-sqs-to-eventbridge-cdk-python/example-pattern.json, eventbridge-pipes-sqs-to-eventbridge-cdk-python/requirements.txt, eventbridge-pipes-sqs-to-eventbridge-cdk-python/source.bat
Issue #, if available:
N/A
Example added for SQS to EventBridge Bus using EventBridge Pipes with CDK Python.
=> New Serverless pattern - SQS to EventBridge Bus using EventBridge Pipes - CDK Python 

eventbridge-schedule-to-step-function-cdk-python/.gitignore, eventbridge-schedule-to-step-function-cdk-python/README.md, eventbridge-schedule-to-step-function-cdk-python/app.py, eventbridge-schedule-to-step-function-cdk-python/cdk.json, eventbridge-schedule-to-step-function-cdk-python/eventbridge_schedule_to_step_function_cdk_python/eventbridge_schedule_to_step_function_cdk_python_stack.py, eventbridge-schedule-to-step-function-cdk-python/example_pattern.json, eventbridge-schedule-to-step-function-cdk-python/requirements.txt, eventbridge-schedule-to-step-function-cdk-python/source.bat
N/A
Example added for EventBridge Schedule to Step Function using EB Pipes with CDK Python.
=> New Serverless pattern -  EB scheduler to Step Function - CDK Python

eventbridge-schedule-to-eventbridge-cdk-python/.gitignore, eventbridge-schedule-to-eventbridge-cdk-python/README.md, eventbridge-schedule-to-eventbridge-cdk-python/app.py, eventbridge-schedule-to-eventbridge-cdk-python/cdk.json, eventbridge-schedule-to-eventbridge-cdk-python/eventbridge_schedule_to_eventbridge_cdk_python/eventbridge_schedule_to_eventbridge_cdk_python_stack.py, eventbridge-schedule-to-eventbridge-cdk-python/example-pattern.json, eventbridge-schedule-to-eventbridge-cdk-python/lambda/index.py, eventbridge-schedule-to-eventbridge-cdk-python/requirements.txt, eventbridge-schedule-to-eventbridge-cdk-python/source.bat
Example added for EB Scheduler to EventBridge to Lambda with CDK Python.
=> New Serverless pattern - EB Scheduler to EventBridge to Lambda - CDK Python

eventbridge-pipes-sqs-enrich-with-sfdc/README.md, eventbridge-pipes-sqs-enrich-with-sfdc/event.json, eventbridge-pipes-sqs-enrich-with-sfdc/example-pattern.json, eventbridge-pipes-sqs-enrich-with-sfdc/template.yaml
New pattern for enriching Pipes with SFDC data
=> Initial commit for EventBridge Pipes Salesforce Enrichment

cognito-restapi-vpclink-cdk/cdk/lib/cdk-cognito-fargate-stack.js
=> Use amazon/amazon-ecs-sample for sample container

eventbridge-pipes-sqs-to-multiple-sqs/.gitignore, eventbridge-pipes-sqs-to-multiple-sqs/README.md, eventbridge-pipes-sqs-to-multiple-sqs/app.py, eventbridge-pipes-sqs-to-multiple-sqs/cdk.json, eventbridge-pipes-sqs-to-multiple-sqs/eventbridge_pipes_sqs_to_multiple_sqs/eventbridge_pipes_sqs_to_multiple_sqs_stack.py, eventbridge-pipes-sqs-to-multiple-sqs/example-pattern.json, eventbridge-pipes-sqs-to-multiple-sqs/lambda/index.py, eventbridge-pipes-sqs-to-multiple-sqs/requirements.txt, eventbridge-pipes-sqs-to-multiple-sqs/source.bat
N/A
Example added for splitting SQS messages in to multiple SQS queues with original payload based on message contents using EventBridge Pipe. Implemented with CDK Python.
=> New Serverless pattern - SQS queue to multiple SQS queues using EB Pipes -  CDK Python

appsync-cognito-lambda-cdk/package.json, appsync-direct-lambda-resolver/cdk/lib/main.ts, appsync-direct-lambda-resolver/cdk/package.json, appsync-direct-lambda-resolver/pattern-cdk-appsync-lambda.json
Updated to remove `alpha` construct of the CDK. Deps also updated.
=> Update: appsync direct lambda resolver

eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/.gitignore, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/README.md, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/app.py, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/cdk.json, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/eventbridge_pipes_dynamodbstream_to_sqs_cdk_python/eventbridge_pipes_dynamodbstream_to_sqs_cdk_python_stack.py, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/example-pattern.json, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/requirements.txt, eventbridge-pipes-dynamodbstream-to-sqs-cdk-python/source.bat
N/A
Example added for DynamoDB streams to SQS using EventBridge Pipe with filter enabled. Implemented with CDK Python.
=> New Serverless pattern - DynamoDB stream to SQS using EB Pipes - CDK/Python

content-filter-pattern-kinesis-cdk/README.md, content-filter-pattern-kinesis-cdk/example-pattern.json, content-filter-pattern-kinesis-cdk/src/.gitignore
*Description of changes:* fixed templateFile, typo and gitignore exclusion for lambda directory
=> fixed templateFile, typo and gitignore exclusion for lambda directory

message-translator-pattern-cdk/README.md, message-translator-pattern-cdk/example-pattern.json, message-translator-pattern-cdk/src/.gitignore, message-translator-pattern-cdk/src/.npmignore, message-translator-pattern-cdk/src/README.md, message-translator-pattern-cdk/src/bin/src.ts, message-translator-pattern-cdk/src/cdk.json, message-translator-pattern-cdk/src/jest.config.js, message-translator-pattern-cdk/src/lib/lambda/messageTranslatorEnrichmentLambda.js, message-translator-pattern-cdk/src/lib/lambda/messageTranslatorSampleDataCreator.js, message-translator-pattern-cdk/src/lib/message-translator-stack.ts, message-translator-pattern-cdk/src/package.json, message-translator-pattern-cdk/src/test/src.test.ts, message-translator-pattern-cdk/src/tsconfig.json
*Description of changes:* Added message translator pattern
=> Dominik richter feature message translator

claim-check-pattern-cdk/README.md, claim-check-pattern-cdk/example-pattern.json, claim-check-pattern-cdk/src/.gitignore, claim-check-pattern-cdk/src/.npmignore, claim-check-pattern-cdk/src/README.md, claim-check-pattern-cdk/src/bin/src.ts, claim-check-pattern-cdk/src/cdk.json, claim-check-pattern-cdk/src/jest.config.js, claim-check-pattern-cdk/src/lib/claim-check-stack.ts, claim-check-pattern-cdk/src/lib/lambda/claimCheckRetrieval.js, claim-check-pattern-cdk/src/lib/lambda/claimCheckSampleDataCreator.js, claim-check-pattern-cdk/src/lib/lambda/claimCheckSplit.js, claim-check-pattern-cdk/src/package.json, claim-check-pattern-cdk/src/test/src.test.ts, claim-check-pattern-cdk/src/tsconfig.json
*Description of changes:* Added claim check pattern
=> added claim check pattern

apigw-lambda-snapstart/UnicornFunction/pom.xml
Also update other dependencies to mitigate CVEs
=> Application dependency upgrade - CRT is now GA, so I've updated the version

stepfunctions-ecs-sam/README.md, stepfunctions-ecs-sam/example-pattern.json, stepfunctions-ecs-sam/template.yml
Previous merge's checks failed due to a broad resource assignment to PassRole policy. Fixed it to be specific and tested the stepfunction post fix.
=> Fixed the PassRole policy to not include *

lambda-esm-sqs-filters-sam/.gitignore, lambda-esm-sqs-filters-sam/README.md, lambda-esm-sqs-filters-sam/events/testMessage.json, lambda-esm-sqs-filters-sam/example-pattern.json, lambda-esm-sqs-filters-sam/functions/esm-sqs-filter-function-generic/app.py, lambda-esm-sqs-filters-sam/pattern.json, lambda-esm-sqs-filters-sam/template.yaml
*Template Event Source Mapping filters for Lambda triggered by an SQS message*
=> New serverless pattern - lambda-esm-sqs-filters-sam

apigw-lambda-ses/README.md, apigw-lambda-ses/email-lambda/email-lambda.py, apigw-lambda-ses/email-lambda/requirements.txt, apigw-lambda-ses/template.yaml
=> Adding apigw-lambda-ses serverless pattern

scripts/pattern-schema.json
Fixes: #1079 
Added Pulumi as an framework option in the schema validation
=> Added Pulumi as framework option in schema validation

sfn-ecs-sam/README.md
Fixed readme reference to new folder name after amendment during merge to main.
=> Fixed readme reference to new folder name after merge amendment

lambda-esm-sqs-filters-sam/template.yaml
=> Fixed filter pattern (one too many brackets)

stepfunctions-eventbridge-schedule-sam-python/.gitignore, stepfunctions-eventbridge-schedule-sam-python/README.md, stepfunctions-eventbridge-schedule-sam-python/example-pattern.json, stepfunctions-eventbridge-schedule-sam-python/src/lambda/app.py, stepfunctions-eventbridge-schedule-sam-python/state_machine/create_schedules.asl.json, stepfunctions-eventbridge-schedule-sam-python/template.yaml
N/A
Example added for Step Functions to EventBridge Scheduler using SDK integration. Implemented with SAM and Python.
=> New Serverless pattern  - Step Functions to EB scheduler example added - SAM/Python

alb-lambda-pulumi-ts/.gitignore, alb-lambda-pulumi-ts/Pulumi.dev.yaml, alb-lambda-pulumi-ts/Pulumi.yaml, alb-lambda-pulumi-ts/README.nd, alb-lambda-pulumi-ts/example-pattern.json, alb-lambda-pulumi-ts/index.ts, alb-lambda-pulumi-ts/lambda/index.ts, alb-lambda-pulumi-ts/lambda/package.json, alb-lambda-pulumi-ts/package.json, alb-lambda-pulumi-ts/tsconfig.json
*Issue #, if available:* #1084
Adding a Pulumi pattern to deploy a lambda function behind an ALB
=> Added pattern for alb to lambda with Pulumi

cloudwatch-logs-subscription-lambda-sam/README.md, cloudwatch-logs-subscription-lambda-sam/example-pattern.json, cloudwatch-logs-subscription-lambda-sam/src/app.js, cloudwatch-logs-subscription-lambda-sam/template.yaml
A new pattern is added in the folder cloudwatch-logs-subscription-lambda-sam
=> New serverless pattern - cloudwatch-logs-subscription-lambda-sam

eventbridge-sqs-cdk-typescript/.gitignore, eventbridge-sqs-cdk-typescript/.npmignore, eventbridge-sqs-cdk-typescript/README.md, eventbridge-sqs-cdk-typescript/bin/eventbridge-sqs-cdk.ts, eventbridge-sqs-cdk-typescript/cdk.json, eventbridge-sqs-cdk-typescript/event.json, eventbridge-sqs-cdk-typescript/eventbridge-sqs-cdk-typescript.json, eventbridge-sqs-cdk-typescript/jest.config.js, eventbridge-sqs-cdk-typescript/lib/eventbridge-sqs-cdk-stack.ts, eventbridge-sqs-cdk-typescript/lib/eventbridge-sqs.ts, eventbridge-sqs-cdk-typescript/package.json, eventbridge-sqs-cdk-typescript/test/eventbridge-sqs-cdk.test.ts, eventbridge-sqs-cdk-typescript/tsconfig.json
*Issue #, if available:* -
This is the typescript addition to an existing serverless pattern (EventBridge - SQS). It includes an L3 construct which users could also extract and make use as they deem fit.
=> feat: eventbridge to sqs pattern (typescript)

eventbridge-pipes-splitter-pattern/README.md, eventbridge-pipes-splitter-pattern/cdk/lib/cdk-stack.ts
Log Events for demonstration purposes
=> Log Splitter events

inspector-lambda/README.md, inspector-lambda/app.py, inspector-lambda/cdk.json, inspector-lambda/example-pattern.json, inspector-lambda/src/InspectorFindings.py, inspector-lambda/src/InspectorInitialScan.py
*Issue #, if available:* #1118
A new CDK pattern that sends Inspector finding and initial scan events to Lambda for processing then S3 for storage. 
=> New Pattern inspector-lambda

lambda-destinations-sam/README.md, lambda-destinations-sam/example-pattern.json, lambda-destinations-sam/src/app1.js, lambda-destinations-sam/src/app2.js, lambda-destinations-sam/template.yaml
A new pattern is added in the folder lambda-destinations-sam
=> New pattern lambda-destinations-sam

eventbridge-schedule-to-sqs-cdk-python/.gitignore, eventbridge-schedule-to-sqs-cdk-python/README.md, eventbridge-schedule-to-sqs-cdk-python/app.py, eventbridge-schedule-to-sqs-cdk-python/cdk.json, eventbridge-schedule-to-sqs-cdk-python/eventbridge_schedule_to_sqs_cdk_python/eventbridge_schedule_to_sqs_cdk_python_stack.py, eventbridge-schedule-to-sqs-cdk-python/example-pattern.json, eventbridge-schedule-to-sqs-cdk-python/requirements.txt, eventbridge-schedule-to-sqs-cdk-python/source.bat
Added pattern for EventBridge Scheduler to send a message to Amazon SQS every 5 minutes. The pattern is deployed using the AWS CDK for Python. 
=> New Serverless pattern - EventBridge Scheduler to Amazon SQS

sam-webapp-cognito/example-pattern.json
=> sam pattern for web application

eventbridge-schedule-to-lambda-cdk-java/README.md, eventbridge-schedule-to-lambda-cdk-java/cdk.json, eventbridge-schedule-to-lambda-cdk-java/example-pattern.json, eventbridge-schedule-to-lambda-cdk-java/pom.xml, eventbridge-schedule-to-lambda-cdk-java/src/main/java/com/myorg/CdkSchedulerApp.java, eventbridge-schedule-to-lambda-cdk-java/src/main/java/com/myorg/CdkSchedulerStack.java, eventbridge-schedule-to-lambda-cdk-java/src/main/java/com/myorg/SchedulerHandler.java, eventbridge-schedule-to-lambda-cdk-java/src/test/java/com/myorg/CdkSchedulerTest.java, eventbridge-schedule-to-lambda-sam-java/README.md, eventbridge-schedule-to-lambda-sam-java/ScheduledFunction/pom.xml, eventbridge-schedule-to-lambda-sam-java/ScheduledFunction/src/main/java/com/serverlessland/App.java, eventbridge-schedule-to-lambda-sam-java/ScheduledFunction/src/test/java/com/serverlessland/AppTest.java, eventbridge-schedule-to-lambda-sam-java/events/event.json, eventbridge-schedule-to-lambda-sam-java/example-pattern.json, eventbridge-schedule-to-lambda-sam-java/template.yaml
*Issue #, if available: Will provide after creation of PR
*Description of changes: New EventBridge Schedule patterns for invoking lambda functions.  CDK and SAM versions in Java.  This is related to David Boyne's request to fill gaps for missing patterns for EventBridge Scheduler. 
=> New serverless patterns - EventBridge Schedule to invoke Lambda SAM and CDK Java

apigw-ddb-openapi-crud/.gitignore, apigw-ddb-openapi-crud/README.md, apigw-ddb-openapi-crud/api.yaml, apigw-ddb-openapi-crud/example-pattern.json, apigw-ddb-openapi-crud/load.yaml, apigw-ddb-openapi-crud/template.yaml, scripts/pattern-schema.json
*Description of changes:* New pattern dynamo crud with OpenAPI
=> new pattern: apigw - dynamo crud with OpenAPI

apigw-throttle-sam/.gitignore, apigw-throttle-sam/README.md, apigw-throttle-sam/example-pattern.json, apigw-throttle-sam/get-function/app.py, apigw-throttle-sam/get-function/requirements.txt, apigw-throttle-sam/load.yaml, apigw-throttle-sam/post-function/app.py, apigw-throttle-sam/post-function/requirements.txt, apigw-throttle-sam/template.yaml
*Description of changes:* A new pattern that creates an API Gateway REST API with API level throttling and resource/method level throttling.
=> new pattern apigw-throttling

apigw-data-validation/template.yaml
*Description of changes:* Fixing issues for validation
=> updated validation template

apigw-caching-sam/README.md, apigw-caching-sam/example-pattern.json, apigw-caching-sam/src/app.py, apigw-caching-sam/src/requirements.txt, apigw-caching-sam/template.yaml
*Description of changes:* New Pattern - APIGW with caching enabled
=> Added new pattern API gateway Sam

apigw-rest-edge-lambda/README.md, apigw-rest-edge-lambda/example-pattern.json, apigw-rest-edge-lambda/template.yaml
*Issue #1222, if available:*
New pattern : Edge-Optimized API with Lambda integration written in python
=> New serverless pattern - Edge-Optimized API with Lambda 

apigw-http-api-lambda-python/README.md, apigw-http-api-lambda-python/example-pattern.json, apigw-http-api-lambda-python/template.yaml
*Issue #1210, if available:*
New pattern : simple HTTP API with Lambda integration written in python
=> New serverless pattern - http api lambda in python

cw-sns-secretsmanager/README.md, cw-sns-secretsmanager/example-pattern.json, cw-sns-secretsmanager/src/app.js, cw-sns-secretsmanager/template.yaml
*Issue #, if available:* #1199
*Description of changes:* This pattern explains how to deploy a SAM application that Detects and Notify on Amazon Secrets Manager Secret Key Creation, Updation and Deletion using Amazon CloudWatch event and Amazon SNS
=> New serverless pattern - cloudwatch-sns-secretsmanager

eventbridge-schedule-to-sqs-cdk-typescript/.gitignore, eventbridge-schedule-to-sqs-cdk-typescript/.npmignore, eventbridge-schedule-to-sqs-cdk-typescript/README.md, eventbridge-schedule-to-sqs-cdk-typescript/bin/eventbridge-schedule-to-sqs-cdk-typescript.ts, eventbridge-schedule-to-sqs-cdk-typescript/cdk.json, eventbridge-schedule-to-sqs-cdk-typescript/example-pattern.json, eventbridge-schedule-to-sqs-cdk-typescript/jest.config.js, eventbridge-schedule-to-sqs-cdk-typescript/lib/eventbridge-schedule-to-sqs-cdk-typescript-stack.ts, eventbridge-schedule-to-sqs-cdk-typescript/package.json, eventbridge-schedule-to-sqs-cdk-typescript/tsconfig.json
This pattern creates an EventBridge Schedule to send a message to Amazon SQS every 5 minutes. The pattern is deployed using the AWS CDK for TypeScript. 
=> Initial creation of pattern - EventBridge Scheduler to send messages to SQS using CDK for TypeScript

apigw-execution-logs/README.md, apigw-execution-logs/example-pattern.json, apigw-execution-logs/template.yaml
Issue #, if available: [1220](https://github.com/aws-samples/serverless-patterns/issues/1220#issue-1661679263)
Description of changes: Created folder apigw-execution-logs which contains SAM tempalte for REST API with execution logs
=> New serverless pattern - apigw-execution-access-logs

eventbridge-scheduler-ssm-cdk-typescript/.gitignore, eventbridge-scheduler-ssm-cdk-typescript/.npmignore, eventbridge-scheduler-ssm-cdk-typescript/README.md, eventbridge-scheduler-ssm-cdk-typescript/bin/eventbridge-scheduler-ssm-cdk-typescript.ts, eventbridge-scheduler-ssm-cdk-typescript/cdk.json, eventbridge-scheduler-ssm-cdk-typescript/example-pattern.json, eventbridge-scheduler-ssm-cdk-typescript/jest.config.js, eventbridge-scheduler-ssm-cdk-typescript/lib/eventbridge-scheduler-ssm-cdk-typescript-stack.ts, eventbridge-scheduler-ssm-cdk-typescript/package.json, eventbridge-scheduler-ssm-cdk-typescript/test/eventbridge-scheduler-ssm-cdk-typescript.test.ts, eventbridge-scheduler-ssm-cdk-typescript/tsconfig.json
This pattern demonstrates how to create an EventBridge scheduler to run SSM Associations using AWS Cloud Development Kit (CDK) for Typescript.
=> Kimevgaws feature eventbridge scheduler ssm cdk typescript

eventbridge-scheduler-ssm-cdk-typescript/README.md, eventbridge-scheduler-ssm-cdk-typescript/example-pattern.json
=> updated service names

apigw-domain-edge-lambda/README.md, apigw-domain-edge-lambda/example-pattern.json, apigw-domain-edge-lambda/template.yaml, apigw-mappingtemplate-lambda-nodejs/README.md, apigw-mappingtemplate-lambda-nodejs/example-pattern.json, apigw-mappingtemplate-lambda-nodejs/template.yaml, apigw-private-lambda/README.md, apigw-private-lambda/example-pattern.json, apigw-private-lambda/template.yaml, lambda-version-alias/README.md, lambda-version-alias/example-pattern.json, lambda-version-alias/template.yaml
*Issue #1319, if available:*
New SAM template that creates a lambda function associated with an alias and a version.
Lambda in python3.9 returns a message. 
For every update on the CloudFormaion stack: the function's code and the version description need to be updated to trigger the changeset and create a new version
=> New serverless pattern -  lambda with alias and version 

apigw-private-lambda/README.md, apigw-private-lambda/example-pattern.json, apigw-private-lambda/template.yaml
*Issue #1298, if available:*
New SAM template to create a private API integrated with Lambda python3.9
=> New serverless pattern - private api gateway with lambda

apigw-domain-edge-lambda/README.md, apigw-domain-edge-lambda/example-pattern.json, apigw-domain-edge-lambda/template.yaml, apigw-private-lambda/README.md, apigw-private-lambda/example-pattern.json, apigw-private-lambda/template.yaml
*Issue #1308, if available:*
New SAM template to create a regional rest api gateway with an edge-optimized domain anme and integrated with lambda in python3.9
=> New serverless pattern - api gateway with edge-optimized domain name and lambda

apigw-domain-edge-lambda/README.md, apigw-domain-edge-lambda/example-pattern.json, apigw-domain-edge-lambda/template.yaml, apigw-mappingtemplate-lambda-nodejs/README.md, apigw-mappingtemplate-lambda-nodejs/example-pattern.json, apigw-mappingtemplate-lambda-nodejs/template.yaml, apigw-private-lambda/README.md, apigw-private-lambda/example-pattern.json, apigw-private-lambda/template.yaml
*Issue #1317, if available:*
New SAM Template to create a Regional REST API with a mapping template in the integration request to pass to the lambda function. Lambda is written in nodejs.18. 
=> New serverless pattern - api gateway mapping template to lambda in nodejs

dynamodb-eventbridge-transformer/README.md, dynamodb-eventbridge-transformer/example-pattern.json, dynamodb-eventbridge-transformer/src/.gitignore, dynamodb-eventbridge-transformer/src/.npmignore, dynamodb-eventbridge-transformer/src/README.md, dynamodb-eventbridge-transformer/src/bin/pipes-from-dynamo.ts, dynamodb-eventbridge-transformer/src/cdk.json, dynamodb-eventbridge-transformer/src/jest.config.js, dynamodb-eventbridge-transformer/src/lib/lambda/writeDemoData.js, dynamodb-eventbridge-transformer/src/lib/pipes-from-dynamo-stack.ts, dynamodb-eventbridge-transformer/src/package.json, dynamodb-eventbridge-transformer/src/test/pipes-from-dynamo.test.ts, dynamodb-eventbridge-transformer/src/tsconfig.json
*Description of changes:* Added "AWS DynamoDB Streams to Event Bridge using Input Transformer" pattern.
=> added dynamodb-eventbridge-transformer

eventbridge-schedule-to-lambda-terraform-python/.gitignore, eventbridge-schedule-to-lambda-terraform-python/README.md, eventbridge-schedule-to-lambda-terraform-python/example-pattern.json, eventbridge-schedule-to-lambda-terraform-python/main.tf, eventbridge-schedule-to-lambda-terraform-python/src/eventbridge_function.py
*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1304
Pattern creates an EventBridge Scheduler to invoke a Python based Lambda function. Resources deployed using Terraform. 
=> New Pattern: EventBridge Scheduler to Invoke Python based Lambda (Terraform)

eventbridge-schedule-to-lambda-terraform-typescript/.gitignore, eventbridge-schedule-to-lambda-terraform-typescript/README.md, eventbridge-schedule-to-lambda-terraform-typescript/example-pattern.json, eventbridge-schedule-to-lambda-terraform-typescript/main.tf, eventbridge-schedule-to-lambda-terraform-typescript/package.json, eventbridge-schedule-to-lambda-terraform-typescript/src/index.ts, eventbridge-schedule-to-lambda-terraform-typescript/tsconfig.json
*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1321
The pattern creates an EventBridge Scheduler schedule to invoke a TypeScript based Lambda function every 5 minutes. Resources deployed using Terraform. 
=> New Pattern: EventBridge Scheduler to TypeScript based Lambda function (Terraform)

eventbridge-schedule-to-sqs-terraform/README.md, eventbridge-schedule-to-sqs-terraform/example-pattern.json, eventbridge-schedule-to-sqs-terraform/main.tf
This pattern uses EventBridge Scheduler to send messages to an SQS queue every minute.
=> New serverless pattern - eventbridge-schedule-to-sqs-terraform

eventbridge-schedule-to-sqs-sam/.gitignore, eventbridge-schedule-to-sqs-sam/README.md, eventbridge-schedule-to-sqs-sam/example-pattern.json, eventbridge-schedule-to-sqs-sam/template.yaml
Issue: https://github.com/aws-samples/serverless-patterns/issues/1324
This pattern creates an EventBridge Scheduler schedule to send a message to SQS every 5 minutes. Resources deployed using SAM. 
=> New Pattern: EventBridge Scheduler to SQS (AWS SAM)

eventbridge-schedule-to-lambda-terraform-go/.gitignore, eventbridge-schedule-to-lambda-terraform-go/README.md, eventbridge-schedule-to-lambda-terraform-go/example-pattern.json, eventbridge-schedule-to-lambda-terraform-go/main.tf, eventbridge-schedule-to-lambda-terraform-go/src/go.mod, eventbridge-schedule-to-lambda-terraform-go/src/go.sum, eventbridge-schedule-to-lambda-terraform-go/src/main.go
*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1302
Pattern that creates an EventBridge Scheduler schedule to invoke a Go based Lambda function every 5 minutes. Resources are deployed using Terraform.
=> New Pattern: EventBridge Schedule to Go based Lambda (Terraform)

eventbridge-schedule-to-lambda-terraform-java/.gitignore, eventbridge-schedule-to-lambda-terraform-java/README.md, eventbridge-schedule-to-lambda-terraform-java/example-pattern.json, eventbridge-schedule-to-lambda-terraform-java/main.tf, eventbridge-schedule-to-lambda-terraform-java/pom.xml, eventbridge-schedule-to-lambda-terraform-java/src/main/java/com/example/EventBridgeFunction.java
*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1312
Pattern creates an EventBridge Scheduler schedule to invoke a Java based Lambda function. Resources deployed using Terraform. 
=> New Pattern: EventBridge Scheduler to invoke Java based Lambda function (Terraform)

eventbridge-schedule-stepfunctions-cdk/README.md, eventbridge-schedule-stepfunctions-cdk/cdk/.gitignore, eventbridge-schedule-stepfunctions-cdk/cdk/.npmignore, eventbridge-schedule-stepfunctions-cdk/cdk/README.md, eventbridge-schedule-stepfunctions-cdk/cdk/bin/evenbridge-schedule-stepfunction.ts, eventbridge-schedule-stepfunctions-cdk/cdk/cdk.json, eventbridge-schedule-stepfunctions-cdk/cdk/jest.config.js, eventbridge-schedule-stepfunctions-cdk/cdk/lib/evenbridge-schedule-stepfunction-stack.ts, eventbridge-schedule-stepfunctions-cdk/cdk/package.json, eventbridge-schedule-stepfunctions-cdk/cdk/test/evenbridge-schedule-stepfunction.test.ts, eventbridge-schedule-stepfunctions-cdk/cdk/tsconfig.json, eventbridge-schedule-stepfunctions-cdk/example-pattern.json
Pattern showing EventBridge scheduler starting execution of StepFunctions state-machine every 5 minutes.
=> New Pattern: EventBridge Scheduler to StepFunctions with CDK

lambda-jbang/JBangFunction/JBangHandler.java, lambda-jbang/JBangFunction/Makefile, lambda-jbang/JBangFunction/model/Person.java, lambda-jbang/README.md, lambda-jbang/example-pattern.json, lambda-jbang/template.yml
*Issue #1341:*
*Description of changes:*<br>
Add a new Serverless Pattern for AWS Lambda function using JBang.
This project uses JBang instead of Maven or Gradle for simplification. 
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
=> #1341: Add pattern for AWS Lambda function using JBang

eventbridge-pipes-ddb-stream-apigateway-iot-core-cdk/example-pattern.json
=> fixed LinkedIN links

apigw-cors-nonproxy/README.md, apigw-cors-nonproxy/example-pattern.json, apigw-cors-nonproxy/template.yaml, apigw-cors-proxy/README.md, apigw-cors-proxy/example-pattern.json, apigw-cors-proxy/template.yaml
*Issue #, if available: #1378
*Description of changes: Added example-pattern.json, README.md, template.yaml
=> REST API CORS non proxy integration template

eventbridge-schedule-to-sqs-terraform/example-pattern.json
Added profile picture link to appear on ServerlessLand
=> Fix - Added profile picture 

rds-sns-event-notification/README.md, rds-sns-event-notification/example-pattern.json, rds-sns-event-notification/template.yaml
recreating this PR as it was corrupted: https://github.com/aws-samples/serverless-patterns/pull/1251
=> adding a pattern that was courrupted

cdk-apigw-authorizer-sqs/example-pattern.json
*Description of changes: This pattern also referred to as Queue-Based leveling pattern can be useful when desigining Event driven architectures (EDA). Customers facing performance issues, when processing synchronous and webhook call, during extremely high peak traffic can avoid such situations by adapting this architectural strategy. A SQS queue will acts as a buffer for these synchronous requests and permits you to decouple the sender from the receiver. This pattern offers an easy solution to bridge the gap using AWS services that can easily plugin to customers existing architecture.
=>  Queue-Based Leveling pattern - apigateway-lambdaAuthorizer-SQS

eventbridge-cloudevents-transformer-cdk-typescript/README.md, eventbridge-cloudevents-transformer-cdk-typescript/example-pattern.json, eventbridge-cloudevents-transformer-cdk-typescript/src/.gitignore, eventbridge-cloudevents-transformer-cdk-typescript/src/.npmignore, eventbridge-cloudevents-transformer-cdk-typescript/src/bin/eb-lambda-cloudevents.ts, eventbridge-cloudevents-transformer-cdk-typescript/src/cdk.json, eventbridge-cloudevents-transformer-cdk-typescript/src/jest.config.js, eventbridge-cloudevents-transformer-cdk-typescript/src/lambda/index.ts, eventbridge-cloudevents-transformer-cdk-typescript/src/lib/eb-lambda-cloudevents-stack.ts, eventbridge-cloudevents-transformer-cdk-typescript/src/package.json, eventbridge-cloudevents-transformer-cdk-typescript/src/tsconfig.json
Closes: #1433
Add new pattern describing how to use EventBridge input transformations to convert EventBridge events to CloudEvents.
=> feat: add eventbridge cloudevents transformer pattern

cognito-restapi/README.md
Fixed the pattern URL(currently it was pointing to broken/non-existent) URL. Fixed a typo
=> Update to pattern cognito-restapi

eventbridge-schedule-to-eventbridge-terraform/README.md, eventbridge-schedule-to-eventbridge-terraform/example-pattern.json, eventbridge-schedule-to-eventbridge-terraform/main.tf
This pattern is for sending custom metrics to EventBridge with Scheduler using Terraform
=> New serverless pattern - EventBridge Schedule to Eventbridge using Terraform

sns-lambda-slack-integration-SAM/.gitignore, sns-lambda-slack-integration-SAM/README.md, sns-lambda-slack-integration-SAM/events/event.json, sns-lambda-slack-integration-SAM/example-pattern.json, sns-lambda-slack-integration-SAM/hello_world/app.py, sns-lambda-slack-integration-SAM/hello_world/requirements.txt, sns-lambda-slack-integration-SAM/template.yaml, sns-lambda-slack-integration-SAM/tests/integration/test_api_gateway.py, sns-lambda-slack-integration-SAM/tests/requirements.txt, sns-lambda-slack-integration-SAM/tests/unit/test_handler.py
User needs to create slack channel and create workflow as well. After that, they need to copy their webhook url in the lambda function.
Created workflow for SNS-Lambda-Slack- SAM integration:
=> Adding repo for sns-lambda-slack-integration-SAM

eventbridge-pipes-ddbstream-to-eventbridge-suffix-matching/README.md, eventbridge-pipes-ddbstream-to-eventbridge-suffix-matching/example-pattern.json, eventbridge-pipes-ddbstream-to-eventbridge-suffix-matching/template.yaml
=> DynamoDB to EventBridge Bus using Pipes and Suffix filtering

eventbridge-schedule-to-step-function-terraform/example-pattern.json
Added link to author image to display on ServerlessLand for the new EB Scheduler to Step Function Pattern - Terraform
=> Added author image - Eventbridge Scheduler to Step Function Pattern Terraform

kinesis-data-stream-firehose-apigw-sam/README.md, kinesis-data-stream-firehose-apigw-sam/example-pattern.json, kinesis-data-stream-firehose-apigw-sam/src/lambda_authorizer.py, kinesis-data-stream-firehose-apigw-sam/src/lambda_function.py, kinesis-data-stream-firehose-apigw-sam/template.yaml
This pattern demonstrated how to POST data received by Kinesis Data Stream to HTTP Endpoint securely using Kinesis Data Firehose
=> Kinesis Data Stream to API Gateway via Data Firehose

s3-lambda-rekognition-ddb-cdk/.gitignore, s3-lambda-rekognition-ddb-cdk/.npmignore, s3-lambda-rekognition-ddb-cdk/README.md, s3-lambda-rekognition-ddb-cdk/bin/s3-lambda-rekognition.ts, s3-lambda-rekognition-ddb-cdk/cdk.json, s3-lambda-rekognition-ddb-cdk/example-pattern.json, s3-lambda-rekognition-ddb-cdk/jest.config.js, s3-lambda-rekognition-ddb-cdk/lib/rekognitionLambda/lambda_function.py, s3-lambda-rekognition-ddb-cdk/lib/s3-lambda-rekognition-stack.ts, s3-lambda-rekognition-ddb-cdk/package.json, s3-lambda-rekognition-ddb-cdk/test/s3-lambda-rekognition.test.ts, s3-lambda-rekognition-ddb-cdk/tsconfig.json
This pattern will give guidance for event driven architectures on classification of images using Rekognition and updating DynamoDB.
=> New Serverless Pattern - S3-Lambda-Rekognition-DDB

s3-lambda-rekognition-iot-cdk/.gitignore, s3-lambda-rekognition-iot-cdk/.npmignore, s3-lambda-rekognition-iot-cdk/README.md, s3-lambda-rekognition-iot-cdk/bin/s3-lambda-rekognition-iot.ts, s3-lambda-rekognition-iot-cdk/cdk.json, s3-lambda-rekognition-iot-cdk/example-pattern.json, s3-lambda-rekognition-iot-cdk/jest.config.js, s3-lambda-rekognition-iot-cdk/lib/ppeDetectionFunction/lambda_function.py, s3-lambda-rekognition-iot-cdk/lib/s3-lambda-rekognition-iot-stack.ts, s3-lambda-rekognition-iot-cdk/package.json, s3-lambda-rekognition-iot-cdk/test/s3-lambda-rekognition.test.ts, s3-lambda-rekognition-iot-cdk/tsconfig.json
This pattern will give guidance for event driven architectures to detect if a person is wearing PPE or not. This pattern works in conjunction with the IoT Puppy Park workshop (https://catalog.workshops.aws/iot-puppy-park/en-US) or independently. 
=> add s3-lambda-rekognition-iot pattern

firehose-transformation-sam-python/README.md, firehose-transformation-sam-python/example-pattern.json, firehose-transformation-sam-python/src/app.py, firehose-transformation-sam-python/template.yaml
Kinesis Data Firehose data transformation with Lambda pattern using SAM and Python-based function
=> New serverless pattern - firehose-transformation-sam-python

s3-eventbridge-sns-cdk/README.md, s3-eventbridge-sns-cdk/example-pattern.json, s3-eventbridge-sns-cdk/src/.gitignore, s3-eventbridge-sns-cdk/src/.npmignore, s3-eventbridge-sns-cdk/src/README.md, s3-eventbridge-sns-cdk/src/bin/s3-eventbridge-sns-cdk.ts, s3-eventbridge-sns-cdk/src/cdk.json, s3-eventbridge-sns-cdk/src/jest.config.js, s3-eventbridge-sns-cdk/src/lib/s3-eventbridge-sns-stack.ts, s3-eventbridge-sns-cdk/src/package.json, s3-eventbridge-sns-cdk/src/test/src.test.ts, s3-eventbridge-sns-cdk/src/tsconfig.json
=> Rajesaws feature s3 eventbridge sns serverless

apigw-websocket-api-sns-terraform/README.md, apigw-websocket-api-sns-terraform/example-pattern.json, apigw-websocket-api-sns-terraform/main.tf
=> New serverless pattern - apigw-websocket-api-sns-terraform

apigw-lambda-snapstart/README.md, apigw-lambda-snapstart/UnicornFunction/pom.xml, apigw-lambda-snapstart/example-pattern.json, apigw-lambda-snapstart/template.yaml
n/a
Updated to the latest version of the aws-serverless-java-container
=> Updated to SnapStart pattern

msk-lambda-iam-go-sam/HandlerKafka/go.mod, msk-lambda-iam-go-sam/HandlerKafka/go.sum, msk-lambda-iam-go-sam/HandlerKafka/main.go, msk-lambda-iam-go-sam/HandlerKafka/main_test.go, msk-lambda-iam-go-sam/Makefile, msk-lambda-iam-go-sam/README.md, msk-lambda-iam-go-sam/events/event.json, msk-lambda-iam-go-sam/example-pattern.json, msk-lambda-iam-go-sam/template.yaml
=> Msk go iam

msk-lambda-iam-go-sam/HandlerKafka/go.mod, msk-lambda-iam-go-sam/HandlerKafka/go.sum, msk-lambda-iam-go-sam/HandlerKafka/main.go, msk-lambda-iam-go-sam/HandlerKafka/main_test.go, msk-lambda-iam-go-sam/Makefile, msk-lambda-iam-go-sam/README.md, msk-lambda-iam-go-sam/events/event.json, msk-lambda-iam-go-sam/example-pattern.json, msk-lambda-iam-go-sam/template.yaml
Sample SAM project to use IAM authentication with MSK, with Lambda function coded in Golang
=> MSK IAM authentication using Golang

sqs-lambda-ddb-sam-ts/deploy.sh, sqs-lambda-ddb-sam-ts/test.sh
#1648 
Remove commented out code and redundant command checks
=> #1648: code clean-up in shell scripts (pattern has been merged into main already)

lambda-elastic-ip-no-nat-gateway-cdk/README.md, lambda-elastic-ip-no-nat-gateway-cdk/cdk/lib/cdk-stack.ts, lambda-elastic-ip-no-nat-gateway-cdk/cdk/src/lambdas/associate-lambda-elastic-ip-cr.ts, lambda-elastic-ip-no-nat-gateway-cdk/cdk/src/types/associate-lambda-elastic-ip-event.ts, lambda-elastic-ip-no-nat-gateway-cdk/example-pattern.json
*Issue #, if available:  #1642*
Removed the function name from the filter
Added documentation
This is a follow up PR to [this PR](https://github.com/aws-samples/serverless-patterns/pull/1644)
=> [Follow up PR] New pattern submission: Lambda Elastic IP without NAT Gateway

apigw-lambda-sns-sms/README.md, apigw-lambda-sns-sms/example-pattern.json, apigw-lambda-sns-sms/src/lambda_function.py, apigw-lambda-sns-sms/template.yaml
This pattern shows an example how a phone number can be validated and how a SMS message can be send using SMS Publish APIs via API Gateway and Lambda deployed using SAM.  
=> apigw-lambda-sns-sms pattern

eventbridge-fan-in-terraform/.gitignore, eventbridge-fan-in-terraform/README.md, eventbridge-fan-in-terraform/data.tf, eventbridge-fan-in-terraform/example-pattern.json, eventbridge-fan-in-terraform/main.tf, eventbridge-fan-in-terraform/outputs.tf, eventbridge-fan-in-terraform/provider.tf, eventbridge-fan-in-terraform/src/app.js, eventbridge-fan-in-terraform/terraform.tfvars, eventbridge-fan-in-terraform/variables.tf
=> Abulbul feature eventbridge fan in terraform

eventbridge-sns-lambda-terraform/README.md, eventbridge-sns-lambda-terraform/event.json, eventbridge-sns-lambda-terraform/example-pattern.json, eventbridge-sns-lambda-terraform/main.tf, eventbridge-sns-lambda-terraform/src/app.js
This commit adds the pattern for eventbridge-sns-lambda pattern using terraform 
=> Add eventbridge-sns-lambda terraform pattern

apigw-lambda-rds-snapstart/example-pattern.json, apigw-lambda-rds-snapstart/infrastructure/cdk/pom.xml, apigw-lambda-rds-snapstart/infrastructure/cdk/src/main/java/com/unicorn/DatabaseSetupConstruct.java, apigw-lambda-rds-snapstart/infrastructure/cdk/src/main/java/com/unicorn/InfrastructureStack.java, apigw-lambda-rds-snapstart/infrastructure/cdk/src/main/java/com/unicorn/UnicornStoreStack.java, apigw-lambda-rds-snapstart/software/unicorn-store/pom.xml
Maintenance 
Updated the pattern to use Java 17.
Updated the InfrastructureStack.java to use the L2 SnapStart support.
=> Updated the pattern to use Java 17.

kinesis-lambda-ddb-cdk-java/README.md, kinesis-lambda-ddb-cdk-java/cdk.json, kinesis-lambda-ddb-cdk-java/example-pattern.json, kinesis-lambda-ddb-cdk-java/lambda-code/index.py, kinesis-lambda-ddb-cdk-java/lambda-code/sample-test-event.json, kinesis-lambda-ddb-cdk-java/pom.xml, kinesis-lambda-ddb-cdk-java/src/main/java/com/myorg/KinesisLambdaDdbCdkJavaApp.java, kinesis-lambda-ddb-cdk-java/src/main/java/com/myorg/KinesisLambdaDdbCdkJavaStack.java, kinesis-lambda-ddb-cdk-java/src/test/java/com/myorg/KinesisLambdaDdbCdkJavaTest.java, kinesis-lambda-ddb-cdk-java/template.yaml
*Issue #1688
This pattern creates an Amazon [Kinesis Data Stream](https://docs.aws.amazon.com/streams/latest/dev/introduction.html) and an AWS [Lambda function](https://docs.aws.amazon.com/lambda/latest/dg/welcome.html) which then sends the records to DynamoDB, using the AWS Cloud Development Kit (AWS CDK) in Java.
=> New serverless pattern - kinesis-lambda-ddb-cdk-java

pipes-msk-to-salesforce-apidestination/README.md, pipes-msk-to-salesforce-apidestination/example-pattern.json, pipes-msk-to-salesforce-apidestination/msk-cluster-stack.yaml, pipes-msk-to-salesforce-apidestination/pipes-stack.yaml, pipes-msk-to-salesforce-apidestination/producer-stack.yaml, pipes-msk-to-salesforce-apidestination/src/app.js, pipes-msk-to-salesforce-apidestination/template.yaml, pipes-msk-to-salesforce-apidestination/test.json, pipes-msk-to-salesforce-apidestination/vpc-stack.yaml
Added new pattern that shows sending data from MSK to Salesforce using EventBridge Pipes and API Destination
=> New Serverless pattern: MSK to Salesforce using EventBridge Pipes and API Destination

apigw-lambda-pinpoint/README.md, apigw-lambda-pinpoint/example-pattern.json, apigw-lambda-pinpoint/src/lambda_function.py, apigw-lambda-pinpoint/template.yaml
updated code, template, readme and json data after feedback from experts Pinpoint
=> updated code, template, readme and json data after feedback from experts

apigw-ses-transformation/README.md, apigw-ses-transformation/example-pattern.json, apigw-ses-transformation/template.yaml
New serverless pattern that creates an Amazon API Gateway REST API that integrates with an Amazon SES.
=> New serverless pattern - apigw-ses-transformation

apigw-ses-transformation/README.md, apigw-ses-transformation/example-pattern.json
- Fixed broken links after initial code submission
=> Fix broken link for apigw-to-ses

sns-sqs-lambda-xray/.gitignore, sns-sqs-lambda-xray/README.md, sns-sqs-lambda-xray/consumer_app/app.py, sns-sqs-lambda-xray/example-pattern.json, sns-sqs-lambda-xray/producer_app/app.py, sns-sqs-lambda-xray/share_layer/requirements.txt, sns-sqs-lambda-xray/template.yaml
Add new pattern: X-ray trace for SNS to SQS to Lambda with Lambda Powertool for Python
=> Add new pattern xray trace for sns to sqs to lambda with Powertool

activemq-lambda/.gitignore, activemq-lambda/README.md, activemq-lambda/example-pattern.json, activemq-lambda/mq_listener/app.py, activemq-lambda/mq_listener/requirements.txt, activemq-lambda/template.yaml
Add new pattern Activemq-Lambda 
=> Add new pattern Activemq-Lambda

apigw-lambda-authorizer-basic-cdk/.gitignore, apigw-lambda-authorizer-basic-cdk/.npmignore, apigw-lambda-authorizer-basic-cdk/README.md, apigw-lambda-authorizer-basic-cdk/bin/apigw-lambda-authorizer-basic-cdk.js, apigw-lambda-authorizer-basic-cdk/cdk.json, apigw-lambda-authorizer-basic-cdk/example-pattern.json, apigw-lambda-authorizer-basic-cdk/jest.config.js, apigw-lambda-authorizer-basic-cdk/lambda/authorizer/index.js, apigw-lambda-authorizer-basic-cdk/lambda/protected/index.js, apigw-lambda-authorizer-basic-cdk/lib/basic-authorizer-construct.js, apigw-lambda-authorizer-basic-cdk/lib/basic-authorizer-stack.js, apigw-lambda-authorizer-basic-cdk/package.json, apigw-lambda-authorizer-basic-cdk/test/apigw-lambda-authorizer-basic-cdk.test.js
This pattern deploys an API Gateway REST API protected by a Lambda Authorizer supporting Basic HTTP Authentication.
=> New serverless pattern - apigw-lambda-authorizer-basic-cdk

cdn-dash-sam/README.md, cdn-dash-sam/example-pattern.json, cdn-dash-sam/src/lambda_function.py, cdn-dash-sam/template.yaml
*Issue #1781, if available:*
This pattern deploys Amazon Eventbridge rule and a AWS Lambda function that creates custom metrics in Amazon CloudWatch for the API mappings of the custom domain names that are present in the region.
=> New serverless pattern - cdn-dash-sam

apigw-rest-api-sqs-lambda-bedrock-cdk/README.md, apigw-rest-api-sqs-lambda-bedrock-cdk/example-pattern.json
The pattern description and the title is updated to reflect the pattern (as requested in the PR  #1729 comment).
=> The pattern description and the title is updated to reflect the pattern.

apigw-lambda-bedrock-cdk-python/apigw_lambda_bedrock/example-pattern.json
Updating instructions to use CDK instead of SAM
=> Update example-pattern.json (s/sam/cdk)

lambda-bedrock-response-streaming/README.md, lambda-bedrock-response-streaming/events/event.json, lambda-bedrock-response-streaming/pattern.json, lambda-bedrock-response-streaming/src/fn.mjs, lambda-bedrock-response-streaming/src/package.json, lambda-bedrock-response-streaming/template.yaml
Adding a pattern with Lambda and Bedrock response streaming
=> New serverless pattern - lambda-bedrock-response-streaming

cloudtrail-lambda-dynamodb-cdk/src/lib/tag-compliance-stack.ts
Added enforceSSL parameter to S3 bucket creation
=> Adding enforceSSL parameter to s3 bucket creation

sfn-sns-tf/README.md, sfn-sns-tf/example-pattern.json, sfn-sns-tf/main.tf
*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1871
*Description of changes:* The terraform template deploys a Step Functions workflow that sends the message to Amazon SNS and returns the response. The terraform template contains the minimum IAM resources required to run the application.
=> New serverless pattern - AWS Step Functions to SNS (Terraform)

vpc-lattice-lambda/README.md, vpc-lattice-lambda/demolambda/app.py, vpc-lattice-lambda/demolambda/requirements.txt, vpc-lattice-lambda/example-pattern.json, vpc-lattice-lambda/primary/app.py, vpc-lattice-lambda/secondary/app.py, vpc-lattice-lambda/template.yaml
Creating a new Serverless Pattern
=> Adding serverless pattern for traffic shift using VPC Lattice

lambda-translator/README.md, lambda-translator/example-pattern.json, lambda-translator/src/index.py, lambda-translator/template.yaml
"This pattern involves AWS lambda function that performs the translation in ream-time using AWS lambda.",
"User sends a request to  the AWS lambda function that consists of text along with the Source Language and the target language. lambda function performs the translation and returns the response.",
=> Serverless pattern to perform real-time translation using AWS Lambda

eventbridge-lambda-fsx-openzfs-periodic-replication/README.md, eventbridge-lambda-fsx-openzfs-periodic-replication/example-pattern.json, eventbridge-lambda-fsx-openzfs-periodic-replication/template.yaml
Modified previously approved pattern to use EventBridge Scheduler instead of EventBridge rule.
=> Minor update to existing pattern - Periodic FSx-OpenZFS volume replication across file systems using Amazon EventBridge Scheduler and AWS Lambda

terraform-ecs-efs-integration/Readme.md, terraform-ecs-efs-integration/bin/build.sh, terraform-ecs-efs-integration/bin/dir_md5.sh, terraform-ecs-efs-integration/containercode/Dockerfile, terraform-ecs-efs-integration/containercode/sample-bash.sh, terraform-ecs-efs-integration/example-pattern.json, terraform-ecs-efs-integration/main.tf, terraform-ecs-efs-integration/templates/ecr-lifecycle-policy.json, terraform-ecs-efs-integration/templates/ecs-role.json, terraform-ecs-efs-integration/templates/kms-policy.json, terraform-ecs-efs-integration/variables.tf, terraform-ecs-efs-integration/versions.tf
=> Nj80750 feature ecs efs integration

lambda-comprehend-language-sam/README.md, lambda-comprehend-language-sam/example-pattern.json, lambda-comprehend-language-sam/src/index.py, lambda-comprehend-language-sam/template.yaml
This pattern contains the source code in Python and supporting files for a serverless application that you can deploy with the SAM CLI. it creates a Lambda function (uses Python Boto3 SDK) that calls the Comprehend service to perform real-time detection of the dominant language of the input text.
=> Lambda to Comprehend to SAM for lang detection using Boto3

apigw-websocket-api-bedrock-streaming/README.md, apigw-websocket-api-bedrock-streaming/example-pattern.json, apigw-websocket-api-bedrock-streaming/src/cfnresponse.py, apigw-websocket-api-bedrock-streaming/src/getBoto3.py, apigw-websocket-api-bedrock-streaming/src/invoke.py, apigw-websocket-api-bedrock-streaming/src/onConnect.py, apigw-websocket-api-bedrock-streaming/src/onDisconnect.py, apigw-websocket-api-bedrock-streaming/src/supported_model_list.py, apigw-websocket-api-bedrock-streaming/template.yaml, apigw-websocket-api-bedrock-streaming/websocket-client.py
This pattern creates a WebSocket API and Lambda functions that provides a streaming response from the LLMs in Amazon Bedrock.
=> New serverless pattern: WebSocketApiGateway-Lambda-Bedrock with streaming response

eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/README.md, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/.gitignore, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/.npmignore, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/README.md, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/bin/scheduler-disable-rule.ts, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/cdk.json, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/jest.config.js, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/lib/scheduler-disable-rule-stack.ts, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/package.json, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/test/scheduler-disable-rule.test.ts, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/cdk/tsconfig.json, eventbridge-schedule-disable-eventbridge-rule-cdk-typescript/example-pattern.json
*Issue #, if available:* Closes: #1842
*Description of changes:* New pattern
=> feat: Disable EventBridge rules with EventBridge Scheduler

lambda-kinesis-lambda-js/README.md, lambda-kinesis-lambda-js/consumer/consumer-function.js, lambda-kinesis-lambda-js/example-pattern.json, lambda-kinesis-lambda-js/lambda-kinesis-lambda-js.json, lambda-kinesis-lambda-js/producer/package.json, lambda-kinesis-lambda-js/producer/producer-function.js, lambda-kinesis-lambda-js/template.yaml
This pattern talks about how to use Lambda functions with nodejs runtime to push and read records from a Kinesis Data Stream. This specifically demonstrates the implementation of serverless producer and consumer for a stream.
=> [New pattern] Lambda-Kinesis-Lambda js pattern

apigw-lambda-snapstart/UnicornFunction/pom.xml, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/config/DynamoDbConfig.java, apigw-lambda-snapstart/UnicornFunction/src/main/java/com/unicorn/store/data/DynamoDBUnicornRepository.java, apigw-lambda-snapstart/UnicornFunction/src/test/java/com/unicorn/store/StoreApplicationTest.java, apigw-lambda-snapstart/UnicornFunction/src/test/java/com/unicorn/store/data/DynamoDBUnicornRepositoryTest.java
N/A
The latest release of AWS SDK for Java v2 includes a sync client for CRT, so we can simplify the example and remove the async code.
=> Refactoring from async CRT client to the sync one.

apigw-comprehend/README.md, apigw-comprehend/apigw-comprehend.json, apigw-comprehend/example-pattern.json, apigw-comprehend/template.yaml
This sample project demonstrates how to use an API Gateway REST API as a proxy to Comprehend DetectSentiment API. You can easily utilise this solution to expose other Comprehend API operations as well with minimal efforts.
=> new pattern

sam-dynamodb-glue-transform/README.md, sam-dynamodb-glue-transform/example-pattern.json, sam-dynamodb-glue-transform/src/data/etl_data.py, sam-dynamodb-glue-transform/src/glue_jobs/transform_testtable.py, sam-dynamodb-glue-transform/src/main.py, sam-dynamodb-glue-transform/src/scripts/batch-orchestration-script.sh, sam-dynamodb-glue-transform/src/scripts/run-job.sh, sam-dynamodb-glue-transform/src/template.yml
*Description of changes:* New serverless pattern
=> New serverless pattern - sam-dynamodb-glue-transform

apigw-route53-failover/template.yaml
=> Update template.yaml. Fix mapping typo

activemq-lambda/template.yaml
This PR adds a metric tag to the activemq-lambda pattern.
=> Add metric tag for activemq-lambda pattern

alb-cognito-lambda/template.yaml, alb-lambda-rest-api-sam-py/template.yaml, alb-lambda-rust/template.yml, amplify_cognito_apigateway_lambda_envvariables/template.yaml, apigw-api-key/template.yaml, apigw-caching-sam/template.yaml, apigw-client-certificate/template.yaml, apigw-cloudwatch/template.yaml, apigw-comprehend/template.yaml, apigw-cors-nonproxy/template.yaml
Add metric tags to 10 more projects.
=> Add metric tags to templates

apigw-cors-proxy/template.yaml, apigw-custom-domain-edge/template.yaml, apigw-custom-domain-regional/template.yaml, apigw-custom-resource-policy/template.yaml, apigw-data-validation/template.yaml, apigw-ddb-openapi-crud/template.yaml, apigw-domain-edge-lambda/template.yaml, apigw-dynamodb-kinesis-lambda/template.yaml, apigw-dynamodb-lambda-scheduler-ses-auto-deletion-sam/template.yaml, apigw-ec2/template.yaml, apigw-eventbridge/template.yml, apigw-execution-access-logs/template.yaml, apigw-http-api-eventbridge-java/template.yaml, apigw-http-api-eventbridge/template.yaml, apigw-http-api-fifo-sqs-lambda-sns-sam/template.yaml, apigw-http-api-lambda-dotnet-sam/template.yaml, apigw-http-api-lambda-python/template.yaml, apigw-http-api-lambda-rds-proxy-java/template.yaml, apigw-http-api-lambda-rds-proxy/template.yaml, apigw-http-api-lambda-rust/template.yml, apigw-http-api-lambda/template.yml, apigw-iam/template.yaml, apigw-kinesis-lambda-ddb/template.yaml, apigw-kinesis-lambda/template.yaml, apigw-kinesis/template.yaml, apigw-lambda-authorizer-custom-header/template.yaml, apigw-lambda-authorizer/template.yaml, apigw-lambda-bedrock-js-sam/template.yaml, apigw-lambda-bedrock-sam/template.yaml, apigw-lambda-comprehend-sam/template.yaml
Add metric tags to SAM templates
=> Add metric tags

lambda-aurora-serverless/README.md, lambda-aurora-serverless/example-pattern.json, lambda-aurora-serverless/lambda-aurora.json
1.  include project JSON 
2. README: link to lambda-aurora-serverlessv2-postgresql
=> lambda-aurora-serverless: include project JSON and README changes

sam-dynamodb-glue-transform/sam-dynamodb-glue-transform.json
adding the json file for PR#2041
=> adding the json file for PR#2041

lambda-streaming-ttfb-write-sam-with-bedrock-streaming/src/index.js
- Add imports
- Fix string formatting
- Fix base64 to string conversion 
=> Bedrock Lambda Streaming fixes 

docdb-lambda-nodejs-sam/README.md, docdb-lambda-nodejs-sam/docdb-lambda-nodejs-sam.json, docdb-lambda-nodejs-sam/example-pattern.json, docdb-lambda-nodejs-sam/src/index.js, docdb-lambda-nodejs-sam/template.yaml, docdb-lambda/README.md, docdb-lambda/example-pattern.json, docdb-lambda/src/index.js, docdb-lambda/template.yaml
*Issue #2132 
New SAM Template that creates an AWS Lambda function to process events in an Amazon DocumentDB (with MongoDB compatibility) change stream by configuring an Amazon DocumentDB cluster as an event source 
=> New serverless pattern - DocumentDB Event Source to Lambda

apigw-lambda-authorizer/template.yaml
=> Updated nodejs version to 20, as 14 is  depreciated

auth0-eventbridge-lambda/README.md
*Issue #, if available:*  #2238
Updated pattern README to correct image reference path. 
=> Updated pattern README - auth0-eventbridge-lambda

apigw-http-api-lambda-ts-cdk/.gitignore, apigw-http-api-lambda-ts-cdk/.npmignore, apigw-http-api-lambda-ts-cdk/README.md, apigw-http-api-lambda-ts-cdk/apigw-http-api-lambda-cdk-ts.json, apigw-http-api-lambda-ts-cdk/bin/apigw-http-api-lambda-ts-cdk.ts, apigw-http-api-lambda-ts-cdk/cdk.json, apigw-http-api-lambda-ts-cdk/example-pattern.json, apigw-http-api-lambda-ts-cdk/lib/httpapi-lambda-stack.ts, apigw-http-api-lambda-ts-cdk/package.json, apigw-http-api-lambda-ts-cdk/resources/dummy.ts, apigw-http-api-lambda-ts-cdk/tsconfig.json
This pattern create an Amazon API Gateway HTTP API and a dummy Lambda function returning a simple "Hello World".
Node.js (Typescript)
CDK
Service from: API Gateway HTTP API (v2)
Service to: Lambda
This pattern creates an Amazon API Gateway HTTP API (v2) that integrates with an AWS Lambda function by using AWS Cloud Development Kit (AWS CDK).
Amazon API Gateway HTTP API is designed with minimal features so it can be offered at a lower price than the REST API. For more information, please read the official document [Choosing between REST APIs and HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html).
This pattern deploys a API Gateway HTTP API that is responsible to route the root path ("/") to the AWS Lambda function. The function (called 'dummy') …
=> New serverless pattern - apigw-http-api-lambda-ts-cdk

serverless-multi-tenant-api/README.md, serverless-multi-tenant-api/__tests__/unit/handlers/get-by-id.test.mjs, serverless-multi-tenant-api/__tests__/unit/handlers/put-item.test.mjs, serverless-multi-tenant-api/buildspec.yml, serverless-multi-tenant-api/env.json, serverless-multi-tenant-api/events/event-get-by-id.json, serverless-multi-tenant-api/events/event-post-item.json, serverless-multi-tenant-api/example-pattern.json, serverless-multi-tenant-api/package.json, serverless-multi-tenant-api/serverless-multi-tenant-api.json, serverless-multi-tenant-api/src/handlers/auth.mjs, serverless-multi-tenant-api/src/handlers/get-by-id.mjs, serverless-multi-tenant-api/src/handlers/put-item.mjs, serverless-multi-tenant-api/template.yaml
*Issue #, if available:*https://github.com/aws-samples/serverless-patterns/issues/2223
=> Serverless Multi Tenant API

apigw-http-api-step-functions-express-java/README.md, apigw-http-api-step-functions-express-java/apigw-http-api-step-functions-express-java.json, apigw-http-api-step-functions-express-java/cdk.json, apigw-http-api-step-functions-express-java/example-pattern.json, apigw-http-api-step-functions-express-java/pom.xml, apigw-http-api-step-functions-express-java/src/main/java/com/myorg/HttpApiGatewayStepFunctionsApp.java, apigw-http-api-step-functions-express-java/src/main/java/com/myorg/HttpApiGatewayStepFunctionsStack.java
Add a CDK implementation of a API Gateway HTTP API to a Step Functions Express Workflow.
=> New Serverless Pattern - API Gateway HTTP API to Step Functions Express Workflow [Java]

auth0-eventbridge-lambda/README.md
*Issue #, if available:* #2278
Edit to existing pattern - Updated links to image files in README
=> Edit to existing pattern - Updated links to image files in README

apigw-http-lambda-documentdb-cdk/lambda/app.ts
wrong default param
changed hardcoded efault string
=> updated wrong default string

s3-eventbridge-sfn-terraform/README.md, s3-eventbridge-sfn-terraform/example-pattern.json, s3-eventbridge-sfn-terraform/main.tf, s3-eventbridge-sfn-terraform/s3-eventbridge-sfn-terraform.json
Adding s3-eventbridge-sfn-terraform patterrn
Adding terraform version of s3-eventbridge-sfn pattern
https://serverlessland.com/patterns/s3-eventbridge-wildcard-sam
=> Add s3-eventbridge-sfn-terraform patterrn

apigw-rest-api-lambda-python/README.md, apigw-rest-api-lambda-python/apigw-rest-api-lambda-python.json, apigw-rest-api-lambda-python/events/event.json, apigw-rest-api-lambda-python/example-pattern.json, apigw-rest-api-lambda-python/hello_world/app.py, apigw-rest-api-lambda-python/hello_world/requirements.txt, apigw-rest-api-lambda-python/template.yaml, apigw-rest-api-lambda-python/tests/requirements.txt
Added template for REST API + Lambda Hello World tutorial in Python for the getting started project (guided walkthroughs). This tutorial is from the SAM CLI app templates ((https://github.com/aws/aws-sam-cli-app-templates/tree/master/python3.10/hello).
This template includes events, which I see is not the usual for serverless patterns, but necessary for the guided walkthrough in the IDE as the user will need to be given all the materials for running the app.
=> New pattern - REST API Hello World (Python)

apigw-rest-api-lambda-node/README.md, apigw-rest-api-lambda-node/apigw-rest-api-lambda-node.json, apigw-rest-api-lambda-node/events/event.json, apigw-rest-api-lambda-node/example-pattern.json, apigw-rest-api-lambda-node/hello_world/app.mjs, apigw-rest-api-lambda-node/hello_world/package.json, apigw-rest-api-lambda-node/template.yaml
Added template for REST API + Lambda Hello World tutorial in Node for the getting started project (guided walkthroughs). This tutorial is from the SAM CLI app templates (https://github.com/aws/aws-sam-cli-app-templates/tree/master/nodejs20.x/hello/%7B%7Bcookiecutter.project_name%7D%7D).
=> New pattern - REST API Hello World (Node)

apigw-rest-api-lambda-java/HelloWorldFunction/src/main/java/helloworld/App.java, apigw-rest-api-lambda-java/HelloWorldFunction/src/pom.xml, apigw-rest-api-lambda-java/README.md, apigw-rest-api-lambda-java/apigw-rest-api-lambda-java.json, apigw-rest-api-lambda-java/events/event.json, apigw-rest-api-lambda-java/example.pattern.json, apigw-rest-api-lambda-java/template.yaml
Added template for REST API + Lambda Hello World tutorial in Java21 for the getting started project (guided walkthroughs). This tutorial is from the SAM CLI app templates: https://github.com/aws/aws-sam-cli-app-templates/tree/master/java21/hello-maven
=> New pattern - REST API hello world (java)

.github/workflows/create_update_release.yaml
[PR 2429](https://github.com/aws-samples/serverless-patterns/pull/2429)
The above mentioned PR was failing while running GitHub Action with syntax error. Have corrected the changes in this PR.
*Acknowledgement:*
=> Correcting changes in Git Release 

.github/workflows/create_update_release.yaml
Issue #, if available:
https://github.com/aws-samples/serverless-patterns/pull/2429
The above mentioned PR was failing while running GitHub Action with syntax error. Have corrected the changes in this PR.
Acknowledgement:
=> Correcting Git Release

.gitignore, s3-lambda-resizing-java/README.md, s3-lambda-resizing-java/ResizerFunction/pom.xml, s3-lambda-resizing-java/ResizerFunction/src/main/java/resizer/App.java, s3-lambda-resizing-java/ResizerFunction/src/test/java/resizer/AppTest.java, s3-lambda-resizing-java/ResizerFunction/src/test/resources/events/s3_event.json, s3-lambda-resizing-java/example-pattern.json, s3-lambda-resizing-java/s3-lambda-resizing-java.json, s3-lambda-resizing-java/template.yaml
=> S3 notification event trigger Java-based AWS Lambda function

sqs-fifo-delayed-queue-dynamodb/example-pattern.json, sqs-fifo-delayed-queue-dynamodb/sqs-fifo-delayed-queue-dynamodb.json
=> sqs-fifo-delayed-queue-dynamodb update authors

s3-lambda-dotnet/event.json, s3-lambda/events/event.json
Add s3 event file to image resizing patterns in Node and .NET so users can test more easily
=> (fix) Add s3 event file to image resizing patterns in Node and .NET

appsync-bedrock-streaming-sam/README.md, appsync-bedrock-streaming-sam/example-pattern.json
=> (fix) - Correct naming of pattern

lambda-kendra-bedrock/template.yaml
modifying data source role to give access to S3
=> Update lambda-kendra-bedrock pattern: modifying data source role

eventbridge-pipes-sqs-to-redshift-cdk-python/README.md, eventbridge-pipes-sqs-to-redshift-cdk-python/eventbridge-pipes-sqs-to-redshift-cdk-python.json
=> change to template file path

lambda-aurora-serverlessv2-postgresql/template.yaml
In #2141, this transform was accidentally removed, breaking the template. This PR adds it back
I'm sorry for breaking this template.
=> Add the transform that was accidentally removed in #2141
